//go:build go1.25

// Code generated by cmd/extract; DO NOT EDIT.

package core

import (
	"hash"
	"reflect"

	"github.com/mvm-sh/mvm/stdlib"
)

func init() {
	m := stdlib.Values["hash"]
	m["Cloner"] = reflect.ValueOf((*hash.Cloner)(nil))
	m["XOF"] = reflect.ValueOf((*hash.XOF)(nil))
}
