//go:build go1.25

// Code generated by cmd/extract; DO NOT EDIT.

package ext

import (
	"io/fs"
	"reflect"

	"github.com/mvm-sh/mvm/stdlib"
)

func init() {
	m := stdlib.Values["io/fs"]
	m["Lstat"] = reflect.ValueOf(fs.Lstat)
	m["ReadLink"] = reflect.ValueOf(fs.ReadLink)
	m["ReadLinkFS"] = reflect.ValueOf((*fs.ReadLinkFS)(nil))
}
