//go:build go1.25

// Code generated by cmd/extract; DO NOT EDIT.

package ext

import (
	"log/slog"
	"reflect"

	"github.com/mvm-sh/mvm/stdlib"
)

func init() {
	m := stdlib.Values["log/slog"]
	m["GroupAttrs"] = reflect.ValueOf(slog.GroupAttrs)
}
