//go:build go1.25

// Code generated by cmd/extract; DO NOT EDIT.

package ext

import (
	"mime/multipart"
	"reflect"

	"github.com/mvm-sh/mvm/stdlib"
)

func init() {
	m := stdlib.Values["mime/multipart"]
	m["FileContentDisposition"] = reflect.ValueOf(multipart.FileContentDisposition)
}
