//go:build go1.25

// Code generated by cmd/extract; DO NOT EDIT.

package ext

import (
	"reflect"
	"runtime"

	"github.com/mvm-sh/mvm/stdlib"
)

func init() {
	m := stdlib.Values["runtime"]
	m["SetDefaultGOMAXPROCS"] = reflect.ValueOf(runtime.SetDefaultGOMAXPROCS)
}
