# Static linting of Go source files. See .golangci.yaml for options.
lint:
	golangci-lint run

# Generate standard library bindings from Go toolchain source.
# Also rebuilds stdlib/src.zip from the sibling github.com/mvm-sh/std
# clone via the //go:generate directive in stdlib/srcfs.go.
# Run after a fresh clone or after updating the Go toolchain or the std module.
# If you have no ../std clone and only need a buildable tree, `make stdzip`
# fetches the published std snapshot from the Go proxy instead.
generate:
	@mkdir -p bin
	go build -o bin/extract ./cmd/extract
	PATH="$(CURDIR)/bin:$$PATH" go generate ./...
	@cd stdlib && for plat in $$(go tool dist list | tr '/' '_'); do \
		os=$${plat%%_*}; arch=$${plat#*_}; \
		$(CURDIR)/bin/extract -goos $$os -goarch $$arch \
			-stdlib \
			syscall $$(go env GOROOT)/src/syscall; \
	done

clean_generate:
	@grep -rl "Code generated by cmd/extract" stdlib/core stdlib/ext 2>/dev/null | xargs rm -f
	rm -f stdlib/src.zip

# Module path of the bundled std snapshot. The embedded zip is always
# re-labeled with the synthetic version pinned in stdlib/stdmod/stdmod.go;
# only its source content comes from the version we build it against.
STD_MODULE := github.com/mvm-sh/std

# Rebuild stdlib/src.zip from the published std module on the Go proxy
# (honors GOPROXY). Use this when you have no sibling ../std clone and are
# not modifying std; to edit std, clone it next to mvm and run `make generate`.
stdzip:
	@dir=$$(go mod download -json $(STD_MODULE)@latest | sed -n 's/.*"Dir": *"\([^"]*\)".*/\1/p'); \
	if [ -z "$$dir" ]; then \
		echo "stdzip: could not resolve $(STD_MODULE) via the Go module proxy" >&2; exit 1; \
	fi; \
	echo "stdzip: building stdlib/src.zip from $$dir"; \
	cd stdlib && MVMSTD_SRC="$$dir" go run gen_stdzip.go

# Run tests with race detector, measure coverage.
test:
	go test -race -covermode=atomic -coverpkg=./... -coverprofile=cover.out ./interp

# Open coverage info in browser
cover: test
	go tool cover -html=cover.out

clean:
	rm -f mvm extract demo cover.out stdlib/src.zip
	$(MAKE) -C examples/c clean

.PHONY: clean clean_generate generate stdzip test cover lint
