// Code generated by gen_pools.go; DO NOT EDIT.
// Shape S37 pool: 256 slots.

package stubs

import (
	"unsafe"

	"github.com/mvm-sh/mvm/runtype"
)

const poolSizeS37 = 256

//go:noinline
func stubS37_0(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(0, recv) }

//go:noinline
func stubS37_1(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(1, recv) }

//go:noinline
func stubS37_2(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(2, recv) }

//go:noinline
func stubS37_3(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(3, recv) }

//go:noinline
func stubS37_4(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(4, recv) }

//go:noinline
func stubS37_5(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(5, recv) }

//go:noinline
func stubS37_6(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(6, recv) }

//go:noinline
func stubS37_7(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(7, recv) }

//go:noinline
func stubS37_8(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(8, recv) }

//go:noinline
func stubS37_9(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(9, recv) }

//go:noinline
func stubS37_10(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(10, recv) }

//go:noinline
func stubS37_11(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(11, recv) }

//go:noinline
func stubS37_12(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(12, recv) }

//go:noinline
func stubS37_13(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(13, recv) }

//go:noinline
func stubS37_14(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(14, recv) }

//go:noinline
func stubS37_15(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(15, recv) }

//go:noinline
func stubS37_16(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(16, recv) }

//go:noinline
func stubS37_17(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(17, recv) }

//go:noinline
func stubS37_18(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(18, recv) }

//go:noinline
func stubS37_19(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(19, recv) }

//go:noinline
func stubS37_20(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(20, recv) }

//go:noinline
func stubS37_21(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(21, recv) }

//go:noinline
func stubS37_22(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(22, recv) }

//go:noinline
func stubS37_23(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(23, recv) }

//go:noinline
func stubS37_24(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(24, recv) }

//go:noinline
func stubS37_25(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(25, recv) }

//go:noinline
func stubS37_26(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(26, recv) }

//go:noinline
func stubS37_27(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(27, recv) }

//go:noinline
func stubS37_28(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(28, recv) }

//go:noinline
func stubS37_29(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(29, recv) }

//go:noinline
func stubS37_30(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(30, recv) }

//go:noinline
func stubS37_31(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(31, recv) }

//go:noinline
func stubS37_32(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(32, recv) }

//go:noinline
func stubS37_33(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(33, recv) }

//go:noinline
func stubS37_34(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(34, recv) }

//go:noinline
func stubS37_35(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(35, recv) }

//go:noinline
func stubS37_36(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(36, recv) }

//go:noinline
func stubS37_37(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(37, recv) }

//go:noinline
func stubS37_38(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(38, recv) }

//go:noinline
func stubS37_39(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(39, recv) }

//go:noinline
func stubS37_40(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(40, recv) }

//go:noinline
func stubS37_41(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(41, recv) }

//go:noinline
func stubS37_42(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(42, recv) }

//go:noinline
func stubS37_43(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(43, recv) }

//go:noinline
func stubS37_44(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(44, recv) }

//go:noinline
func stubS37_45(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(45, recv) }

//go:noinline
func stubS37_46(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(46, recv) }

//go:noinline
func stubS37_47(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(47, recv) }

//go:noinline
func stubS37_48(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(48, recv) }

//go:noinline
func stubS37_49(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(49, recv) }

//go:noinline
func stubS37_50(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(50, recv) }

//go:noinline
func stubS37_51(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(51, recv) }

//go:noinline
func stubS37_52(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(52, recv) }

//go:noinline
func stubS37_53(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(53, recv) }

//go:noinline
func stubS37_54(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(54, recv) }

//go:noinline
func stubS37_55(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(55, recv) }

//go:noinline
func stubS37_56(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(56, recv) }

//go:noinline
func stubS37_57(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(57, recv) }

//go:noinline
func stubS37_58(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(58, recv) }

//go:noinline
func stubS37_59(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(59, recv) }

//go:noinline
func stubS37_60(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(60, recv) }

//go:noinline
func stubS37_61(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(61, recv) }

//go:noinline
func stubS37_62(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(62, recv) }

//go:noinline
func stubS37_63(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(63, recv) }

//go:noinline
func stubS37_64(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(64, recv) }

//go:noinline
func stubS37_65(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(65, recv) }

//go:noinline
func stubS37_66(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(66, recv) }

//go:noinline
func stubS37_67(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(67, recv) }

//go:noinline
func stubS37_68(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(68, recv) }

//go:noinline
func stubS37_69(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(69, recv) }

//go:noinline
func stubS37_70(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(70, recv) }

//go:noinline
func stubS37_71(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(71, recv) }

//go:noinline
func stubS37_72(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(72, recv) }

//go:noinline
func stubS37_73(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(73, recv) }

//go:noinline
func stubS37_74(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(74, recv) }

//go:noinline
func stubS37_75(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(75, recv) }

//go:noinline
func stubS37_76(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(76, recv) }

//go:noinline
func stubS37_77(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(77, recv) }

//go:noinline
func stubS37_78(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(78, recv) }

//go:noinline
func stubS37_79(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(79, recv) }

//go:noinline
func stubS37_80(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(80, recv) }

//go:noinline
func stubS37_81(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(81, recv) }

//go:noinline
func stubS37_82(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(82, recv) }

//go:noinline
func stubS37_83(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(83, recv) }

//go:noinline
func stubS37_84(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(84, recv) }

//go:noinline
func stubS37_85(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(85, recv) }

//go:noinline
func stubS37_86(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(86, recv) }

//go:noinline
func stubS37_87(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(87, recv) }

//go:noinline
func stubS37_88(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(88, recv) }

//go:noinline
func stubS37_89(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(89, recv) }

//go:noinline
func stubS37_90(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(90, recv) }

//go:noinline
func stubS37_91(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(91, recv) }

//go:noinline
func stubS37_92(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(92, recv) }

//go:noinline
func stubS37_93(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(93, recv) }

//go:noinline
func stubS37_94(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(94, recv) }

//go:noinline
func stubS37_95(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(95, recv) }

//go:noinline
func stubS37_96(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(96, recv) }

//go:noinline
func stubS37_97(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(97, recv) }

//go:noinline
func stubS37_98(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(98, recv) }

//go:noinline
func stubS37_99(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(99, recv) }

//go:noinline
func stubS37_100(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(100, recv) }

//go:noinline
func stubS37_101(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(101, recv) }

//go:noinline
func stubS37_102(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(102, recv) }

//go:noinline
func stubS37_103(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(103, recv) }

//go:noinline
func stubS37_104(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(104, recv) }

//go:noinline
func stubS37_105(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(105, recv) }

//go:noinline
func stubS37_106(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(106, recv) }

//go:noinline
func stubS37_107(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(107, recv) }

//go:noinline
func stubS37_108(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(108, recv) }

//go:noinline
func stubS37_109(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(109, recv) }

//go:noinline
func stubS37_110(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(110, recv) }

//go:noinline
func stubS37_111(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(111, recv) }

//go:noinline
func stubS37_112(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(112, recv) }

//go:noinline
func stubS37_113(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(113, recv) }

//go:noinline
func stubS37_114(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(114, recv) }

//go:noinline
func stubS37_115(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(115, recv) }

//go:noinline
func stubS37_116(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(116, recv) }

//go:noinline
func stubS37_117(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(117, recv) }

//go:noinline
func stubS37_118(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(118, recv) }

//go:noinline
func stubS37_119(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(119, recv) }

//go:noinline
func stubS37_120(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(120, recv) }

//go:noinline
func stubS37_121(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(121, recv) }

//go:noinline
func stubS37_122(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(122, recv) }

//go:noinline
func stubS37_123(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(123, recv) }

//go:noinline
func stubS37_124(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(124, recv) }

//go:noinline
func stubS37_125(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(125, recv) }

//go:noinline
func stubS37_126(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(126, recv) }

//go:noinline
func stubS37_127(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(127, recv) }

//go:noinline
func stubS37_128(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(128, recv) }

//go:noinline
func stubS37_129(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(129, recv) }

//go:noinline
func stubS37_130(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(130, recv) }

//go:noinline
func stubS37_131(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(131, recv) }

//go:noinline
func stubS37_132(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(132, recv) }

//go:noinline
func stubS37_133(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(133, recv) }

//go:noinline
func stubS37_134(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(134, recv) }

//go:noinline
func stubS37_135(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(135, recv) }

//go:noinline
func stubS37_136(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(136, recv) }

//go:noinline
func stubS37_137(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(137, recv) }

//go:noinline
func stubS37_138(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(138, recv) }

//go:noinline
func stubS37_139(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(139, recv) }

//go:noinline
func stubS37_140(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(140, recv) }

//go:noinline
func stubS37_141(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(141, recv) }

//go:noinline
func stubS37_142(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(142, recv) }

//go:noinline
func stubS37_143(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(143, recv) }

//go:noinline
func stubS37_144(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(144, recv) }

//go:noinline
func stubS37_145(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(145, recv) }

//go:noinline
func stubS37_146(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(146, recv) }

//go:noinline
func stubS37_147(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(147, recv) }

//go:noinline
func stubS37_148(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(148, recv) }

//go:noinline
func stubS37_149(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(149, recv) }

//go:noinline
func stubS37_150(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(150, recv) }

//go:noinline
func stubS37_151(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(151, recv) }

//go:noinline
func stubS37_152(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(152, recv) }

//go:noinline
func stubS37_153(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(153, recv) }

//go:noinline
func stubS37_154(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(154, recv) }

//go:noinline
func stubS37_155(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(155, recv) }

//go:noinline
func stubS37_156(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(156, recv) }

//go:noinline
func stubS37_157(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(157, recv) }

//go:noinline
func stubS37_158(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(158, recv) }

//go:noinline
func stubS37_159(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(159, recv) }

//go:noinline
func stubS37_160(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(160, recv) }

//go:noinline
func stubS37_161(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(161, recv) }

//go:noinline
func stubS37_162(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(162, recv) }

//go:noinline
func stubS37_163(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(163, recv) }

//go:noinline
func stubS37_164(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(164, recv) }

//go:noinline
func stubS37_165(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(165, recv) }

//go:noinline
func stubS37_166(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(166, recv) }

//go:noinline
func stubS37_167(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(167, recv) }

//go:noinline
func stubS37_168(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(168, recv) }

//go:noinline
func stubS37_169(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(169, recv) }

//go:noinline
func stubS37_170(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(170, recv) }

//go:noinline
func stubS37_171(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(171, recv) }

//go:noinline
func stubS37_172(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(172, recv) }

//go:noinline
func stubS37_173(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(173, recv) }

//go:noinline
func stubS37_174(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(174, recv) }

//go:noinline
func stubS37_175(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(175, recv) }

//go:noinline
func stubS37_176(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(176, recv) }

//go:noinline
func stubS37_177(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(177, recv) }

//go:noinline
func stubS37_178(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(178, recv) }

//go:noinline
func stubS37_179(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(179, recv) }

//go:noinline
func stubS37_180(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(180, recv) }

//go:noinline
func stubS37_181(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(181, recv) }

//go:noinline
func stubS37_182(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(182, recv) }

//go:noinline
func stubS37_183(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(183, recv) }

//go:noinline
func stubS37_184(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(184, recv) }

//go:noinline
func stubS37_185(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(185, recv) }

//go:noinline
func stubS37_186(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(186, recv) }

//go:noinline
func stubS37_187(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(187, recv) }

//go:noinline
func stubS37_188(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(188, recv) }

//go:noinline
func stubS37_189(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(189, recv) }

//go:noinline
func stubS37_190(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(190, recv) }

//go:noinline
func stubS37_191(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(191, recv) }

//go:noinline
func stubS37_192(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(192, recv) }

//go:noinline
func stubS37_193(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(193, recv) }

//go:noinline
func stubS37_194(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(194, recv) }

//go:noinline
func stubS37_195(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(195, recv) }

//go:noinline
func stubS37_196(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(196, recv) }

//go:noinline
func stubS37_197(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(197, recv) }

//go:noinline
func stubS37_198(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(198, recv) }

//go:noinline
func stubS37_199(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(199, recv) }

//go:noinline
func stubS37_200(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(200, recv) }

//go:noinline
func stubS37_201(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(201, recv) }

//go:noinline
func stubS37_202(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(202, recv) }

//go:noinline
func stubS37_203(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(203, recv) }

//go:noinline
func stubS37_204(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(204, recv) }

//go:noinline
func stubS37_205(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(205, recv) }

//go:noinline
func stubS37_206(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(206, recv) }

//go:noinline
func stubS37_207(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(207, recv) }

//go:noinline
func stubS37_208(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(208, recv) }

//go:noinline
func stubS37_209(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(209, recv) }

//go:noinline
func stubS37_210(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(210, recv) }

//go:noinline
func stubS37_211(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(211, recv) }

//go:noinline
func stubS37_212(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(212, recv) }

//go:noinline
func stubS37_213(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(213, recv) }

//go:noinline
func stubS37_214(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(214, recv) }

//go:noinline
func stubS37_215(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(215, recv) }

//go:noinline
func stubS37_216(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(216, recv) }

//go:noinline
func stubS37_217(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(217, recv) }

//go:noinline
func stubS37_218(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(218, recv) }

//go:noinline
func stubS37_219(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(219, recv) }

//go:noinline
func stubS37_220(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(220, recv) }

//go:noinline
func stubS37_221(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(221, recv) }

//go:noinline
func stubS37_222(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(222, recv) }

//go:noinline
func stubS37_223(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(223, recv) }

//go:noinline
func stubS37_224(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(224, recv) }

//go:noinline
func stubS37_225(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(225, recv) }

//go:noinline
func stubS37_226(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(226, recv) }

//go:noinline
func stubS37_227(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(227, recv) }

//go:noinline
func stubS37_228(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(228, recv) }

//go:noinline
func stubS37_229(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(229, recv) }

//go:noinline
func stubS37_230(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(230, recv) }

//go:noinline
func stubS37_231(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(231, recv) }

//go:noinline
func stubS37_232(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(232, recv) }

//go:noinline
func stubS37_233(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(233, recv) }

//go:noinline
func stubS37_234(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(234, recv) }

//go:noinline
func stubS37_235(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(235, recv) }

//go:noinline
func stubS37_236(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(236, recv) }

//go:noinline
func stubS37_237(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(237, recv) }

//go:noinline
func stubS37_238(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(238, recv) }

//go:noinline
func stubS37_239(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(239, recv) }

//go:noinline
func stubS37_240(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(240, recv) }

//go:noinline
func stubS37_241(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(241, recv) }

//go:noinline
func stubS37_242(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(242, recv) }

//go:noinline
func stubS37_243(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(243, recv) }

//go:noinline
func stubS37_244(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(244, recv) }

//go:noinline
func stubS37_245(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(245, recv) }

//go:noinline
func stubS37_246(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(246, recv) }

//go:noinline
func stubS37_247(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(247, recv) }

//go:noinline
func stubS37_248(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(248, recv) }

//go:noinline
func stubS37_249(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(249, recv) }

//go:noinline
func stubS37_250(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(250, recv) }

//go:noinline
func stubS37_251(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(251, recv) }

//go:noinline
func stubS37_252(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(252, recv) }

//go:noinline
func stubS37_253(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(253, recv) }

//go:noinline
func stubS37_254(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(254, recv) }

//go:noinline
func stubS37_255(recv unsafe.Pointer) (rune, int, error) { return dispatchS37(255, recv) }

var stubsS37 = [poolSizeS37]uintptr{
	runtype.FuncPC(stubS37_0),
	runtype.FuncPC(stubS37_1),
	runtype.FuncPC(stubS37_2),
	runtype.FuncPC(stubS37_3),
	runtype.FuncPC(stubS37_4),
	runtype.FuncPC(stubS37_5),
	runtype.FuncPC(stubS37_6),
	runtype.FuncPC(stubS37_7),
	runtype.FuncPC(stubS37_8),
	runtype.FuncPC(stubS37_9),
	runtype.FuncPC(stubS37_10),
	runtype.FuncPC(stubS37_11),
	runtype.FuncPC(stubS37_12),
	runtype.FuncPC(stubS37_13),
	runtype.FuncPC(stubS37_14),
	runtype.FuncPC(stubS37_15),
	runtype.FuncPC(stubS37_16),
	runtype.FuncPC(stubS37_17),
	runtype.FuncPC(stubS37_18),
	runtype.FuncPC(stubS37_19),
	runtype.FuncPC(stubS37_20),
	runtype.FuncPC(stubS37_21),
	runtype.FuncPC(stubS37_22),
	runtype.FuncPC(stubS37_23),
	runtype.FuncPC(stubS37_24),
	runtype.FuncPC(stubS37_25),
	runtype.FuncPC(stubS37_26),
	runtype.FuncPC(stubS37_27),
	runtype.FuncPC(stubS37_28),
	runtype.FuncPC(stubS37_29),
	runtype.FuncPC(stubS37_30),
	runtype.FuncPC(stubS37_31),
	runtype.FuncPC(stubS37_32),
	runtype.FuncPC(stubS37_33),
	runtype.FuncPC(stubS37_34),
	runtype.FuncPC(stubS37_35),
	runtype.FuncPC(stubS37_36),
	runtype.FuncPC(stubS37_37),
	runtype.FuncPC(stubS37_38),
	runtype.FuncPC(stubS37_39),
	runtype.FuncPC(stubS37_40),
	runtype.FuncPC(stubS37_41),
	runtype.FuncPC(stubS37_42),
	runtype.FuncPC(stubS37_43),
	runtype.FuncPC(stubS37_44),
	runtype.FuncPC(stubS37_45),
	runtype.FuncPC(stubS37_46),
	runtype.FuncPC(stubS37_47),
	runtype.FuncPC(stubS37_48),
	runtype.FuncPC(stubS37_49),
	runtype.FuncPC(stubS37_50),
	runtype.FuncPC(stubS37_51),
	runtype.FuncPC(stubS37_52),
	runtype.FuncPC(stubS37_53),
	runtype.FuncPC(stubS37_54),
	runtype.FuncPC(stubS37_55),
	runtype.FuncPC(stubS37_56),
	runtype.FuncPC(stubS37_57),
	runtype.FuncPC(stubS37_58),
	runtype.FuncPC(stubS37_59),
	runtype.FuncPC(stubS37_60),
	runtype.FuncPC(stubS37_61),
	runtype.FuncPC(stubS37_62),
	runtype.FuncPC(stubS37_63),
	runtype.FuncPC(stubS37_64),
	runtype.FuncPC(stubS37_65),
	runtype.FuncPC(stubS37_66),
	runtype.FuncPC(stubS37_67),
	runtype.FuncPC(stubS37_68),
	runtype.FuncPC(stubS37_69),
	runtype.FuncPC(stubS37_70),
	runtype.FuncPC(stubS37_71),
	runtype.FuncPC(stubS37_72),
	runtype.FuncPC(stubS37_73),
	runtype.FuncPC(stubS37_74),
	runtype.FuncPC(stubS37_75),
	runtype.FuncPC(stubS37_76),
	runtype.FuncPC(stubS37_77),
	runtype.FuncPC(stubS37_78),
	runtype.FuncPC(stubS37_79),
	runtype.FuncPC(stubS37_80),
	runtype.FuncPC(stubS37_81),
	runtype.FuncPC(stubS37_82),
	runtype.FuncPC(stubS37_83),
	runtype.FuncPC(stubS37_84),
	runtype.FuncPC(stubS37_85),
	runtype.FuncPC(stubS37_86),
	runtype.FuncPC(stubS37_87),
	runtype.FuncPC(stubS37_88),
	runtype.FuncPC(stubS37_89),
	runtype.FuncPC(stubS37_90),
	runtype.FuncPC(stubS37_91),
	runtype.FuncPC(stubS37_92),
	runtype.FuncPC(stubS37_93),
	runtype.FuncPC(stubS37_94),
	runtype.FuncPC(stubS37_95),
	runtype.FuncPC(stubS37_96),
	runtype.FuncPC(stubS37_97),
	runtype.FuncPC(stubS37_98),
	runtype.FuncPC(stubS37_99),
	runtype.FuncPC(stubS37_100),
	runtype.FuncPC(stubS37_101),
	runtype.FuncPC(stubS37_102),
	runtype.FuncPC(stubS37_103),
	runtype.FuncPC(stubS37_104),
	runtype.FuncPC(stubS37_105),
	runtype.FuncPC(stubS37_106),
	runtype.FuncPC(stubS37_107),
	runtype.FuncPC(stubS37_108),
	runtype.FuncPC(stubS37_109),
	runtype.FuncPC(stubS37_110),
	runtype.FuncPC(stubS37_111),
	runtype.FuncPC(stubS37_112),
	runtype.FuncPC(stubS37_113),
	runtype.FuncPC(stubS37_114),
	runtype.FuncPC(stubS37_115),
	runtype.FuncPC(stubS37_116),
	runtype.FuncPC(stubS37_117),
	runtype.FuncPC(stubS37_118),
	runtype.FuncPC(stubS37_119),
	runtype.FuncPC(stubS37_120),
	runtype.FuncPC(stubS37_121),
	runtype.FuncPC(stubS37_122),
	runtype.FuncPC(stubS37_123),
	runtype.FuncPC(stubS37_124),
	runtype.FuncPC(stubS37_125),
	runtype.FuncPC(stubS37_126),
	runtype.FuncPC(stubS37_127),
	runtype.FuncPC(stubS37_128),
	runtype.FuncPC(stubS37_129),
	runtype.FuncPC(stubS37_130),
	runtype.FuncPC(stubS37_131),
	runtype.FuncPC(stubS37_132),
	runtype.FuncPC(stubS37_133),
	runtype.FuncPC(stubS37_134),
	runtype.FuncPC(stubS37_135),
	runtype.FuncPC(stubS37_136),
	runtype.FuncPC(stubS37_137),
	runtype.FuncPC(stubS37_138),
	runtype.FuncPC(stubS37_139),
	runtype.FuncPC(stubS37_140),
	runtype.FuncPC(stubS37_141),
	runtype.FuncPC(stubS37_142),
	runtype.FuncPC(stubS37_143),
	runtype.FuncPC(stubS37_144),
	runtype.FuncPC(stubS37_145),
	runtype.FuncPC(stubS37_146),
	runtype.FuncPC(stubS37_147),
	runtype.FuncPC(stubS37_148),
	runtype.FuncPC(stubS37_149),
	runtype.FuncPC(stubS37_150),
	runtype.FuncPC(stubS37_151),
	runtype.FuncPC(stubS37_152),
	runtype.FuncPC(stubS37_153),
	runtype.FuncPC(stubS37_154),
	runtype.FuncPC(stubS37_155),
	runtype.FuncPC(stubS37_156),
	runtype.FuncPC(stubS37_157),
	runtype.FuncPC(stubS37_158),
	runtype.FuncPC(stubS37_159),
	runtype.FuncPC(stubS37_160),
	runtype.FuncPC(stubS37_161),
	runtype.FuncPC(stubS37_162),
	runtype.FuncPC(stubS37_163),
	runtype.FuncPC(stubS37_164),
	runtype.FuncPC(stubS37_165),
	runtype.FuncPC(stubS37_166),
	runtype.FuncPC(stubS37_167),
	runtype.FuncPC(stubS37_168),
	runtype.FuncPC(stubS37_169),
	runtype.FuncPC(stubS37_170),
	runtype.FuncPC(stubS37_171),
	runtype.FuncPC(stubS37_172),
	runtype.FuncPC(stubS37_173),
	runtype.FuncPC(stubS37_174),
	runtype.FuncPC(stubS37_175),
	runtype.FuncPC(stubS37_176),
	runtype.FuncPC(stubS37_177),
	runtype.FuncPC(stubS37_178),
	runtype.FuncPC(stubS37_179),
	runtype.FuncPC(stubS37_180),
	runtype.FuncPC(stubS37_181),
	runtype.FuncPC(stubS37_182),
	runtype.FuncPC(stubS37_183),
	runtype.FuncPC(stubS37_184),
	runtype.FuncPC(stubS37_185),
	runtype.FuncPC(stubS37_186),
	runtype.FuncPC(stubS37_187),
	runtype.FuncPC(stubS37_188),
	runtype.FuncPC(stubS37_189),
	runtype.FuncPC(stubS37_190),
	runtype.FuncPC(stubS37_191),
	runtype.FuncPC(stubS37_192),
	runtype.FuncPC(stubS37_193),
	runtype.FuncPC(stubS37_194),
	runtype.FuncPC(stubS37_195),
	runtype.FuncPC(stubS37_196),
	runtype.FuncPC(stubS37_197),
	runtype.FuncPC(stubS37_198),
	runtype.FuncPC(stubS37_199),
	runtype.FuncPC(stubS37_200),
	runtype.FuncPC(stubS37_201),
	runtype.FuncPC(stubS37_202),
	runtype.FuncPC(stubS37_203),
	runtype.FuncPC(stubS37_204),
	runtype.FuncPC(stubS37_205),
	runtype.FuncPC(stubS37_206),
	runtype.FuncPC(stubS37_207),
	runtype.FuncPC(stubS37_208),
	runtype.FuncPC(stubS37_209),
	runtype.FuncPC(stubS37_210),
	runtype.FuncPC(stubS37_211),
	runtype.FuncPC(stubS37_212),
	runtype.FuncPC(stubS37_213),
	runtype.FuncPC(stubS37_214),
	runtype.FuncPC(stubS37_215),
	runtype.FuncPC(stubS37_216),
	runtype.FuncPC(stubS37_217),
	runtype.FuncPC(stubS37_218),
	runtype.FuncPC(stubS37_219),
	runtype.FuncPC(stubS37_220),
	runtype.FuncPC(stubS37_221),
	runtype.FuncPC(stubS37_222),
	runtype.FuncPC(stubS37_223),
	runtype.FuncPC(stubS37_224),
	runtype.FuncPC(stubS37_225),
	runtype.FuncPC(stubS37_226),
	runtype.FuncPC(stubS37_227),
	runtype.FuncPC(stubS37_228),
	runtype.FuncPC(stubS37_229),
	runtype.FuncPC(stubS37_230),
	runtype.FuncPC(stubS37_231),
	runtype.FuncPC(stubS37_232),
	runtype.FuncPC(stubS37_233),
	runtype.FuncPC(stubS37_234),
	runtype.FuncPC(stubS37_235),
	runtype.FuncPC(stubS37_236),
	runtype.FuncPC(stubS37_237),
	runtype.FuncPC(stubS37_238),
	runtype.FuncPC(stubS37_239),
	runtype.FuncPC(stubS37_240),
	runtype.FuncPC(stubS37_241),
	runtype.FuncPC(stubS37_242),
	runtype.FuncPC(stubS37_243),
	runtype.FuncPC(stubS37_244),
	runtype.FuncPC(stubS37_245),
	runtype.FuncPC(stubS37_246),
	runtype.FuncPC(stubS37_247),
	runtype.FuncPC(stubS37_248),
	runtype.FuncPC(stubS37_249),
	runtype.FuncPC(stubS37_250),
	runtype.FuncPC(stubS37_251),
	runtype.FuncPC(stubS37_252),
	runtype.FuncPC(stubS37_253),
	runtype.FuncPC(stubS37_254),
	runtype.FuncPC(stubS37_255),
}
