// Code generated by gen_pools.go; DO NOT EDIT.
// Shape S35 pool: 256 slots.

package stubs

import (
	"log/slog"
	"unsafe"

	"github.com/mvm-sh/mvm/runtype"
)

const poolSizeS35 = 256

//go:noinline
func stubS35_0(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(0, recv, name) }

//go:noinline
func stubS35_1(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(1, recv, name) }

//go:noinline
func stubS35_2(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(2, recv, name) }

//go:noinline
func stubS35_3(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(3, recv, name) }

//go:noinline
func stubS35_4(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(4, recv, name) }

//go:noinline
func stubS35_5(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(5, recv, name) }

//go:noinline
func stubS35_6(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(6, recv, name) }

//go:noinline
func stubS35_7(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(7, recv, name) }

//go:noinline
func stubS35_8(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(8, recv, name) }

//go:noinline
func stubS35_9(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(9, recv, name) }

//go:noinline
func stubS35_10(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(10, recv, name) }

//go:noinline
func stubS35_11(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(11, recv, name) }

//go:noinline
func stubS35_12(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(12, recv, name) }

//go:noinline
func stubS35_13(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(13, recv, name) }

//go:noinline
func stubS35_14(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(14, recv, name) }

//go:noinline
func stubS35_15(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(15, recv, name) }

//go:noinline
func stubS35_16(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(16, recv, name) }

//go:noinline
func stubS35_17(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(17, recv, name) }

//go:noinline
func stubS35_18(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(18, recv, name) }

//go:noinline
func stubS35_19(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(19, recv, name) }

//go:noinline
func stubS35_20(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(20, recv, name) }

//go:noinline
func stubS35_21(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(21, recv, name) }

//go:noinline
func stubS35_22(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(22, recv, name) }

//go:noinline
func stubS35_23(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(23, recv, name) }

//go:noinline
func stubS35_24(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(24, recv, name) }

//go:noinline
func stubS35_25(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(25, recv, name) }

//go:noinline
func stubS35_26(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(26, recv, name) }

//go:noinline
func stubS35_27(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(27, recv, name) }

//go:noinline
func stubS35_28(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(28, recv, name) }

//go:noinline
func stubS35_29(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(29, recv, name) }

//go:noinline
func stubS35_30(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(30, recv, name) }

//go:noinline
func stubS35_31(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(31, recv, name) }

//go:noinline
func stubS35_32(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(32, recv, name) }

//go:noinline
func stubS35_33(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(33, recv, name) }

//go:noinline
func stubS35_34(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(34, recv, name) }

//go:noinline
func stubS35_35(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(35, recv, name) }

//go:noinline
func stubS35_36(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(36, recv, name) }

//go:noinline
func stubS35_37(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(37, recv, name) }

//go:noinline
func stubS35_38(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(38, recv, name) }

//go:noinline
func stubS35_39(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(39, recv, name) }

//go:noinline
func stubS35_40(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(40, recv, name) }

//go:noinline
func stubS35_41(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(41, recv, name) }

//go:noinline
func stubS35_42(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(42, recv, name) }

//go:noinline
func stubS35_43(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(43, recv, name) }

//go:noinline
func stubS35_44(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(44, recv, name) }

//go:noinline
func stubS35_45(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(45, recv, name) }

//go:noinline
func stubS35_46(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(46, recv, name) }

//go:noinline
func stubS35_47(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(47, recv, name) }

//go:noinline
func stubS35_48(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(48, recv, name) }

//go:noinline
func stubS35_49(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(49, recv, name) }

//go:noinline
func stubS35_50(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(50, recv, name) }

//go:noinline
func stubS35_51(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(51, recv, name) }

//go:noinline
func stubS35_52(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(52, recv, name) }

//go:noinline
func stubS35_53(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(53, recv, name) }

//go:noinline
func stubS35_54(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(54, recv, name) }

//go:noinline
func stubS35_55(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(55, recv, name) }

//go:noinline
func stubS35_56(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(56, recv, name) }

//go:noinline
func stubS35_57(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(57, recv, name) }

//go:noinline
func stubS35_58(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(58, recv, name) }

//go:noinline
func stubS35_59(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(59, recv, name) }

//go:noinline
func stubS35_60(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(60, recv, name) }

//go:noinline
func stubS35_61(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(61, recv, name) }

//go:noinline
func stubS35_62(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(62, recv, name) }

//go:noinline
func stubS35_63(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(63, recv, name) }

//go:noinline
func stubS35_64(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(64, recv, name) }

//go:noinline
func stubS35_65(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(65, recv, name) }

//go:noinline
func stubS35_66(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(66, recv, name) }

//go:noinline
func stubS35_67(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(67, recv, name) }

//go:noinline
func stubS35_68(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(68, recv, name) }

//go:noinline
func stubS35_69(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(69, recv, name) }

//go:noinline
func stubS35_70(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(70, recv, name) }

//go:noinline
func stubS35_71(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(71, recv, name) }

//go:noinline
func stubS35_72(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(72, recv, name) }

//go:noinline
func stubS35_73(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(73, recv, name) }

//go:noinline
func stubS35_74(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(74, recv, name) }

//go:noinline
func stubS35_75(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(75, recv, name) }

//go:noinline
func stubS35_76(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(76, recv, name) }

//go:noinline
func stubS35_77(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(77, recv, name) }

//go:noinline
func stubS35_78(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(78, recv, name) }

//go:noinline
func stubS35_79(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(79, recv, name) }

//go:noinline
func stubS35_80(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(80, recv, name) }

//go:noinline
func stubS35_81(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(81, recv, name) }

//go:noinline
func stubS35_82(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(82, recv, name) }

//go:noinline
func stubS35_83(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(83, recv, name) }

//go:noinline
func stubS35_84(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(84, recv, name) }

//go:noinline
func stubS35_85(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(85, recv, name) }

//go:noinline
func stubS35_86(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(86, recv, name) }

//go:noinline
func stubS35_87(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(87, recv, name) }

//go:noinline
func stubS35_88(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(88, recv, name) }

//go:noinline
func stubS35_89(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(89, recv, name) }

//go:noinline
func stubS35_90(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(90, recv, name) }

//go:noinline
func stubS35_91(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(91, recv, name) }

//go:noinline
func stubS35_92(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(92, recv, name) }

//go:noinline
func stubS35_93(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(93, recv, name) }

//go:noinline
func stubS35_94(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(94, recv, name) }

//go:noinline
func stubS35_95(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(95, recv, name) }

//go:noinline
func stubS35_96(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(96, recv, name) }

//go:noinline
func stubS35_97(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(97, recv, name) }

//go:noinline
func stubS35_98(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(98, recv, name) }

//go:noinline
func stubS35_99(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(99, recv, name) }

//go:noinline
func stubS35_100(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(100, recv, name) }

//go:noinline
func stubS35_101(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(101, recv, name) }

//go:noinline
func stubS35_102(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(102, recv, name) }

//go:noinline
func stubS35_103(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(103, recv, name) }

//go:noinline
func stubS35_104(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(104, recv, name) }

//go:noinline
func stubS35_105(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(105, recv, name) }

//go:noinline
func stubS35_106(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(106, recv, name) }

//go:noinline
func stubS35_107(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(107, recv, name) }

//go:noinline
func stubS35_108(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(108, recv, name) }

//go:noinline
func stubS35_109(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(109, recv, name) }

//go:noinline
func stubS35_110(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(110, recv, name) }

//go:noinline
func stubS35_111(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(111, recv, name) }

//go:noinline
func stubS35_112(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(112, recv, name) }

//go:noinline
func stubS35_113(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(113, recv, name) }

//go:noinline
func stubS35_114(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(114, recv, name) }

//go:noinline
func stubS35_115(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(115, recv, name) }

//go:noinline
func stubS35_116(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(116, recv, name) }

//go:noinline
func stubS35_117(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(117, recv, name) }

//go:noinline
func stubS35_118(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(118, recv, name) }

//go:noinline
func stubS35_119(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(119, recv, name) }

//go:noinline
func stubS35_120(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(120, recv, name) }

//go:noinline
func stubS35_121(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(121, recv, name) }

//go:noinline
func stubS35_122(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(122, recv, name) }

//go:noinline
func stubS35_123(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(123, recv, name) }

//go:noinline
func stubS35_124(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(124, recv, name) }

//go:noinline
func stubS35_125(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(125, recv, name) }

//go:noinline
func stubS35_126(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(126, recv, name) }

//go:noinline
func stubS35_127(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(127, recv, name) }

//go:noinline
func stubS35_128(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(128, recv, name) }

//go:noinline
func stubS35_129(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(129, recv, name) }

//go:noinline
func stubS35_130(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(130, recv, name) }

//go:noinline
func stubS35_131(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(131, recv, name) }

//go:noinline
func stubS35_132(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(132, recv, name) }

//go:noinline
func stubS35_133(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(133, recv, name) }

//go:noinline
func stubS35_134(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(134, recv, name) }

//go:noinline
func stubS35_135(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(135, recv, name) }

//go:noinline
func stubS35_136(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(136, recv, name) }

//go:noinline
func stubS35_137(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(137, recv, name) }

//go:noinline
func stubS35_138(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(138, recv, name) }

//go:noinline
func stubS35_139(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(139, recv, name) }

//go:noinline
func stubS35_140(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(140, recv, name) }

//go:noinline
func stubS35_141(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(141, recv, name) }

//go:noinline
func stubS35_142(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(142, recv, name) }

//go:noinline
func stubS35_143(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(143, recv, name) }

//go:noinline
func stubS35_144(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(144, recv, name) }

//go:noinline
func stubS35_145(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(145, recv, name) }

//go:noinline
func stubS35_146(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(146, recv, name) }

//go:noinline
func stubS35_147(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(147, recv, name) }

//go:noinline
func stubS35_148(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(148, recv, name) }

//go:noinline
func stubS35_149(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(149, recv, name) }

//go:noinline
func stubS35_150(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(150, recv, name) }

//go:noinline
func stubS35_151(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(151, recv, name) }

//go:noinline
func stubS35_152(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(152, recv, name) }

//go:noinline
func stubS35_153(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(153, recv, name) }

//go:noinline
func stubS35_154(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(154, recv, name) }

//go:noinline
func stubS35_155(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(155, recv, name) }

//go:noinline
func stubS35_156(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(156, recv, name) }

//go:noinline
func stubS35_157(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(157, recv, name) }

//go:noinline
func stubS35_158(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(158, recv, name) }

//go:noinline
func stubS35_159(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(159, recv, name) }

//go:noinline
func stubS35_160(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(160, recv, name) }

//go:noinline
func stubS35_161(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(161, recv, name) }

//go:noinline
func stubS35_162(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(162, recv, name) }

//go:noinline
func stubS35_163(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(163, recv, name) }

//go:noinline
func stubS35_164(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(164, recv, name) }

//go:noinline
func stubS35_165(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(165, recv, name) }

//go:noinline
func stubS35_166(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(166, recv, name) }

//go:noinline
func stubS35_167(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(167, recv, name) }

//go:noinline
func stubS35_168(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(168, recv, name) }

//go:noinline
func stubS35_169(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(169, recv, name) }

//go:noinline
func stubS35_170(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(170, recv, name) }

//go:noinline
func stubS35_171(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(171, recv, name) }

//go:noinline
func stubS35_172(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(172, recv, name) }

//go:noinline
func stubS35_173(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(173, recv, name) }

//go:noinline
func stubS35_174(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(174, recv, name) }

//go:noinline
func stubS35_175(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(175, recv, name) }

//go:noinline
func stubS35_176(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(176, recv, name) }

//go:noinline
func stubS35_177(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(177, recv, name) }

//go:noinline
func stubS35_178(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(178, recv, name) }

//go:noinline
func stubS35_179(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(179, recv, name) }

//go:noinline
func stubS35_180(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(180, recv, name) }

//go:noinline
func stubS35_181(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(181, recv, name) }

//go:noinline
func stubS35_182(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(182, recv, name) }

//go:noinline
func stubS35_183(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(183, recv, name) }

//go:noinline
func stubS35_184(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(184, recv, name) }

//go:noinline
func stubS35_185(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(185, recv, name) }

//go:noinline
func stubS35_186(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(186, recv, name) }

//go:noinline
func stubS35_187(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(187, recv, name) }

//go:noinline
func stubS35_188(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(188, recv, name) }

//go:noinline
func stubS35_189(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(189, recv, name) }

//go:noinline
func stubS35_190(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(190, recv, name) }

//go:noinline
func stubS35_191(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(191, recv, name) }

//go:noinline
func stubS35_192(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(192, recv, name) }

//go:noinline
func stubS35_193(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(193, recv, name) }

//go:noinline
func stubS35_194(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(194, recv, name) }

//go:noinline
func stubS35_195(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(195, recv, name) }

//go:noinline
func stubS35_196(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(196, recv, name) }

//go:noinline
func stubS35_197(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(197, recv, name) }

//go:noinline
func stubS35_198(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(198, recv, name) }

//go:noinline
func stubS35_199(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(199, recv, name) }

//go:noinline
func stubS35_200(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(200, recv, name) }

//go:noinline
func stubS35_201(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(201, recv, name) }

//go:noinline
func stubS35_202(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(202, recv, name) }

//go:noinline
func stubS35_203(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(203, recv, name) }

//go:noinline
func stubS35_204(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(204, recv, name) }

//go:noinline
func stubS35_205(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(205, recv, name) }

//go:noinline
func stubS35_206(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(206, recv, name) }

//go:noinline
func stubS35_207(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(207, recv, name) }

//go:noinline
func stubS35_208(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(208, recv, name) }

//go:noinline
func stubS35_209(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(209, recv, name) }

//go:noinline
func stubS35_210(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(210, recv, name) }

//go:noinline
func stubS35_211(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(211, recv, name) }

//go:noinline
func stubS35_212(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(212, recv, name) }

//go:noinline
func stubS35_213(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(213, recv, name) }

//go:noinline
func stubS35_214(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(214, recv, name) }

//go:noinline
func stubS35_215(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(215, recv, name) }

//go:noinline
func stubS35_216(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(216, recv, name) }

//go:noinline
func stubS35_217(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(217, recv, name) }

//go:noinline
func stubS35_218(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(218, recv, name) }

//go:noinline
func stubS35_219(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(219, recv, name) }

//go:noinline
func stubS35_220(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(220, recv, name) }

//go:noinline
func stubS35_221(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(221, recv, name) }

//go:noinline
func stubS35_222(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(222, recv, name) }

//go:noinline
func stubS35_223(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(223, recv, name) }

//go:noinline
func stubS35_224(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(224, recv, name) }

//go:noinline
func stubS35_225(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(225, recv, name) }

//go:noinline
func stubS35_226(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(226, recv, name) }

//go:noinline
func stubS35_227(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(227, recv, name) }

//go:noinline
func stubS35_228(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(228, recv, name) }

//go:noinline
func stubS35_229(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(229, recv, name) }

//go:noinline
func stubS35_230(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(230, recv, name) }

//go:noinline
func stubS35_231(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(231, recv, name) }

//go:noinline
func stubS35_232(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(232, recv, name) }

//go:noinline
func stubS35_233(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(233, recv, name) }

//go:noinline
func stubS35_234(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(234, recv, name) }

//go:noinline
func stubS35_235(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(235, recv, name) }

//go:noinline
func stubS35_236(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(236, recv, name) }

//go:noinline
func stubS35_237(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(237, recv, name) }

//go:noinline
func stubS35_238(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(238, recv, name) }

//go:noinline
func stubS35_239(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(239, recv, name) }

//go:noinline
func stubS35_240(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(240, recv, name) }

//go:noinline
func stubS35_241(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(241, recv, name) }

//go:noinline
func stubS35_242(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(242, recv, name) }

//go:noinline
func stubS35_243(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(243, recv, name) }

//go:noinline
func stubS35_244(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(244, recv, name) }

//go:noinline
func stubS35_245(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(245, recv, name) }

//go:noinline
func stubS35_246(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(246, recv, name) }

//go:noinline
func stubS35_247(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(247, recv, name) }

//go:noinline
func stubS35_248(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(248, recv, name) }

//go:noinline
func stubS35_249(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(249, recv, name) }

//go:noinline
func stubS35_250(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(250, recv, name) }

//go:noinline
func stubS35_251(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(251, recv, name) }

//go:noinline
func stubS35_252(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(252, recv, name) }

//go:noinline
func stubS35_253(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(253, recv, name) }

//go:noinline
func stubS35_254(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(254, recv, name) }

//go:noinline
func stubS35_255(recv unsafe.Pointer, name string) slog.Handler { return dispatchS35(255, recv, name) }

var stubsS35 = [poolSizeS35]uintptr{
	runtype.FuncPC(stubS35_0),
	runtype.FuncPC(stubS35_1),
	runtype.FuncPC(stubS35_2),
	runtype.FuncPC(stubS35_3),
	runtype.FuncPC(stubS35_4),
	runtype.FuncPC(stubS35_5),
	runtype.FuncPC(stubS35_6),
	runtype.FuncPC(stubS35_7),
	runtype.FuncPC(stubS35_8),
	runtype.FuncPC(stubS35_9),
	runtype.FuncPC(stubS35_10),
	runtype.FuncPC(stubS35_11),
	runtype.FuncPC(stubS35_12),
	runtype.FuncPC(stubS35_13),
	runtype.FuncPC(stubS35_14),
	runtype.FuncPC(stubS35_15),
	runtype.FuncPC(stubS35_16),
	runtype.FuncPC(stubS35_17),
	runtype.FuncPC(stubS35_18),
	runtype.FuncPC(stubS35_19),
	runtype.FuncPC(stubS35_20),
	runtype.FuncPC(stubS35_21),
	runtype.FuncPC(stubS35_22),
	runtype.FuncPC(stubS35_23),
	runtype.FuncPC(stubS35_24),
	runtype.FuncPC(stubS35_25),
	runtype.FuncPC(stubS35_26),
	runtype.FuncPC(stubS35_27),
	runtype.FuncPC(stubS35_28),
	runtype.FuncPC(stubS35_29),
	runtype.FuncPC(stubS35_30),
	runtype.FuncPC(stubS35_31),
	runtype.FuncPC(stubS35_32),
	runtype.FuncPC(stubS35_33),
	runtype.FuncPC(stubS35_34),
	runtype.FuncPC(stubS35_35),
	runtype.FuncPC(stubS35_36),
	runtype.FuncPC(stubS35_37),
	runtype.FuncPC(stubS35_38),
	runtype.FuncPC(stubS35_39),
	runtype.FuncPC(stubS35_40),
	runtype.FuncPC(stubS35_41),
	runtype.FuncPC(stubS35_42),
	runtype.FuncPC(stubS35_43),
	runtype.FuncPC(stubS35_44),
	runtype.FuncPC(stubS35_45),
	runtype.FuncPC(stubS35_46),
	runtype.FuncPC(stubS35_47),
	runtype.FuncPC(stubS35_48),
	runtype.FuncPC(stubS35_49),
	runtype.FuncPC(stubS35_50),
	runtype.FuncPC(stubS35_51),
	runtype.FuncPC(stubS35_52),
	runtype.FuncPC(stubS35_53),
	runtype.FuncPC(stubS35_54),
	runtype.FuncPC(stubS35_55),
	runtype.FuncPC(stubS35_56),
	runtype.FuncPC(stubS35_57),
	runtype.FuncPC(stubS35_58),
	runtype.FuncPC(stubS35_59),
	runtype.FuncPC(stubS35_60),
	runtype.FuncPC(stubS35_61),
	runtype.FuncPC(stubS35_62),
	runtype.FuncPC(stubS35_63),
	runtype.FuncPC(stubS35_64),
	runtype.FuncPC(stubS35_65),
	runtype.FuncPC(stubS35_66),
	runtype.FuncPC(stubS35_67),
	runtype.FuncPC(stubS35_68),
	runtype.FuncPC(stubS35_69),
	runtype.FuncPC(stubS35_70),
	runtype.FuncPC(stubS35_71),
	runtype.FuncPC(stubS35_72),
	runtype.FuncPC(stubS35_73),
	runtype.FuncPC(stubS35_74),
	runtype.FuncPC(stubS35_75),
	runtype.FuncPC(stubS35_76),
	runtype.FuncPC(stubS35_77),
	runtype.FuncPC(stubS35_78),
	runtype.FuncPC(stubS35_79),
	runtype.FuncPC(stubS35_80),
	runtype.FuncPC(stubS35_81),
	runtype.FuncPC(stubS35_82),
	runtype.FuncPC(stubS35_83),
	runtype.FuncPC(stubS35_84),
	runtype.FuncPC(stubS35_85),
	runtype.FuncPC(stubS35_86),
	runtype.FuncPC(stubS35_87),
	runtype.FuncPC(stubS35_88),
	runtype.FuncPC(stubS35_89),
	runtype.FuncPC(stubS35_90),
	runtype.FuncPC(stubS35_91),
	runtype.FuncPC(stubS35_92),
	runtype.FuncPC(stubS35_93),
	runtype.FuncPC(stubS35_94),
	runtype.FuncPC(stubS35_95),
	runtype.FuncPC(stubS35_96),
	runtype.FuncPC(stubS35_97),
	runtype.FuncPC(stubS35_98),
	runtype.FuncPC(stubS35_99),
	runtype.FuncPC(stubS35_100),
	runtype.FuncPC(stubS35_101),
	runtype.FuncPC(stubS35_102),
	runtype.FuncPC(stubS35_103),
	runtype.FuncPC(stubS35_104),
	runtype.FuncPC(stubS35_105),
	runtype.FuncPC(stubS35_106),
	runtype.FuncPC(stubS35_107),
	runtype.FuncPC(stubS35_108),
	runtype.FuncPC(stubS35_109),
	runtype.FuncPC(stubS35_110),
	runtype.FuncPC(stubS35_111),
	runtype.FuncPC(stubS35_112),
	runtype.FuncPC(stubS35_113),
	runtype.FuncPC(stubS35_114),
	runtype.FuncPC(stubS35_115),
	runtype.FuncPC(stubS35_116),
	runtype.FuncPC(stubS35_117),
	runtype.FuncPC(stubS35_118),
	runtype.FuncPC(stubS35_119),
	runtype.FuncPC(stubS35_120),
	runtype.FuncPC(stubS35_121),
	runtype.FuncPC(stubS35_122),
	runtype.FuncPC(stubS35_123),
	runtype.FuncPC(stubS35_124),
	runtype.FuncPC(stubS35_125),
	runtype.FuncPC(stubS35_126),
	runtype.FuncPC(stubS35_127),
	runtype.FuncPC(stubS35_128),
	runtype.FuncPC(stubS35_129),
	runtype.FuncPC(stubS35_130),
	runtype.FuncPC(stubS35_131),
	runtype.FuncPC(stubS35_132),
	runtype.FuncPC(stubS35_133),
	runtype.FuncPC(stubS35_134),
	runtype.FuncPC(stubS35_135),
	runtype.FuncPC(stubS35_136),
	runtype.FuncPC(stubS35_137),
	runtype.FuncPC(stubS35_138),
	runtype.FuncPC(stubS35_139),
	runtype.FuncPC(stubS35_140),
	runtype.FuncPC(stubS35_141),
	runtype.FuncPC(stubS35_142),
	runtype.FuncPC(stubS35_143),
	runtype.FuncPC(stubS35_144),
	runtype.FuncPC(stubS35_145),
	runtype.FuncPC(stubS35_146),
	runtype.FuncPC(stubS35_147),
	runtype.FuncPC(stubS35_148),
	runtype.FuncPC(stubS35_149),
	runtype.FuncPC(stubS35_150),
	runtype.FuncPC(stubS35_151),
	runtype.FuncPC(stubS35_152),
	runtype.FuncPC(stubS35_153),
	runtype.FuncPC(stubS35_154),
	runtype.FuncPC(stubS35_155),
	runtype.FuncPC(stubS35_156),
	runtype.FuncPC(stubS35_157),
	runtype.FuncPC(stubS35_158),
	runtype.FuncPC(stubS35_159),
	runtype.FuncPC(stubS35_160),
	runtype.FuncPC(stubS35_161),
	runtype.FuncPC(stubS35_162),
	runtype.FuncPC(stubS35_163),
	runtype.FuncPC(stubS35_164),
	runtype.FuncPC(stubS35_165),
	runtype.FuncPC(stubS35_166),
	runtype.FuncPC(stubS35_167),
	runtype.FuncPC(stubS35_168),
	runtype.FuncPC(stubS35_169),
	runtype.FuncPC(stubS35_170),
	runtype.FuncPC(stubS35_171),
	runtype.FuncPC(stubS35_172),
	runtype.FuncPC(stubS35_173),
	runtype.FuncPC(stubS35_174),
	runtype.FuncPC(stubS35_175),
	runtype.FuncPC(stubS35_176),
	runtype.FuncPC(stubS35_177),
	runtype.FuncPC(stubS35_178),
	runtype.FuncPC(stubS35_179),
	runtype.FuncPC(stubS35_180),
	runtype.FuncPC(stubS35_181),
	runtype.FuncPC(stubS35_182),
	runtype.FuncPC(stubS35_183),
	runtype.FuncPC(stubS35_184),
	runtype.FuncPC(stubS35_185),
	runtype.FuncPC(stubS35_186),
	runtype.FuncPC(stubS35_187),
	runtype.FuncPC(stubS35_188),
	runtype.FuncPC(stubS35_189),
	runtype.FuncPC(stubS35_190),
	runtype.FuncPC(stubS35_191),
	runtype.FuncPC(stubS35_192),
	runtype.FuncPC(stubS35_193),
	runtype.FuncPC(stubS35_194),
	runtype.FuncPC(stubS35_195),
	runtype.FuncPC(stubS35_196),
	runtype.FuncPC(stubS35_197),
	runtype.FuncPC(stubS35_198),
	runtype.FuncPC(stubS35_199),
	runtype.FuncPC(stubS35_200),
	runtype.FuncPC(stubS35_201),
	runtype.FuncPC(stubS35_202),
	runtype.FuncPC(stubS35_203),
	runtype.FuncPC(stubS35_204),
	runtype.FuncPC(stubS35_205),
	runtype.FuncPC(stubS35_206),
	runtype.FuncPC(stubS35_207),
	runtype.FuncPC(stubS35_208),
	runtype.FuncPC(stubS35_209),
	runtype.FuncPC(stubS35_210),
	runtype.FuncPC(stubS35_211),
	runtype.FuncPC(stubS35_212),
	runtype.FuncPC(stubS35_213),
	runtype.FuncPC(stubS35_214),
	runtype.FuncPC(stubS35_215),
	runtype.FuncPC(stubS35_216),
	runtype.FuncPC(stubS35_217),
	runtype.FuncPC(stubS35_218),
	runtype.FuncPC(stubS35_219),
	runtype.FuncPC(stubS35_220),
	runtype.FuncPC(stubS35_221),
	runtype.FuncPC(stubS35_222),
	runtype.FuncPC(stubS35_223),
	runtype.FuncPC(stubS35_224),
	runtype.FuncPC(stubS35_225),
	runtype.FuncPC(stubS35_226),
	runtype.FuncPC(stubS35_227),
	runtype.FuncPC(stubS35_228),
	runtype.FuncPC(stubS35_229),
	runtype.FuncPC(stubS35_230),
	runtype.FuncPC(stubS35_231),
	runtype.FuncPC(stubS35_232),
	runtype.FuncPC(stubS35_233),
	runtype.FuncPC(stubS35_234),
	runtype.FuncPC(stubS35_235),
	runtype.FuncPC(stubS35_236),
	runtype.FuncPC(stubS35_237),
	runtype.FuncPC(stubS35_238),
	runtype.FuncPC(stubS35_239),
	runtype.FuncPC(stubS35_240),
	runtype.FuncPC(stubS35_241),
	runtype.FuncPC(stubS35_242),
	runtype.FuncPC(stubS35_243),
	runtype.FuncPC(stubS35_244),
	runtype.FuncPC(stubS35_245),
	runtype.FuncPC(stubS35_246),
	runtype.FuncPC(stubS35_247),
	runtype.FuncPC(stubS35_248),
	runtype.FuncPC(stubS35_249),
	runtype.FuncPC(stubS35_250),
	runtype.FuncPC(stubS35_251),
	runtype.FuncPC(stubS35_252),
	runtype.FuncPC(stubS35_253),
	runtype.FuncPC(stubS35_254),
	runtype.FuncPC(stubS35_255),
}
