// Code generated by gen_pools.go; DO NOT EDIT.
// Shape S36 pool: 256 slots.

package stubs

import (
	"log/slog"
	"unsafe"

	"github.com/mvm-sh/mvm/runtype"
)

const poolSizeS36 = 256

//go:noinline
func stubS36_0(recv unsafe.Pointer) slog.Value { return dispatchS36(0, recv) }

//go:noinline
func stubS36_1(recv unsafe.Pointer) slog.Value { return dispatchS36(1, recv) }

//go:noinline
func stubS36_2(recv unsafe.Pointer) slog.Value { return dispatchS36(2, recv) }

//go:noinline
func stubS36_3(recv unsafe.Pointer) slog.Value { return dispatchS36(3, recv) }

//go:noinline
func stubS36_4(recv unsafe.Pointer) slog.Value { return dispatchS36(4, recv) }

//go:noinline
func stubS36_5(recv unsafe.Pointer) slog.Value { return dispatchS36(5, recv) }

//go:noinline
func stubS36_6(recv unsafe.Pointer) slog.Value { return dispatchS36(6, recv) }

//go:noinline
func stubS36_7(recv unsafe.Pointer) slog.Value { return dispatchS36(7, recv) }

//go:noinline
func stubS36_8(recv unsafe.Pointer) slog.Value { return dispatchS36(8, recv) }

//go:noinline
func stubS36_9(recv unsafe.Pointer) slog.Value { return dispatchS36(9, recv) }

//go:noinline
func stubS36_10(recv unsafe.Pointer) slog.Value { return dispatchS36(10, recv) }

//go:noinline
func stubS36_11(recv unsafe.Pointer) slog.Value { return dispatchS36(11, recv) }

//go:noinline
func stubS36_12(recv unsafe.Pointer) slog.Value { return dispatchS36(12, recv) }

//go:noinline
func stubS36_13(recv unsafe.Pointer) slog.Value { return dispatchS36(13, recv) }

//go:noinline
func stubS36_14(recv unsafe.Pointer) slog.Value { return dispatchS36(14, recv) }

//go:noinline
func stubS36_15(recv unsafe.Pointer) slog.Value { return dispatchS36(15, recv) }

//go:noinline
func stubS36_16(recv unsafe.Pointer) slog.Value { return dispatchS36(16, recv) }

//go:noinline
func stubS36_17(recv unsafe.Pointer) slog.Value { return dispatchS36(17, recv) }

//go:noinline
func stubS36_18(recv unsafe.Pointer) slog.Value { return dispatchS36(18, recv) }

//go:noinline
func stubS36_19(recv unsafe.Pointer) slog.Value { return dispatchS36(19, recv) }

//go:noinline
func stubS36_20(recv unsafe.Pointer) slog.Value { return dispatchS36(20, recv) }

//go:noinline
func stubS36_21(recv unsafe.Pointer) slog.Value { return dispatchS36(21, recv) }

//go:noinline
func stubS36_22(recv unsafe.Pointer) slog.Value { return dispatchS36(22, recv) }

//go:noinline
func stubS36_23(recv unsafe.Pointer) slog.Value { return dispatchS36(23, recv) }

//go:noinline
func stubS36_24(recv unsafe.Pointer) slog.Value { return dispatchS36(24, recv) }

//go:noinline
func stubS36_25(recv unsafe.Pointer) slog.Value { return dispatchS36(25, recv) }

//go:noinline
func stubS36_26(recv unsafe.Pointer) slog.Value { return dispatchS36(26, recv) }

//go:noinline
func stubS36_27(recv unsafe.Pointer) slog.Value { return dispatchS36(27, recv) }

//go:noinline
func stubS36_28(recv unsafe.Pointer) slog.Value { return dispatchS36(28, recv) }

//go:noinline
func stubS36_29(recv unsafe.Pointer) slog.Value { return dispatchS36(29, recv) }

//go:noinline
func stubS36_30(recv unsafe.Pointer) slog.Value { return dispatchS36(30, recv) }

//go:noinline
func stubS36_31(recv unsafe.Pointer) slog.Value { return dispatchS36(31, recv) }

//go:noinline
func stubS36_32(recv unsafe.Pointer) slog.Value { return dispatchS36(32, recv) }

//go:noinline
func stubS36_33(recv unsafe.Pointer) slog.Value { return dispatchS36(33, recv) }

//go:noinline
func stubS36_34(recv unsafe.Pointer) slog.Value { return dispatchS36(34, recv) }

//go:noinline
func stubS36_35(recv unsafe.Pointer) slog.Value { return dispatchS36(35, recv) }

//go:noinline
func stubS36_36(recv unsafe.Pointer) slog.Value { return dispatchS36(36, recv) }

//go:noinline
func stubS36_37(recv unsafe.Pointer) slog.Value { return dispatchS36(37, recv) }

//go:noinline
func stubS36_38(recv unsafe.Pointer) slog.Value { return dispatchS36(38, recv) }

//go:noinline
func stubS36_39(recv unsafe.Pointer) slog.Value { return dispatchS36(39, recv) }

//go:noinline
func stubS36_40(recv unsafe.Pointer) slog.Value { return dispatchS36(40, recv) }

//go:noinline
func stubS36_41(recv unsafe.Pointer) slog.Value { return dispatchS36(41, recv) }

//go:noinline
func stubS36_42(recv unsafe.Pointer) slog.Value { return dispatchS36(42, recv) }

//go:noinline
func stubS36_43(recv unsafe.Pointer) slog.Value { return dispatchS36(43, recv) }

//go:noinline
func stubS36_44(recv unsafe.Pointer) slog.Value { return dispatchS36(44, recv) }

//go:noinline
func stubS36_45(recv unsafe.Pointer) slog.Value { return dispatchS36(45, recv) }

//go:noinline
func stubS36_46(recv unsafe.Pointer) slog.Value { return dispatchS36(46, recv) }

//go:noinline
func stubS36_47(recv unsafe.Pointer) slog.Value { return dispatchS36(47, recv) }

//go:noinline
func stubS36_48(recv unsafe.Pointer) slog.Value { return dispatchS36(48, recv) }

//go:noinline
func stubS36_49(recv unsafe.Pointer) slog.Value { return dispatchS36(49, recv) }

//go:noinline
func stubS36_50(recv unsafe.Pointer) slog.Value { return dispatchS36(50, recv) }

//go:noinline
func stubS36_51(recv unsafe.Pointer) slog.Value { return dispatchS36(51, recv) }

//go:noinline
func stubS36_52(recv unsafe.Pointer) slog.Value { return dispatchS36(52, recv) }

//go:noinline
func stubS36_53(recv unsafe.Pointer) slog.Value { return dispatchS36(53, recv) }

//go:noinline
func stubS36_54(recv unsafe.Pointer) slog.Value { return dispatchS36(54, recv) }

//go:noinline
func stubS36_55(recv unsafe.Pointer) slog.Value { return dispatchS36(55, recv) }

//go:noinline
func stubS36_56(recv unsafe.Pointer) slog.Value { return dispatchS36(56, recv) }

//go:noinline
func stubS36_57(recv unsafe.Pointer) slog.Value { return dispatchS36(57, recv) }

//go:noinline
func stubS36_58(recv unsafe.Pointer) slog.Value { return dispatchS36(58, recv) }

//go:noinline
func stubS36_59(recv unsafe.Pointer) slog.Value { return dispatchS36(59, recv) }

//go:noinline
func stubS36_60(recv unsafe.Pointer) slog.Value { return dispatchS36(60, recv) }

//go:noinline
func stubS36_61(recv unsafe.Pointer) slog.Value { return dispatchS36(61, recv) }

//go:noinline
func stubS36_62(recv unsafe.Pointer) slog.Value { return dispatchS36(62, recv) }

//go:noinline
func stubS36_63(recv unsafe.Pointer) slog.Value { return dispatchS36(63, recv) }

//go:noinline
func stubS36_64(recv unsafe.Pointer) slog.Value { return dispatchS36(64, recv) }

//go:noinline
func stubS36_65(recv unsafe.Pointer) slog.Value { return dispatchS36(65, recv) }

//go:noinline
func stubS36_66(recv unsafe.Pointer) slog.Value { return dispatchS36(66, recv) }

//go:noinline
func stubS36_67(recv unsafe.Pointer) slog.Value { return dispatchS36(67, recv) }

//go:noinline
func stubS36_68(recv unsafe.Pointer) slog.Value { return dispatchS36(68, recv) }

//go:noinline
func stubS36_69(recv unsafe.Pointer) slog.Value { return dispatchS36(69, recv) }

//go:noinline
func stubS36_70(recv unsafe.Pointer) slog.Value { return dispatchS36(70, recv) }

//go:noinline
func stubS36_71(recv unsafe.Pointer) slog.Value { return dispatchS36(71, recv) }

//go:noinline
func stubS36_72(recv unsafe.Pointer) slog.Value { return dispatchS36(72, recv) }

//go:noinline
func stubS36_73(recv unsafe.Pointer) slog.Value { return dispatchS36(73, recv) }

//go:noinline
func stubS36_74(recv unsafe.Pointer) slog.Value { return dispatchS36(74, recv) }

//go:noinline
func stubS36_75(recv unsafe.Pointer) slog.Value { return dispatchS36(75, recv) }

//go:noinline
func stubS36_76(recv unsafe.Pointer) slog.Value { return dispatchS36(76, recv) }

//go:noinline
func stubS36_77(recv unsafe.Pointer) slog.Value { return dispatchS36(77, recv) }

//go:noinline
func stubS36_78(recv unsafe.Pointer) slog.Value { return dispatchS36(78, recv) }

//go:noinline
func stubS36_79(recv unsafe.Pointer) slog.Value { return dispatchS36(79, recv) }

//go:noinline
func stubS36_80(recv unsafe.Pointer) slog.Value { return dispatchS36(80, recv) }

//go:noinline
func stubS36_81(recv unsafe.Pointer) slog.Value { return dispatchS36(81, recv) }

//go:noinline
func stubS36_82(recv unsafe.Pointer) slog.Value { return dispatchS36(82, recv) }

//go:noinline
func stubS36_83(recv unsafe.Pointer) slog.Value { return dispatchS36(83, recv) }

//go:noinline
func stubS36_84(recv unsafe.Pointer) slog.Value { return dispatchS36(84, recv) }

//go:noinline
func stubS36_85(recv unsafe.Pointer) slog.Value { return dispatchS36(85, recv) }

//go:noinline
func stubS36_86(recv unsafe.Pointer) slog.Value { return dispatchS36(86, recv) }

//go:noinline
func stubS36_87(recv unsafe.Pointer) slog.Value { return dispatchS36(87, recv) }

//go:noinline
func stubS36_88(recv unsafe.Pointer) slog.Value { return dispatchS36(88, recv) }

//go:noinline
func stubS36_89(recv unsafe.Pointer) slog.Value { return dispatchS36(89, recv) }

//go:noinline
func stubS36_90(recv unsafe.Pointer) slog.Value { return dispatchS36(90, recv) }

//go:noinline
func stubS36_91(recv unsafe.Pointer) slog.Value { return dispatchS36(91, recv) }

//go:noinline
func stubS36_92(recv unsafe.Pointer) slog.Value { return dispatchS36(92, recv) }

//go:noinline
func stubS36_93(recv unsafe.Pointer) slog.Value { return dispatchS36(93, recv) }

//go:noinline
func stubS36_94(recv unsafe.Pointer) slog.Value { return dispatchS36(94, recv) }

//go:noinline
func stubS36_95(recv unsafe.Pointer) slog.Value { return dispatchS36(95, recv) }

//go:noinline
func stubS36_96(recv unsafe.Pointer) slog.Value { return dispatchS36(96, recv) }

//go:noinline
func stubS36_97(recv unsafe.Pointer) slog.Value { return dispatchS36(97, recv) }

//go:noinline
func stubS36_98(recv unsafe.Pointer) slog.Value { return dispatchS36(98, recv) }

//go:noinline
func stubS36_99(recv unsafe.Pointer) slog.Value { return dispatchS36(99, recv) }

//go:noinline
func stubS36_100(recv unsafe.Pointer) slog.Value { return dispatchS36(100, recv) }

//go:noinline
func stubS36_101(recv unsafe.Pointer) slog.Value { return dispatchS36(101, recv) }

//go:noinline
func stubS36_102(recv unsafe.Pointer) slog.Value { return dispatchS36(102, recv) }

//go:noinline
func stubS36_103(recv unsafe.Pointer) slog.Value { return dispatchS36(103, recv) }

//go:noinline
func stubS36_104(recv unsafe.Pointer) slog.Value { return dispatchS36(104, recv) }

//go:noinline
func stubS36_105(recv unsafe.Pointer) slog.Value { return dispatchS36(105, recv) }

//go:noinline
func stubS36_106(recv unsafe.Pointer) slog.Value { return dispatchS36(106, recv) }

//go:noinline
func stubS36_107(recv unsafe.Pointer) slog.Value { return dispatchS36(107, recv) }

//go:noinline
func stubS36_108(recv unsafe.Pointer) slog.Value { return dispatchS36(108, recv) }

//go:noinline
func stubS36_109(recv unsafe.Pointer) slog.Value { return dispatchS36(109, recv) }

//go:noinline
func stubS36_110(recv unsafe.Pointer) slog.Value { return dispatchS36(110, recv) }

//go:noinline
func stubS36_111(recv unsafe.Pointer) slog.Value { return dispatchS36(111, recv) }

//go:noinline
func stubS36_112(recv unsafe.Pointer) slog.Value { return dispatchS36(112, recv) }

//go:noinline
func stubS36_113(recv unsafe.Pointer) slog.Value { return dispatchS36(113, recv) }

//go:noinline
func stubS36_114(recv unsafe.Pointer) slog.Value { return dispatchS36(114, recv) }

//go:noinline
func stubS36_115(recv unsafe.Pointer) slog.Value { return dispatchS36(115, recv) }

//go:noinline
func stubS36_116(recv unsafe.Pointer) slog.Value { return dispatchS36(116, recv) }

//go:noinline
func stubS36_117(recv unsafe.Pointer) slog.Value { return dispatchS36(117, recv) }

//go:noinline
func stubS36_118(recv unsafe.Pointer) slog.Value { return dispatchS36(118, recv) }

//go:noinline
func stubS36_119(recv unsafe.Pointer) slog.Value { return dispatchS36(119, recv) }

//go:noinline
func stubS36_120(recv unsafe.Pointer) slog.Value { return dispatchS36(120, recv) }

//go:noinline
func stubS36_121(recv unsafe.Pointer) slog.Value { return dispatchS36(121, recv) }

//go:noinline
func stubS36_122(recv unsafe.Pointer) slog.Value { return dispatchS36(122, recv) }

//go:noinline
func stubS36_123(recv unsafe.Pointer) slog.Value { return dispatchS36(123, recv) }

//go:noinline
func stubS36_124(recv unsafe.Pointer) slog.Value { return dispatchS36(124, recv) }

//go:noinline
func stubS36_125(recv unsafe.Pointer) slog.Value { return dispatchS36(125, recv) }

//go:noinline
func stubS36_126(recv unsafe.Pointer) slog.Value { return dispatchS36(126, recv) }

//go:noinline
func stubS36_127(recv unsafe.Pointer) slog.Value { return dispatchS36(127, recv) }

//go:noinline
func stubS36_128(recv unsafe.Pointer) slog.Value { return dispatchS36(128, recv) }

//go:noinline
func stubS36_129(recv unsafe.Pointer) slog.Value { return dispatchS36(129, recv) }

//go:noinline
func stubS36_130(recv unsafe.Pointer) slog.Value { return dispatchS36(130, recv) }

//go:noinline
func stubS36_131(recv unsafe.Pointer) slog.Value { return dispatchS36(131, recv) }

//go:noinline
func stubS36_132(recv unsafe.Pointer) slog.Value { return dispatchS36(132, recv) }

//go:noinline
func stubS36_133(recv unsafe.Pointer) slog.Value { return dispatchS36(133, recv) }

//go:noinline
func stubS36_134(recv unsafe.Pointer) slog.Value { return dispatchS36(134, recv) }

//go:noinline
func stubS36_135(recv unsafe.Pointer) slog.Value { return dispatchS36(135, recv) }

//go:noinline
func stubS36_136(recv unsafe.Pointer) slog.Value { return dispatchS36(136, recv) }

//go:noinline
func stubS36_137(recv unsafe.Pointer) slog.Value { return dispatchS36(137, recv) }

//go:noinline
func stubS36_138(recv unsafe.Pointer) slog.Value { return dispatchS36(138, recv) }

//go:noinline
func stubS36_139(recv unsafe.Pointer) slog.Value { return dispatchS36(139, recv) }

//go:noinline
func stubS36_140(recv unsafe.Pointer) slog.Value { return dispatchS36(140, recv) }

//go:noinline
func stubS36_141(recv unsafe.Pointer) slog.Value { return dispatchS36(141, recv) }

//go:noinline
func stubS36_142(recv unsafe.Pointer) slog.Value { return dispatchS36(142, recv) }

//go:noinline
func stubS36_143(recv unsafe.Pointer) slog.Value { return dispatchS36(143, recv) }

//go:noinline
func stubS36_144(recv unsafe.Pointer) slog.Value { return dispatchS36(144, recv) }

//go:noinline
func stubS36_145(recv unsafe.Pointer) slog.Value { return dispatchS36(145, recv) }

//go:noinline
func stubS36_146(recv unsafe.Pointer) slog.Value { return dispatchS36(146, recv) }

//go:noinline
func stubS36_147(recv unsafe.Pointer) slog.Value { return dispatchS36(147, recv) }

//go:noinline
func stubS36_148(recv unsafe.Pointer) slog.Value { return dispatchS36(148, recv) }

//go:noinline
func stubS36_149(recv unsafe.Pointer) slog.Value { return dispatchS36(149, recv) }

//go:noinline
func stubS36_150(recv unsafe.Pointer) slog.Value { return dispatchS36(150, recv) }

//go:noinline
func stubS36_151(recv unsafe.Pointer) slog.Value { return dispatchS36(151, recv) }

//go:noinline
func stubS36_152(recv unsafe.Pointer) slog.Value { return dispatchS36(152, recv) }

//go:noinline
func stubS36_153(recv unsafe.Pointer) slog.Value { return dispatchS36(153, recv) }

//go:noinline
func stubS36_154(recv unsafe.Pointer) slog.Value { return dispatchS36(154, recv) }

//go:noinline
func stubS36_155(recv unsafe.Pointer) slog.Value { return dispatchS36(155, recv) }

//go:noinline
func stubS36_156(recv unsafe.Pointer) slog.Value { return dispatchS36(156, recv) }

//go:noinline
func stubS36_157(recv unsafe.Pointer) slog.Value { return dispatchS36(157, recv) }

//go:noinline
func stubS36_158(recv unsafe.Pointer) slog.Value { return dispatchS36(158, recv) }

//go:noinline
func stubS36_159(recv unsafe.Pointer) slog.Value { return dispatchS36(159, recv) }

//go:noinline
func stubS36_160(recv unsafe.Pointer) slog.Value { return dispatchS36(160, recv) }

//go:noinline
func stubS36_161(recv unsafe.Pointer) slog.Value { return dispatchS36(161, recv) }

//go:noinline
func stubS36_162(recv unsafe.Pointer) slog.Value { return dispatchS36(162, recv) }

//go:noinline
func stubS36_163(recv unsafe.Pointer) slog.Value { return dispatchS36(163, recv) }

//go:noinline
func stubS36_164(recv unsafe.Pointer) slog.Value { return dispatchS36(164, recv) }

//go:noinline
func stubS36_165(recv unsafe.Pointer) slog.Value { return dispatchS36(165, recv) }

//go:noinline
func stubS36_166(recv unsafe.Pointer) slog.Value { return dispatchS36(166, recv) }

//go:noinline
func stubS36_167(recv unsafe.Pointer) slog.Value { return dispatchS36(167, recv) }

//go:noinline
func stubS36_168(recv unsafe.Pointer) slog.Value { return dispatchS36(168, recv) }

//go:noinline
func stubS36_169(recv unsafe.Pointer) slog.Value { return dispatchS36(169, recv) }

//go:noinline
func stubS36_170(recv unsafe.Pointer) slog.Value { return dispatchS36(170, recv) }

//go:noinline
func stubS36_171(recv unsafe.Pointer) slog.Value { return dispatchS36(171, recv) }

//go:noinline
func stubS36_172(recv unsafe.Pointer) slog.Value { return dispatchS36(172, recv) }

//go:noinline
func stubS36_173(recv unsafe.Pointer) slog.Value { return dispatchS36(173, recv) }

//go:noinline
func stubS36_174(recv unsafe.Pointer) slog.Value { return dispatchS36(174, recv) }

//go:noinline
func stubS36_175(recv unsafe.Pointer) slog.Value { return dispatchS36(175, recv) }

//go:noinline
func stubS36_176(recv unsafe.Pointer) slog.Value { return dispatchS36(176, recv) }

//go:noinline
func stubS36_177(recv unsafe.Pointer) slog.Value { return dispatchS36(177, recv) }

//go:noinline
func stubS36_178(recv unsafe.Pointer) slog.Value { return dispatchS36(178, recv) }

//go:noinline
func stubS36_179(recv unsafe.Pointer) slog.Value { return dispatchS36(179, recv) }

//go:noinline
func stubS36_180(recv unsafe.Pointer) slog.Value { return dispatchS36(180, recv) }

//go:noinline
func stubS36_181(recv unsafe.Pointer) slog.Value { return dispatchS36(181, recv) }

//go:noinline
func stubS36_182(recv unsafe.Pointer) slog.Value { return dispatchS36(182, recv) }

//go:noinline
func stubS36_183(recv unsafe.Pointer) slog.Value { return dispatchS36(183, recv) }

//go:noinline
func stubS36_184(recv unsafe.Pointer) slog.Value { return dispatchS36(184, recv) }

//go:noinline
func stubS36_185(recv unsafe.Pointer) slog.Value { return dispatchS36(185, recv) }

//go:noinline
func stubS36_186(recv unsafe.Pointer) slog.Value { return dispatchS36(186, recv) }

//go:noinline
func stubS36_187(recv unsafe.Pointer) slog.Value { return dispatchS36(187, recv) }

//go:noinline
func stubS36_188(recv unsafe.Pointer) slog.Value { return dispatchS36(188, recv) }

//go:noinline
func stubS36_189(recv unsafe.Pointer) slog.Value { return dispatchS36(189, recv) }

//go:noinline
func stubS36_190(recv unsafe.Pointer) slog.Value { return dispatchS36(190, recv) }

//go:noinline
func stubS36_191(recv unsafe.Pointer) slog.Value { return dispatchS36(191, recv) }

//go:noinline
func stubS36_192(recv unsafe.Pointer) slog.Value { return dispatchS36(192, recv) }

//go:noinline
func stubS36_193(recv unsafe.Pointer) slog.Value { return dispatchS36(193, recv) }

//go:noinline
func stubS36_194(recv unsafe.Pointer) slog.Value { return dispatchS36(194, recv) }

//go:noinline
func stubS36_195(recv unsafe.Pointer) slog.Value { return dispatchS36(195, recv) }

//go:noinline
func stubS36_196(recv unsafe.Pointer) slog.Value { return dispatchS36(196, recv) }

//go:noinline
func stubS36_197(recv unsafe.Pointer) slog.Value { return dispatchS36(197, recv) }

//go:noinline
func stubS36_198(recv unsafe.Pointer) slog.Value { return dispatchS36(198, recv) }

//go:noinline
func stubS36_199(recv unsafe.Pointer) slog.Value { return dispatchS36(199, recv) }

//go:noinline
func stubS36_200(recv unsafe.Pointer) slog.Value { return dispatchS36(200, recv) }

//go:noinline
func stubS36_201(recv unsafe.Pointer) slog.Value { return dispatchS36(201, recv) }

//go:noinline
func stubS36_202(recv unsafe.Pointer) slog.Value { return dispatchS36(202, recv) }

//go:noinline
func stubS36_203(recv unsafe.Pointer) slog.Value { return dispatchS36(203, recv) }

//go:noinline
func stubS36_204(recv unsafe.Pointer) slog.Value { return dispatchS36(204, recv) }

//go:noinline
func stubS36_205(recv unsafe.Pointer) slog.Value { return dispatchS36(205, recv) }

//go:noinline
func stubS36_206(recv unsafe.Pointer) slog.Value { return dispatchS36(206, recv) }

//go:noinline
func stubS36_207(recv unsafe.Pointer) slog.Value { return dispatchS36(207, recv) }

//go:noinline
func stubS36_208(recv unsafe.Pointer) slog.Value { return dispatchS36(208, recv) }

//go:noinline
func stubS36_209(recv unsafe.Pointer) slog.Value { return dispatchS36(209, recv) }

//go:noinline
func stubS36_210(recv unsafe.Pointer) slog.Value { return dispatchS36(210, recv) }

//go:noinline
func stubS36_211(recv unsafe.Pointer) slog.Value { return dispatchS36(211, recv) }

//go:noinline
func stubS36_212(recv unsafe.Pointer) slog.Value { return dispatchS36(212, recv) }

//go:noinline
func stubS36_213(recv unsafe.Pointer) slog.Value { return dispatchS36(213, recv) }

//go:noinline
func stubS36_214(recv unsafe.Pointer) slog.Value { return dispatchS36(214, recv) }

//go:noinline
func stubS36_215(recv unsafe.Pointer) slog.Value { return dispatchS36(215, recv) }

//go:noinline
func stubS36_216(recv unsafe.Pointer) slog.Value { return dispatchS36(216, recv) }

//go:noinline
func stubS36_217(recv unsafe.Pointer) slog.Value { return dispatchS36(217, recv) }

//go:noinline
func stubS36_218(recv unsafe.Pointer) slog.Value { return dispatchS36(218, recv) }

//go:noinline
func stubS36_219(recv unsafe.Pointer) slog.Value { return dispatchS36(219, recv) }

//go:noinline
func stubS36_220(recv unsafe.Pointer) slog.Value { return dispatchS36(220, recv) }

//go:noinline
func stubS36_221(recv unsafe.Pointer) slog.Value { return dispatchS36(221, recv) }

//go:noinline
func stubS36_222(recv unsafe.Pointer) slog.Value { return dispatchS36(222, recv) }

//go:noinline
func stubS36_223(recv unsafe.Pointer) slog.Value { return dispatchS36(223, recv) }

//go:noinline
func stubS36_224(recv unsafe.Pointer) slog.Value { return dispatchS36(224, recv) }

//go:noinline
func stubS36_225(recv unsafe.Pointer) slog.Value { return dispatchS36(225, recv) }

//go:noinline
func stubS36_226(recv unsafe.Pointer) slog.Value { return dispatchS36(226, recv) }

//go:noinline
func stubS36_227(recv unsafe.Pointer) slog.Value { return dispatchS36(227, recv) }

//go:noinline
func stubS36_228(recv unsafe.Pointer) slog.Value { return dispatchS36(228, recv) }

//go:noinline
func stubS36_229(recv unsafe.Pointer) slog.Value { return dispatchS36(229, recv) }

//go:noinline
func stubS36_230(recv unsafe.Pointer) slog.Value { return dispatchS36(230, recv) }

//go:noinline
func stubS36_231(recv unsafe.Pointer) slog.Value { return dispatchS36(231, recv) }

//go:noinline
func stubS36_232(recv unsafe.Pointer) slog.Value { return dispatchS36(232, recv) }

//go:noinline
func stubS36_233(recv unsafe.Pointer) slog.Value { return dispatchS36(233, recv) }

//go:noinline
func stubS36_234(recv unsafe.Pointer) slog.Value { return dispatchS36(234, recv) }

//go:noinline
func stubS36_235(recv unsafe.Pointer) slog.Value { return dispatchS36(235, recv) }

//go:noinline
func stubS36_236(recv unsafe.Pointer) slog.Value { return dispatchS36(236, recv) }

//go:noinline
func stubS36_237(recv unsafe.Pointer) slog.Value { return dispatchS36(237, recv) }

//go:noinline
func stubS36_238(recv unsafe.Pointer) slog.Value { return dispatchS36(238, recv) }

//go:noinline
func stubS36_239(recv unsafe.Pointer) slog.Value { return dispatchS36(239, recv) }

//go:noinline
func stubS36_240(recv unsafe.Pointer) slog.Value { return dispatchS36(240, recv) }

//go:noinline
func stubS36_241(recv unsafe.Pointer) slog.Value { return dispatchS36(241, recv) }

//go:noinline
func stubS36_242(recv unsafe.Pointer) slog.Value { return dispatchS36(242, recv) }

//go:noinline
func stubS36_243(recv unsafe.Pointer) slog.Value { return dispatchS36(243, recv) }

//go:noinline
func stubS36_244(recv unsafe.Pointer) slog.Value { return dispatchS36(244, recv) }

//go:noinline
func stubS36_245(recv unsafe.Pointer) slog.Value { return dispatchS36(245, recv) }

//go:noinline
func stubS36_246(recv unsafe.Pointer) slog.Value { return dispatchS36(246, recv) }

//go:noinline
func stubS36_247(recv unsafe.Pointer) slog.Value { return dispatchS36(247, recv) }

//go:noinline
func stubS36_248(recv unsafe.Pointer) slog.Value { return dispatchS36(248, recv) }

//go:noinline
func stubS36_249(recv unsafe.Pointer) slog.Value { return dispatchS36(249, recv) }

//go:noinline
func stubS36_250(recv unsafe.Pointer) slog.Value { return dispatchS36(250, recv) }

//go:noinline
func stubS36_251(recv unsafe.Pointer) slog.Value { return dispatchS36(251, recv) }

//go:noinline
func stubS36_252(recv unsafe.Pointer) slog.Value { return dispatchS36(252, recv) }

//go:noinline
func stubS36_253(recv unsafe.Pointer) slog.Value { return dispatchS36(253, recv) }

//go:noinline
func stubS36_254(recv unsafe.Pointer) slog.Value { return dispatchS36(254, recv) }

//go:noinline
func stubS36_255(recv unsafe.Pointer) slog.Value { return dispatchS36(255, recv) }

var stubsS36 = [poolSizeS36]uintptr{
	runtype.FuncPC(stubS36_0),
	runtype.FuncPC(stubS36_1),
	runtype.FuncPC(stubS36_2),
	runtype.FuncPC(stubS36_3),
	runtype.FuncPC(stubS36_4),
	runtype.FuncPC(stubS36_5),
	runtype.FuncPC(stubS36_6),
	runtype.FuncPC(stubS36_7),
	runtype.FuncPC(stubS36_8),
	runtype.FuncPC(stubS36_9),
	runtype.FuncPC(stubS36_10),
	runtype.FuncPC(stubS36_11),
	runtype.FuncPC(stubS36_12),
	runtype.FuncPC(stubS36_13),
	runtype.FuncPC(stubS36_14),
	runtype.FuncPC(stubS36_15),
	runtype.FuncPC(stubS36_16),
	runtype.FuncPC(stubS36_17),
	runtype.FuncPC(stubS36_18),
	runtype.FuncPC(stubS36_19),
	runtype.FuncPC(stubS36_20),
	runtype.FuncPC(stubS36_21),
	runtype.FuncPC(stubS36_22),
	runtype.FuncPC(stubS36_23),
	runtype.FuncPC(stubS36_24),
	runtype.FuncPC(stubS36_25),
	runtype.FuncPC(stubS36_26),
	runtype.FuncPC(stubS36_27),
	runtype.FuncPC(stubS36_28),
	runtype.FuncPC(stubS36_29),
	runtype.FuncPC(stubS36_30),
	runtype.FuncPC(stubS36_31),
	runtype.FuncPC(stubS36_32),
	runtype.FuncPC(stubS36_33),
	runtype.FuncPC(stubS36_34),
	runtype.FuncPC(stubS36_35),
	runtype.FuncPC(stubS36_36),
	runtype.FuncPC(stubS36_37),
	runtype.FuncPC(stubS36_38),
	runtype.FuncPC(stubS36_39),
	runtype.FuncPC(stubS36_40),
	runtype.FuncPC(stubS36_41),
	runtype.FuncPC(stubS36_42),
	runtype.FuncPC(stubS36_43),
	runtype.FuncPC(stubS36_44),
	runtype.FuncPC(stubS36_45),
	runtype.FuncPC(stubS36_46),
	runtype.FuncPC(stubS36_47),
	runtype.FuncPC(stubS36_48),
	runtype.FuncPC(stubS36_49),
	runtype.FuncPC(stubS36_50),
	runtype.FuncPC(stubS36_51),
	runtype.FuncPC(stubS36_52),
	runtype.FuncPC(stubS36_53),
	runtype.FuncPC(stubS36_54),
	runtype.FuncPC(stubS36_55),
	runtype.FuncPC(stubS36_56),
	runtype.FuncPC(stubS36_57),
	runtype.FuncPC(stubS36_58),
	runtype.FuncPC(stubS36_59),
	runtype.FuncPC(stubS36_60),
	runtype.FuncPC(stubS36_61),
	runtype.FuncPC(stubS36_62),
	runtype.FuncPC(stubS36_63),
	runtype.FuncPC(stubS36_64),
	runtype.FuncPC(stubS36_65),
	runtype.FuncPC(stubS36_66),
	runtype.FuncPC(stubS36_67),
	runtype.FuncPC(stubS36_68),
	runtype.FuncPC(stubS36_69),
	runtype.FuncPC(stubS36_70),
	runtype.FuncPC(stubS36_71),
	runtype.FuncPC(stubS36_72),
	runtype.FuncPC(stubS36_73),
	runtype.FuncPC(stubS36_74),
	runtype.FuncPC(stubS36_75),
	runtype.FuncPC(stubS36_76),
	runtype.FuncPC(stubS36_77),
	runtype.FuncPC(stubS36_78),
	runtype.FuncPC(stubS36_79),
	runtype.FuncPC(stubS36_80),
	runtype.FuncPC(stubS36_81),
	runtype.FuncPC(stubS36_82),
	runtype.FuncPC(stubS36_83),
	runtype.FuncPC(stubS36_84),
	runtype.FuncPC(stubS36_85),
	runtype.FuncPC(stubS36_86),
	runtype.FuncPC(stubS36_87),
	runtype.FuncPC(stubS36_88),
	runtype.FuncPC(stubS36_89),
	runtype.FuncPC(stubS36_90),
	runtype.FuncPC(stubS36_91),
	runtype.FuncPC(stubS36_92),
	runtype.FuncPC(stubS36_93),
	runtype.FuncPC(stubS36_94),
	runtype.FuncPC(stubS36_95),
	runtype.FuncPC(stubS36_96),
	runtype.FuncPC(stubS36_97),
	runtype.FuncPC(stubS36_98),
	runtype.FuncPC(stubS36_99),
	runtype.FuncPC(stubS36_100),
	runtype.FuncPC(stubS36_101),
	runtype.FuncPC(stubS36_102),
	runtype.FuncPC(stubS36_103),
	runtype.FuncPC(stubS36_104),
	runtype.FuncPC(stubS36_105),
	runtype.FuncPC(stubS36_106),
	runtype.FuncPC(stubS36_107),
	runtype.FuncPC(stubS36_108),
	runtype.FuncPC(stubS36_109),
	runtype.FuncPC(stubS36_110),
	runtype.FuncPC(stubS36_111),
	runtype.FuncPC(stubS36_112),
	runtype.FuncPC(stubS36_113),
	runtype.FuncPC(stubS36_114),
	runtype.FuncPC(stubS36_115),
	runtype.FuncPC(stubS36_116),
	runtype.FuncPC(stubS36_117),
	runtype.FuncPC(stubS36_118),
	runtype.FuncPC(stubS36_119),
	runtype.FuncPC(stubS36_120),
	runtype.FuncPC(stubS36_121),
	runtype.FuncPC(stubS36_122),
	runtype.FuncPC(stubS36_123),
	runtype.FuncPC(stubS36_124),
	runtype.FuncPC(stubS36_125),
	runtype.FuncPC(stubS36_126),
	runtype.FuncPC(stubS36_127),
	runtype.FuncPC(stubS36_128),
	runtype.FuncPC(stubS36_129),
	runtype.FuncPC(stubS36_130),
	runtype.FuncPC(stubS36_131),
	runtype.FuncPC(stubS36_132),
	runtype.FuncPC(stubS36_133),
	runtype.FuncPC(stubS36_134),
	runtype.FuncPC(stubS36_135),
	runtype.FuncPC(stubS36_136),
	runtype.FuncPC(stubS36_137),
	runtype.FuncPC(stubS36_138),
	runtype.FuncPC(stubS36_139),
	runtype.FuncPC(stubS36_140),
	runtype.FuncPC(stubS36_141),
	runtype.FuncPC(stubS36_142),
	runtype.FuncPC(stubS36_143),
	runtype.FuncPC(stubS36_144),
	runtype.FuncPC(stubS36_145),
	runtype.FuncPC(stubS36_146),
	runtype.FuncPC(stubS36_147),
	runtype.FuncPC(stubS36_148),
	runtype.FuncPC(stubS36_149),
	runtype.FuncPC(stubS36_150),
	runtype.FuncPC(stubS36_151),
	runtype.FuncPC(stubS36_152),
	runtype.FuncPC(stubS36_153),
	runtype.FuncPC(stubS36_154),
	runtype.FuncPC(stubS36_155),
	runtype.FuncPC(stubS36_156),
	runtype.FuncPC(stubS36_157),
	runtype.FuncPC(stubS36_158),
	runtype.FuncPC(stubS36_159),
	runtype.FuncPC(stubS36_160),
	runtype.FuncPC(stubS36_161),
	runtype.FuncPC(stubS36_162),
	runtype.FuncPC(stubS36_163),
	runtype.FuncPC(stubS36_164),
	runtype.FuncPC(stubS36_165),
	runtype.FuncPC(stubS36_166),
	runtype.FuncPC(stubS36_167),
	runtype.FuncPC(stubS36_168),
	runtype.FuncPC(stubS36_169),
	runtype.FuncPC(stubS36_170),
	runtype.FuncPC(stubS36_171),
	runtype.FuncPC(stubS36_172),
	runtype.FuncPC(stubS36_173),
	runtype.FuncPC(stubS36_174),
	runtype.FuncPC(stubS36_175),
	runtype.FuncPC(stubS36_176),
	runtype.FuncPC(stubS36_177),
	runtype.FuncPC(stubS36_178),
	runtype.FuncPC(stubS36_179),
	runtype.FuncPC(stubS36_180),
	runtype.FuncPC(stubS36_181),
	runtype.FuncPC(stubS36_182),
	runtype.FuncPC(stubS36_183),
	runtype.FuncPC(stubS36_184),
	runtype.FuncPC(stubS36_185),
	runtype.FuncPC(stubS36_186),
	runtype.FuncPC(stubS36_187),
	runtype.FuncPC(stubS36_188),
	runtype.FuncPC(stubS36_189),
	runtype.FuncPC(stubS36_190),
	runtype.FuncPC(stubS36_191),
	runtype.FuncPC(stubS36_192),
	runtype.FuncPC(stubS36_193),
	runtype.FuncPC(stubS36_194),
	runtype.FuncPC(stubS36_195),
	runtype.FuncPC(stubS36_196),
	runtype.FuncPC(stubS36_197),
	runtype.FuncPC(stubS36_198),
	runtype.FuncPC(stubS36_199),
	runtype.FuncPC(stubS36_200),
	runtype.FuncPC(stubS36_201),
	runtype.FuncPC(stubS36_202),
	runtype.FuncPC(stubS36_203),
	runtype.FuncPC(stubS36_204),
	runtype.FuncPC(stubS36_205),
	runtype.FuncPC(stubS36_206),
	runtype.FuncPC(stubS36_207),
	runtype.FuncPC(stubS36_208),
	runtype.FuncPC(stubS36_209),
	runtype.FuncPC(stubS36_210),
	runtype.FuncPC(stubS36_211),
	runtype.FuncPC(stubS36_212),
	runtype.FuncPC(stubS36_213),
	runtype.FuncPC(stubS36_214),
	runtype.FuncPC(stubS36_215),
	runtype.FuncPC(stubS36_216),
	runtype.FuncPC(stubS36_217),
	runtype.FuncPC(stubS36_218),
	runtype.FuncPC(stubS36_219),
	runtype.FuncPC(stubS36_220),
	runtype.FuncPC(stubS36_221),
	runtype.FuncPC(stubS36_222),
	runtype.FuncPC(stubS36_223),
	runtype.FuncPC(stubS36_224),
	runtype.FuncPC(stubS36_225),
	runtype.FuncPC(stubS36_226),
	runtype.FuncPC(stubS36_227),
	runtype.FuncPC(stubS36_228),
	runtype.FuncPC(stubS36_229),
	runtype.FuncPC(stubS36_230),
	runtype.FuncPC(stubS36_231),
	runtype.FuncPC(stubS36_232),
	runtype.FuncPC(stubS36_233),
	runtype.FuncPC(stubS36_234),
	runtype.FuncPC(stubS36_235),
	runtype.FuncPC(stubS36_236),
	runtype.FuncPC(stubS36_237),
	runtype.FuncPC(stubS36_238),
	runtype.FuncPC(stubS36_239),
	runtype.FuncPC(stubS36_240),
	runtype.FuncPC(stubS36_241),
	runtype.FuncPC(stubS36_242),
	runtype.FuncPC(stubS36_243),
	runtype.FuncPC(stubS36_244),
	runtype.FuncPC(stubS36_245),
	runtype.FuncPC(stubS36_246),
	runtype.FuncPC(stubS36_247),
	runtype.FuncPC(stubS36_248),
	runtype.FuncPC(stubS36_249),
	runtype.FuncPC(stubS36_250),
	runtype.FuncPC(stubS36_251),
	runtype.FuncPC(stubS36_252),
	runtype.FuncPC(stubS36_253),
	runtype.FuncPC(stubS36_254),
	runtype.FuncPC(stubS36_255),
}
