// Code generated by gen_pools.go; DO NOT EDIT.
// Shape S21 pool: 256 slots.

package stubs

import (
	"unsafe"

	"github.com/mvm-sh/mvm/runtype"
)

const poolSizeS21 = 256

//go:noinline
func stubS21_0(recv unsafe.Pointer) bool { return dispatchS21(0, recv) }

//go:noinline
func stubS21_1(recv unsafe.Pointer) bool { return dispatchS21(1, recv) }

//go:noinline
func stubS21_2(recv unsafe.Pointer) bool { return dispatchS21(2, recv) }

//go:noinline
func stubS21_3(recv unsafe.Pointer) bool { return dispatchS21(3, recv) }

//go:noinline
func stubS21_4(recv unsafe.Pointer) bool { return dispatchS21(4, recv) }

//go:noinline
func stubS21_5(recv unsafe.Pointer) bool { return dispatchS21(5, recv) }

//go:noinline
func stubS21_6(recv unsafe.Pointer) bool { return dispatchS21(6, recv) }

//go:noinline
func stubS21_7(recv unsafe.Pointer) bool { return dispatchS21(7, recv) }

//go:noinline
func stubS21_8(recv unsafe.Pointer) bool { return dispatchS21(8, recv) }

//go:noinline
func stubS21_9(recv unsafe.Pointer) bool { return dispatchS21(9, recv) }

//go:noinline
func stubS21_10(recv unsafe.Pointer) bool { return dispatchS21(10, recv) }

//go:noinline
func stubS21_11(recv unsafe.Pointer) bool { return dispatchS21(11, recv) }

//go:noinline
func stubS21_12(recv unsafe.Pointer) bool { return dispatchS21(12, recv) }

//go:noinline
func stubS21_13(recv unsafe.Pointer) bool { return dispatchS21(13, recv) }

//go:noinline
func stubS21_14(recv unsafe.Pointer) bool { return dispatchS21(14, recv) }

//go:noinline
func stubS21_15(recv unsafe.Pointer) bool { return dispatchS21(15, recv) }

//go:noinline
func stubS21_16(recv unsafe.Pointer) bool { return dispatchS21(16, recv) }

//go:noinline
func stubS21_17(recv unsafe.Pointer) bool { return dispatchS21(17, recv) }

//go:noinline
func stubS21_18(recv unsafe.Pointer) bool { return dispatchS21(18, recv) }

//go:noinline
func stubS21_19(recv unsafe.Pointer) bool { return dispatchS21(19, recv) }

//go:noinline
func stubS21_20(recv unsafe.Pointer) bool { return dispatchS21(20, recv) }

//go:noinline
func stubS21_21(recv unsafe.Pointer) bool { return dispatchS21(21, recv) }

//go:noinline
func stubS21_22(recv unsafe.Pointer) bool { return dispatchS21(22, recv) }

//go:noinline
func stubS21_23(recv unsafe.Pointer) bool { return dispatchS21(23, recv) }

//go:noinline
func stubS21_24(recv unsafe.Pointer) bool { return dispatchS21(24, recv) }

//go:noinline
func stubS21_25(recv unsafe.Pointer) bool { return dispatchS21(25, recv) }

//go:noinline
func stubS21_26(recv unsafe.Pointer) bool { return dispatchS21(26, recv) }

//go:noinline
func stubS21_27(recv unsafe.Pointer) bool { return dispatchS21(27, recv) }

//go:noinline
func stubS21_28(recv unsafe.Pointer) bool { return dispatchS21(28, recv) }

//go:noinline
func stubS21_29(recv unsafe.Pointer) bool { return dispatchS21(29, recv) }

//go:noinline
func stubS21_30(recv unsafe.Pointer) bool { return dispatchS21(30, recv) }

//go:noinline
func stubS21_31(recv unsafe.Pointer) bool { return dispatchS21(31, recv) }

//go:noinline
func stubS21_32(recv unsafe.Pointer) bool { return dispatchS21(32, recv) }

//go:noinline
func stubS21_33(recv unsafe.Pointer) bool { return dispatchS21(33, recv) }

//go:noinline
func stubS21_34(recv unsafe.Pointer) bool { return dispatchS21(34, recv) }

//go:noinline
func stubS21_35(recv unsafe.Pointer) bool { return dispatchS21(35, recv) }

//go:noinline
func stubS21_36(recv unsafe.Pointer) bool { return dispatchS21(36, recv) }

//go:noinline
func stubS21_37(recv unsafe.Pointer) bool { return dispatchS21(37, recv) }

//go:noinline
func stubS21_38(recv unsafe.Pointer) bool { return dispatchS21(38, recv) }

//go:noinline
func stubS21_39(recv unsafe.Pointer) bool { return dispatchS21(39, recv) }

//go:noinline
func stubS21_40(recv unsafe.Pointer) bool { return dispatchS21(40, recv) }

//go:noinline
func stubS21_41(recv unsafe.Pointer) bool { return dispatchS21(41, recv) }

//go:noinline
func stubS21_42(recv unsafe.Pointer) bool { return dispatchS21(42, recv) }

//go:noinline
func stubS21_43(recv unsafe.Pointer) bool { return dispatchS21(43, recv) }

//go:noinline
func stubS21_44(recv unsafe.Pointer) bool { return dispatchS21(44, recv) }

//go:noinline
func stubS21_45(recv unsafe.Pointer) bool { return dispatchS21(45, recv) }

//go:noinline
func stubS21_46(recv unsafe.Pointer) bool { return dispatchS21(46, recv) }

//go:noinline
func stubS21_47(recv unsafe.Pointer) bool { return dispatchS21(47, recv) }

//go:noinline
func stubS21_48(recv unsafe.Pointer) bool { return dispatchS21(48, recv) }

//go:noinline
func stubS21_49(recv unsafe.Pointer) bool { return dispatchS21(49, recv) }

//go:noinline
func stubS21_50(recv unsafe.Pointer) bool { return dispatchS21(50, recv) }

//go:noinline
func stubS21_51(recv unsafe.Pointer) bool { return dispatchS21(51, recv) }

//go:noinline
func stubS21_52(recv unsafe.Pointer) bool { return dispatchS21(52, recv) }

//go:noinline
func stubS21_53(recv unsafe.Pointer) bool { return dispatchS21(53, recv) }

//go:noinline
func stubS21_54(recv unsafe.Pointer) bool { return dispatchS21(54, recv) }

//go:noinline
func stubS21_55(recv unsafe.Pointer) bool { return dispatchS21(55, recv) }

//go:noinline
func stubS21_56(recv unsafe.Pointer) bool { return dispatchS21(56, recv) }

//go:noinline
func stubS21_57(recv unsafe.Pointer) bool { return dispatchS21(57, recv) }

//go:noinline
func stubS21_58(recv unsafe.Pointer) bool { return dispatchS21(58, recv) }

//go:noinline
func stubS21_59(recv unsafe.Pointer) bool { return dispatchS21(59, recv) }

//go:noinline
func stubS21_60(recv unsafe.Pointer) bool { return dispatchS21(60, recv) }

//go:noinline
func stubS21_61(recv unsafe.Pointer) bool { return dispatchS21(61, recv) }

//go:noinline
func stubS21_62(recv unsafe.Pointer) bool { return dispatchS21(62, recv) }

//go:noinline
func stubS21_63(recv unsafe.Pointer) bool { return dispatchS21(63, recv) }

//go:noinline
func stubS21_64(recv unsafe.Pointer) bool { return dispatchS21(64, recv) }

//go:noinline
func stubS21_65(recv unsafe.Pointer) bool { return dispatchS21(65, recv) }

//go:noinline
func stubS21_66(recv unsafe.Pointer) bool { return dispatchS21(66, recv) }

//go:noinline
func stubS21_67(recv unsafe.Pointer) bool { return dispatchS21(67, recv) }

//go:noinline
func stubS21_68(recv unsafe.Pointer) bool { return dispatchS21(68, recv) }

//go:noinline
func stubS21_69(recv unsafe.Pointer) bool { return dispatchS21(69, recv) }

//go:noinline
func stubS21_70(recv unsafe.Pointer) bool { return dispatchS21(70, recv) }

//go:noinline
func stubS21_71(recv unsafe.Pointer) bool { return dispatchS21(71, recv) }

//go:noinline
func stubS21_72(recv unsafe.Pointer) bool { return dispatchS21(72, recv) }

//go:noinline
func stubS21_73(recv unsafe.Pointer) bool { return dispatchS21(73, recv) }

//go:noinline
func stubS21_74(recv unsafe.Pointer) bool { return dispatchS21(74, recv) }

//go:noinline
func stubS21_75(recv unsafe.Pointer) bool { return dispatchS21(75, recv) }

//go:noinline
func stubS21_76(recv unsafe.Pointer) bool { return dispatchS21(76, recv) }

//go:noinline
func stubS21_77(recv unsafe.Pointer) bool { return dispatchS21(77, recv) }

//go:noinline
func stubS21_78(recv unsafe.Pointer) bool { return dispatchS21(78, recv) }

//go:noinline
func stubS21_79(recv unsafe.Pointer) bool { return dispatchS21(79, recv) }

//go:noinline
func stubS21_80(recv unsafe.Pointer) bool { return dispatchS21(80, recv) }

//go:noinline
func stubS21_81(recv unsafe.Pointer) bool { return dispatchS21(81, recv) }

//go:noinline
func stubS21_82(recv unsafe.Pointer) bool { return dispatchS21(82, recv) }

//go:noinline
func stubS21_83(recv unsafe.Pointer) bool { return dispatchS21(83, recv) }

//go:noinline
func stubS21_84(recv unsafe.Pointer) bool { return dispatchS21(84, recv) }

//go:noinline
func stubS21_85(recv unsafe.Pointer) bool { return dispatchS21(85, recv) }

//go:noinline
func stubS21_86(recv unsafe.Pointer) bool { return dispatchS21(86, recv) }

//go:noinline
func stubS21_87(recv unsafe.Pointer) bool { return dispatchS21(87, recv) }

//go:noinline
func stubS21_88(recv unsafe.Pointer) bool { return dispatchS21(88, recv) }

//go:noinline
func stubS21_89(recv unsafe.Pointer) bool { return dispatchS21(89, recv) }

//go:noinline
func stubS21_90(recv unsafe.Pointer) bool { return dispatchS21(90, recv) }

//go:noinline
func stubS21_91(recv unsafe.Pointer) bool { return dispatchS21(91, recv) }

//go:noinline
func stubS21_92(recv unsafe.Pointer) bool { return dispatchS21(92, recv) }

//go:noinline
func stubS21_93(recv unsafe.Pointer) bool { return dispatchS21(93, recv) }

//go:noinline
func stubS21_94(recv unsafe.Pointer) bool { return dispatchS21(94, recv) }

//go:noinline
func stubS21_95(recv unsafe.Pointer) bool { return dispatchS21(95, recv) }

//go:noinline
func stubS21_96(recv unsafe.Pointer) bool { return dispatchS21(96, recv) }

//go:noinline
func stubS21_97(recv unsafe.Pointer) bool { return dispatchS21(97, recv) }

//go:noinline
func stubS21_98(recv unsafe.Pointer) bool { return dispatchS21(98, recv) }

//go:noinline
func stubS21_99(recv unsafe.Pointer) bool { return dispatchS21(99, recv) }

//go:noinline
func stubS21_100(recv unsafe.Pointer) bool { return dispatchS21(100, recv) }

//go:noinline
func stubS21_101(recv unsafe.Pointer) bool { return dispatchS21(101, recv) }

//go:noinline
func stubS21_102(recv unsafe.Pointer) bool { return dispatchS21(102, recv) }

//go:noinline
func stubS21_103(recv unsafe.Pointer) bool { return dispatchS21(103, recv) }

//go:noinline
func stubS21_104(recv unsafe.Pointer) bool { return dispatchS21(104, recv) }

//go:noinline
func stubS21_105(recv unsafe.Pointer) bool { return dispatchS21(105, recv) }

//go:noinline
func stubS21_106(recv unsafe.Pointer) bool { return dispatchS21(106, recv) }

//go:noinline
func stubS21_107(recv unsafe.Pointer) bool { return dispatchS21(107, recv) }

//go:noinline
func stubS21_108(recv unsafe.Pointer) bool { return dispatchS21(108, recv) }

//go:noinline
func stubS21_109(recv unsafe.Pointer) bool { return dispatchS21(109, recv) }

//go:noinline
func stubS21_110(recv unsafe.Pointer) bool { return dispatchS21(110, recv) }

//go:noinline
func stubS21_111(recv unsafe.Pointer) bool { return dispatchS21(111, recv) }

//go:noinline
func stubS21_112(recv unsafe.Pointer) bool { return dispatchS21(112, recv) }

//go:noinline
func stubS21_113(recv unsafe.Pointer) bool { return dispatchS21(113, recv) }

//go:noinline
func stubS21_114(recv unsafe.Pointer) bool { return dispatchS21(114, recv) }

//go:noinline
func stubS21_115(recv unsafe.Pointer) bool { return dispatchS21(115, recv) }

//go:noinline
func stubS21_116(recv unsafe.Pointer) bool { return dispatchS21(116, recv) }

//go:noinline
func stubS21_117(recv unsafe.Pointer) bool { return dispatchS21(117, recv) }

//go:noinline
func stubS21_118(recv unsafe.Pointer) bool { return dispatchS21(118, recv) }

//go:noinline
func stubS21_119(recv unsafe.Pointer) bool { return dispatchS21(119, recv) }

//go:noinline
func stubS21_120(recv unsafe.Pointer) bool { return dispatchS21(120, recv) }

//go:noinline
func stubS21_121(recv unsafe.Pointer) bool { return dispatchS21(121, recv) }

//go:noinline
func stubS21_122(recv unsafe.Pointer) bool { return dispatchS21(122, recv) }

//go:noinline
func stubS21_123(recv unsafe.Pointer) bool { return dispatchS21(123, recv) }

//go:noinline
func stubS21_124(recv unsafe.Pointer) bool { return dispatchS21(124, recv) }

//go:noinline
func stubS21_125(recv unsafe.Pointer) bool { return dispatchS21(125, recv) }

//go:noinline
func stubS21_126(recv unsafe.Pointer) bool { return dispatchS21(126, recv) }

//go:noinline
func stubS21_127(recv unsafe.Pointer) bool { return dispatchS21(127, recv) }

//go:noinline
func stubS21_128(recv unsafe.Pointer) bool { return dispatchS21(128, recv) }

//go:noinline
func stubS21_129(recv unsafe.Pointer) bool { return dispatchS21(129, recv) }

//go:noinline
func stubS21_130(recv unsafe.Pointer) bool { return dispatchS21(130, recv) }

//go:noinline
func stubS21_131(recv unsafe.Pointer) bool { return dispatchS21(131, recv) }

//go:noinline
func stubS21_132(recv unsafe.Pointer) bool { return dispatchS21(132, recv) }

//go:noinline
func stubS21_133(recv unsafe.Pointer) bool { return dispatchS21(133, recv) }

//go:noinline
func stubS21_134(recv unsafe.Pointer) bool { return dispatchS21(134, recv) }

//go:noinline
func stubS21_135(recv unsafe.Pointer) bool { return dispatchS21(135, recv) }

//go:noinline
func stubS21_136(recv unsafe.Pointer) bool { return dispatchS21(136, recv) }

//go:noinline
func stubS21_137(recv unsafe.Pointer) bool { return dispatchS21(137, recv) }

//go:noinline
func stubS21_138(recv unsafe.Pointer) bool { return dispatchS21(138, recv) }

//go:noinline
func stubS21_139(recv unsafe.Pointer) bool { return dispatchS21(139, recv) }

//go:noinline
func stubS21_140(recv unsafe.Pointer) bool { return dispatchS21(140, recv) }

//go:noinline
func stubS21_141(recv unsafe.Pointer) bool { return dispatchS21(141, recv) }

//go:noinline
func stubS21_142(recv unsafe.Pointer) bool { return dispatchS21(142, recv) }

//go:noinline
func stubS21_143(recv unsafe.Pointer) bool { return dispatchS21(143, recv) }

//go:noinline
func stubS21_144(recv unsafe.Pointer) bool { return dispatchS21(144, recv) }

//go:noinline
func stubS21_145(recv unsafe.Pointer) bool { return dispatchS21(145, recv) }

//go:noinline
func stubS21_146(recv unsafe.Pointer) bool { return dispatchS21(146, recv) }

//go:noinline
func stubS21_147(recv unsafe.Pointer) bool { return dispatchS21(147, recv) }

//go:noinline
func stubS21_148(recv unsafe.Pointer) bool { return dispatchS21(148, recv) }

//go:noinline
func stubS21_149(recv unsafe.Pointer) bool { return dispatchS21(149, recv) }

//go:noinline
func stubS21_150(recv unsafe.Pointer) bool { return dispatchS21(150, recv) }

//go:noinline
func stubS21_151(recv unsafe.Pointer) bool { return dispatchS21(151, recv) }

//go:noinline
func stubS21_152(recv unsafe.Pointer) bool { return dispatchS21(152, recv) }

//go:noinline
func stubS21_153(recv unsafe.Pointer) bool { return dispatchS21(153, recv) }

//go:noinline
func stubS21_154(recv unsafe.Pointer) bool { return dispatchS21(154, recv) }

//go:noinline
func stubS21_155(recv unsafe.Pointer) bool { return dispatchS21(155, recv) }

//go:noinline
func stubS21_156(recv unsafe.Pointer) bool { return dispatchS21(156, recv) }

//go:noinline
func stubS21_157(recv unsafe.Pointer) bool { return dispatchS21(157, recv) }

//go:noinline
func stubS21_158(recv unsafe.Pointer) bool { return dispatchS21(158, recv) }

//go:noinline
func stubS21_159(recv unsafe.Pointer) bool { return dispatchS21(159, recv) }

//go:noinline
func stubS21_160(recv unsafe.Pointer) bool { return dispatchS21(160, recv) }

//go:noinline
func stubS21_161(recv unsafe.Pointer) bool { return dispatchS21(161, recv) }

//go:noinline
func stubS21_162(recv unsafe.Pointer) bool { return dispatchS21(162, recv) }

//go:noinline
func stubS21_163(recv unsafe.Pointer) bool { return dispatchS21(163, recv) }

//go:noinline
func stubS21_164(recv unsafe.Pointer) bool { return dispatchS21(164, recv) }

//go:noinline
func stubS21_165(recv unsafe.Pointer) bool { return dispatchS21(165, recv) }

//go:noinline
func stubS21_166(recv unsafe.Pointer) bool { return dispatchS21(166, recv) }

//go:noinline
func stubS21_167(recv unsafe.Pointer) bool { return dispatchS21(167, recv) }

//go:noinline
func stubS21_168(recv unsafe.Pointer) bool { return dispatchS21(168, recv) }

//go:noinline
func stubS21_169(recv unsafe.Pointer) bool { return dispatchS21(169, recv) }

//go:noinline
func stubS21_170(recv unsafe.Pointer) bool { return dispatchS21(170, recv) }

//go:noinline
func stubS21_171(recv unsafe.Pointer) bool { return dispatchS21(171, recv) }

//go:noinline
func stubS21_172(recv unsafe.Pointer) bool { return dispatchS21(172, recv) }

//go:noinline
func stubS21_173(recv unsafe.Pointer) bool { return dispatchS21(173, recv) }

//go:noinline
func stubS21_174(recv unsafe.Pointer) bool { return dispatchS21(174, recv) }

//go:noinline
func stubS21_175(recv unsafe.Pointer) bool { return dispatchS21(175, recv) }

//go:noinline
func stubS21_176(recv unsafe.Pointer) bool { return dispatchS21(176, recv) }

//go:noinline
func stubS21_177(recv unsafe.Pointer) bool { return dispatchS21(177, recv) }

//go:noinline
func stubS21_178(recv unsafe.Pointer) bool { return dispatchS21(178, recv) }

//go:noinline
func stubS21_179(recv unsafe.Pointer) bool { return dispatchS21(179, recv) }

//go:noinline
func stubS21_180(recv unsafe.Pointer) bool { return dispatchS21(180, recv) }

//go:noinline
func stubS21_181(recv unsafe.Pointer) bool { return dispatchS21(181, recv) }

//go:noinline
func stubS21_182(recv unsafe.Pointer) bool { return dispatchS21(182, recv) }

//go:noinline
func stubS21_183(recv unsafe.Pointer) bool { return dispatchS21(183, recv) }

//go:noinline
func stubS21_184(recv unsafe.Pointer) bool { return dispatchS21(184, recv) }

//go:noinline
func stubS21_185(recv unsafe.Pointer) bool { return dispatchS21(185, recv) }

//go:noinline
func stubS21_186(recv unsafe.Pointer) bool { return dispatchS21(186, recv) }

//go:noinline
func stubS21_187(recv unsafe.Pointer) bool { return dispatchS21(187, recv) }

//go:noinline
func stubS21_188(recv unsafe.Pointer) bool { return dispatchS21(188, recv) }

//go:noinline
func stubS21_189(recv unsafe.Pointer) bool { return dispatchS21(189, recv) }

//go:noinline
func stubS21_190(recv unsafe.Pointer) bool { return dispatchS21(190, recv) }

//go:noinline
func stubS21_191(recv unsafe.Pointer) bool { return dispatchS21(191, recv) }

//go:noinline
func stubS21_192(recv unsafe.Pointer) bool { return dispatchS21(192, recv) }

//go:noinline
func stubS21_193(recv unsafe.Pointer) bool { return dispatchS21(193, recv) }

//go:noinline
func stubS21_194(recv unsafe.Pointer) bool { return dispatchS21(194, recv) }

//go:noinline
func stubS21_195(recv unsafe.Pointer) bool { return dispatchS21(195, recv) }

//go:noinline
func stubS21_196(recv unsafe.Pointer) bool { return dispatchS21(196, recv) }

//go:noinline
func stubS21_197(recv unsafe.Pointer) bool { return dispatchS21(197, recv) }

//go:noinline
func stubS21_198(recv unsafe.Pointer) bool { return dispatchS21(198, recv) }

//go:noinline
func stubS21_199(recv unsafe.Pointer) bool { return dispatchS21(199, recv) }

//go:noinline
func stubS21_200(recv unsafe.Pointer) bool { return dispatchS21(200, recv) }

//go:noinline
func stubS21_201(recv unsafe.Pointer) bool { return dispatchS21(201, recv) }

//go:noinline
func stubS21_202(recv unsafe.Pointer) bool { return dispatchS21(202, recv) }

//go:noinline
func stubS21_203(recv unsafe.Pointer) bool { return dispatchS21(203, recv) }

//go:noinline
func stubS21_204(recv unsafe.Pointer) bool { return dispatchS21(204, recv) }

//go:noinline
func stubS21_205(recv unsafe.Pointer) bool { return dispatchS21(205, recv) }

//go:noinline
func stubS21_206(recv unsafe.Pointer) bool { return dispatchS21(206, recv) }

//go:noinline
func stubS21_207(recv unsafe.Pointer) bool { return dispatchS21(207, recv) }

//go:noinline
func stubS21_208(recv unsafe.Pointer) bool { return dispatchS21(208, recv) }

//go:noinline
func stubS21_209(recv unsafe.Pointer) bool { return dispatchS21(209, recv) }

//go:noinline
func stubS21_210(recv unsafe.Pointer) bool { return dispatchS21(210, recv) }

//go:noinline
func stubS21_211(recv unsafe.Pointer) bool { return dispatchS21(211, recv) }

//go:noinline
func stubS21_212(recv unsafe.Pointer) bool { return dispatchS21(212, recv) }

//go:noinline
func stubS21_213(recv unsafe.Pointer) bool { return dispatchS21(213, recv) }

//go:noinline
func stubS21_214(recv unsafe.Pointer) bool { return dispatchS21(214, recv) }

//go:noinline
func stubS21_215(recv unsafe.Pointer) bool { return dispatchS21(215, recv) }

//go:noinline
func stubS21_216(recv unsafe.Pointer) bool { return dispatchS21(216, recv) }

//go:noinline
func stubS21_217(recv unsafe.Pointer) bool { return dispatchS21(217, recv) }

//go:noinline
func stubS21_218(recv unsafe.Pointer) bool { return dispatchS21(218, recv) }

//go:noinline
func stubS21_219(recv unsafe.Pointer) bool { return dispatchS21(219, recv) }

//go:noinline
func stubS21_220(recv unsafe.Pointer) bool { return dispatchS21(220, recv) }

//go:noinline
func stubS21_221(recv unsafe.Pointer) bool { return dispatchS21(221, recv) }

//go:noinline
func stubS21_222(recv unsafe.Pointer) bool { return dispatchS21(222, recv) }

//go:noinline
func stubS21_223(recv unsafe.Pointer) bool { return dispatchS21(223, recv) }

//go:noinline
func stubS21_224(recv unsafe.Pointer) bool { return dispatchS21(224, recv) }

//go:noinline
func stubS21_225(recv unsafe.Pointer) bool { return dispatchS21(225, recv) }

//go:noinline
func stubS21_226(recv unsafe.Pointer) bool { return dispatchS21(226, recv) }

//go:noinline
func stubS21_227(recv unsafe.Pointer) bool { return dispatchS21(227, recv) }

//go:noinline
func stubS21_228(recv unsafe.Pointer) bool { return dispatchS21(228, recv) }

//go:noinline
func stubS21_229(recv unsafe.Pointer) bool { return dispatchS21(229, recv) }

//go:noinline
func stubS21_230(recv unsafe.Pointer) bool { return dispatchS21(230, recv) }

//go:noinline
func stubS21_231(recv unsafe.Pointer) bool { return dispatchS21(231, recv) }

//go:noinline
func stubS21_232(recv unsafe.Pointer) bool { return dispatchS21(232, recv) }

//go:noinline
func stubS21_233(recv unsafe.Pointer) bool { return dispatchS21(233, recv) }

//go:noinline
func stubS21_234(recv unsafe.Pointer) bool { return dispatchS21(234, recv) }

//go:noinline
func stubS21_235(recv unsafe.Pointer) bool { return dispatchS21(235, recv) }

//go:noinline
func stubS21_236(recv unsafe.Pointer) bool { return dispatchS21(236, recv) }

//go:noinline
func stubS21_237(recv unsafe.Pointer) bool { return dispatchS21(237, recv) }

//go:noinline
func stubS21_238(recv unsafe.Pointer) bool { return dispatchS21(238, recv) }

//go:noinline
func stubS21_239(recv unsafe.Pointer) bool { return dispatchS21(239, recv) }

//go:noinline
func stubS21_240(recv unsafe.Pointer) bool { return dispatchS21(240, recv) }

//go:noinline
func stubS21_241(recv unsafe.Pointer) bool { return dispatchS21(241, recv) }

//go:noinline
func stubS21_242(recv unsafe.Pointer) bool { return dispatchS21(242, recv) }

//go:noinline
func stubS21_243(recv unsafe.Pointer) bool { return dispatchS21(243, recv) }

//go:noinline
func stubS21_244(recv unsafe.Pointer) bool { return dispatchS21(244, recv) }

//go:noinline
func stubS21_245(recv unsafe.Pointer) bool { return dispatchS21(245, recv) }

//go:noinline
func stubS21_246(recv unsafe.Pointer) bool { return dispatchS21(246, recv) }

//go:noinline
func stubS21_247(recv unsafe.Pointer) bool { return dispatchS21(247, recv) }

//go:noinline
func stubS21_248(recv unsafe.Pointer) bool { return dispatchS21(248, recv) }

//go:noinline
func stubS21_249(recv unsafe.Pointer) bool { return dispatchS21(249, recv) }

//go:noinline
func stubS21_250(recv unsafe.Pointer) bool { return dispatchS21(250, recv) }

//go:noinline
func stubS21_251(recv unsafe.Pointer) bool { return dispatchS21(251, recv) }

//go:noinline
func stubS21_252(recv unsafe.Pointer) bool { return dispatchS21(252, recv) }

//go:noinline
func stubS21_253(recv unsafe.Pointer) bool { return dispatchS21(253, recv) }

//go:noinline
func stubS21_254(recv unsafe.Pointer) bool { return dispatchS21(254, recv) }

//go:noinline
func stubS21_255(recv unsafe.Pointer) bool { return dispatchS21(255, recv) }

var stubsS21 = [poolSizeS21]uintptr{
	runtype.FuncPC(stubS21_0),
	runtype.FuncPC(stubS21_1),
	runtype.FuncPC(stubS21_2),
	runtype.FuncPC(stubS21_3),
	runtype.FuncPC(stubS21_4),
	runtype.FuncPC(stubS21_5),
	runtype.FuncPC(stubS21_6),
	runtype.FuncPC(stubS21_7),
	runtype.FuncPC(stubS21_8),
	runtype.FuncPC(stubS21_9),
	runtype.FuncPC(stubS21_10),
	runtype.FuncPC(stubS21_11),
	runtype.FuncPC(stubS21_12),
	runtype.FuncPC(stubS21_13),
	runtype.FuncPC(stubS21_14),
	runtype.FuncPC(stubS21_15),
	runtype.FuncPC(stubS21_16),
	runtype.FuncPC(stubS21_17),
	runtype.FuncPC(stubS21_18),
	runtype.FuncPC(stubS21_19),
	runtype.FuncPC(stubS21_20),
	runtype.FuncPC(stubS21_21),
	runtype.FuncPC(stubS21_22),
	runtype.FuncPC(stubS21_23),
	runtype.FuncPC(stubS21_24),
	runtype.FuncPC(stubS21_25),
	runtype.FuncPC(stubS21_26),
	runtype.FuncPC(stubS21_27),
	runtype.FuncPC(stubS21_28),
	runtype.FuncPC(stubS21_29),
	runtype.FuncPC(stubS21_30),
	runtype.FuncPC(stubS21_31),
	runtype.FuncPC(stubS21_32),
	runtype.FuncPC(stubS21_33),
	runtype.FuncPC(stubS21_34),
	runtype.FuncPC(stubS21_35),
	runtype.FuncPC(stubS21_36),
	runtype.FuncPC(stubS21_37),
	runtype.FuncPC(stubS21_38),
	runtype.FuncPC(stubS21_39),
	runtype.FuncPC(stubS21_40),
	runtype.FuncPC(stubS21_41),
	runtype.FuncPC(stubS21_42),
	runtype.FuncPC(stubS21_43),
	runtype.FuncPC(stubS21_44),
	runtype.FuncPC(stubS21_45),
	runtype.FuncPC(stubS21_46),
	runtype.FuncPC(stubS21_47),
	runtype.FuncPC(stubS21_48),
	runtype.FuncPC(stubS21_49),
	runtype.FuncPC(stubS21_50),
	runtype.FuncPC(stubS21_51),
	runtype.FuncPC(stubS21_52),
	runtype.FuncPC(stubS21_53),
	runtype.FuncPC(stubS21_54),
	runtype.FuncPC(stubS21_55),
	runtype.FuncPC(stubS21_56),
	runtype.FuncPC(stubS21_57),
	runtype.FuncPC(stubS21_58),
	runtype.FuncPC(stubS21_59),
	runtype.FuncPC(stubS21_60),
	runtype.FuncPC(stubS21_61),
	runtype.FuncPC(stubS21_62),
	runtype.FuncPC(stubS21_63),
	runtype.FuncPC(stubS21_64),
	runtype.FuncPC(stubS21_65),
	runtype.FuncPC(stubS21_66),
	runtype.FuncPC(stubS21_67),
	runtype.FuncPC(stubS21_68),
	runtype.FuncPC(stubS21_69),
	runtype.FuncPC(stubS21_70),
	runtype.FuncPC(stubS21_71),
	runtype.FuncPC(stubS21_72),
	runtype.FuncPC(stubS21_73),
	runtype.FuncPC(stubS21_74),
	runtype.FuncPC(stubS21_75),
	runtype.FuncPC(stubS21_76),
	runtype.FuncPC(stubS21_77),
	runtype.FuncPC(stubS21_78),
	runtype.FuncPC(stubS21_79),
	runtype.FuncPC(stubS21_80),
	runtype.FuncPC(stubS21_81),
	runtype.FuncPC(stubS21_82),
	runtype.FuncPC(stubS21_83),
	runtype.FuncPC(stubS21_84),
	runtype.FuncPC(stubS21_85),
	runtype.FuncPC(stubS21_86),
	runtype.FuncPC(stubS21_87),
	runtype.FuncPC(stubS21_88),
	runtype.FuncPC(stubS21_89),
	runtype.FuncPC(stubS21_90),
	runtype.FuncPC(stubS21_91),
	runtype.FuncPC(stubS21_92),
	runtype.FuncPC(stubS21_93),
	runtype.FuncPC(stubS21_94),
	runtype.FuncPC(stubS21_95),
	runtype.FuncPC(stubS21_96),
	runtype.FuncPC(stubS21_97),
	runtype.FuncPC(stubS21_98),
	runtype.FuncPC(stubS21_99),
	runtype.FuncPC(stubS21_100),
	runtype.FuncPC(stubS21_101),
	runtype.FuncPC(stubS21_102),
	runtype.FuncPC(stubS21_103),
	runtype.FuncPC(stubS21_104),
	runtype.FuncPC(stubS21_105),
	runtype.FuncPC(stubS21_106),
	runtype.FuncPC(stubS21_107),
	runtype.FuncPC(stubS21_108),
	runtype.FuncPC(stubS21_109),
	runtype.FuncPC(stubS21_110),
	runtype.FuncPC(stubS21_111),
	runtype.FuncPC(stubS21_112),
	runtype.FuncPC(stubS21_113),
	runtype.FuncPC(stubS21_114),
	runtype.FuncPC(stubS21_115),
	runtype.FuncPC(stubS21_116),
	runtype.FuncPC(stubS21_117),
	runtype.FuncPC(stubS21_118),
	runtype.FuncPC(stubS21_119),
	runtype.FuncPC(stubS21_120),
	runtype.FuncPC(stubS21_121),
	runtype.FuncPC(stubS21_122),
	runtype.FuncPC(stubS21_123),
	runtype.FuncPC(stubS21_124),
	runtype.FuncPC(stubS21_125),
	runtype.FuncPC(stubS21_126),
	runtype.FuncPC(stubS21_127),
	runtype.FuncPC(stubS21_128),
	runtype.FuncPC(stubS21_129),
	runtype.FuncPC(stubS21_130),
	runtype.FuncPC(stubS21_131),
	runtype.FuncPC(stubS21_132),
	runtype.FuncPC(stubS21_133),
	runtype.FuncPC(stubS21_134),
	runtype.FuncPC(stubS21_135),
	runtype.FuncPC(stubS21_136),
	runtype.FuncPC(stubS21_137),
	runtype.FuncPC(stubS21_138),
	runtype.FuncPC(stubS21_139),
	runtype.FuncPC(stubS21_140),
	runtype.FuncPC(stubS21_141),
	runtype.FuncPC(stubS21_142),
	runtype.FuncPC(stubS21_143),
	runtype.FuncPC(stubS21_144),
	runtype.FuncPC(stubS21_145),
	runtype.FuncPC(stubS21_146),
	runtype.FuncPC(stubS21_147),
	runtype.FuncPC(stubS21_148),
	runtype.FuncPC(stubS21_149),
	runtype.FuncPC(stubS21_150),
	runtype.FuncPC(stubS21_151),
	runtype.FuncPC(stubS21_152),
	runtype.FuncPC(stubS21_153),
	runtype.FuncPC(stubS21_154),
	runtype.FuncPC(stubS21_155),
	runtype.FuncPC(stubS21_156),
	runtype.FuncPC(stubS21_157),
	runtype.FuncPC(stubS21_158),
	runtype.FuncPC(stubS21_159),
	runtype.FuncPC(stubS21_160),
	runtype.FuncPC(stubS21_161),
	runtype.FuncPC(stubS21_162),
	runtype.FuncPC(stubS21_163),
	runtype.FuncPC(stubS21_164),
	runtype.FuncPC(stubS21_165),
	runtype.FuncPC(stubS21_166),
	runtype.FuncPC(stubS21_167),
	runtype.FuncPC(stubS21_168),
	runtype.FuncPC(stubS21_169),
	runtype.FuncPC(stubS21_170),
	runtype.FuncPC(stubS21_171),
	runtype.FuncPC(stubS21_172),
	runtype.FuncPC(stubS21_173),
	runtype.FuncPC(stubS21_174),
	runtype.FuncPC(stubS21_175),
	runtype.FuncPC(stubS21_176),
	runtype.FuncPC(stubS21_177),
	runtype.FuncPC(stubS21_178),
	runtype.FuncPC(stubS21_179),
	runtype.FuncPC(stubS21_180),
	runtype.FuncPC(stubS21_181),
	runtype.FuncPC(stubS21_182),
	runtype.FuncPC(stubS21_183),
	runtype.FuncPC(stubS21_184),
	runtype.FuncPC(stubS21_185),
	runtype.FuncPC(stubS21_186),
	runtype.FuncPC(stubS21_187),
	runtype.FuncPC(stubS21_188),
	runtype.FuncPC(stubS21_189),
	runtype.FuncPC(stubS21_190),
	runtype.FuncPC(stubS21_191),
	runtype.FuncPC(stubS21_192),
	runtype.FuncPC(stubS21_193),
	runtype.FuncPC(stubS21_194),
	runtype.FuncPC(stubS21_195),
	runtype.FuncPC(stubS21_196),
	runtype.FuncPC(stubS21_197),
	runtype.FuncPC(stubS21_198),
	runtype.FuncPC(stubS21_199),
	runtype.FuncPC(stubS21_200),
	runtype.FuncPC(stubS21_201),
	runtype.FuncPC(stubS21_202),
	runtype.FuncPC(stubS21_203),
	runtype.FuncPC(stubS21_204),
	runtype.FuncPC(stubS21_205),
	runtype.FuncPC(stubS21_206),
	runtype.FuncPC(stubS21_207),
	runtype.FuncPC(stubS21_208),
	runtype.FuncPC(stubS21_209),
	runtype.FuncPC(stubS21_210),
	runtype.FuncPC(stubS21_211),
	runtype.FuncPC(stubS21_212),
	runtype.FuncPC(stubS21_213),
	runtype.FuncPC(stubS21_214),
	runtype.FuncPC(stubS21_215),
	runtype.FuncPC(stubS21_216),
	runtype.FuncPC(stubS21_217),
	runtype.FuncPC(stubS21_218),
	runtype.FuncPC(stubS21_219),
	runtype.FuncPC(stubS21_220),
	runtype.FuncPC(stubS21_221),
	runtype.FuncPC(stubS21_222),
	runtype.FuncPC(stubS21_223),
	runtype.FuncPC(stubS21_224),
	runtype.FuncPC(stubS21_225),
	runtype.FuncPC(stubS21_226),
	runtype.FuncPC(stubS21_227),
	runtype.FuncPC(stubS21_228),
	runtype.FuncPC(stubS21_229),
	runtype.FuncPC(stubS21_230),
	runtype.FuncPC(stubS21_231),
	runtype.FuncPC(stubS21_232),
	runtype.FuncPC(stubS21_233),
	runtype.FuncPC(stubS21_234),
	runtype.FuncPC(stubS21_235),
	runtype.FuncPC(stubS21_236),
	runtype.FuncPC(stubS21_237),
	runtype.FuncPC(stubS21_238),
	runtype.FuncPC(stubS21_239),
	runtype.FuncPC(stubS21_240),
	runtype.FuncPC(stubS21_241),
	runtype.FuncPC(stubS21_242),
	runtype.FuncPC(stubS21_243),
	runtype.FuncPC(stubS21_244),
	runtype.FuncPC(stubS21_245),
	runtype.FuncPC(stubS21_246),
	runtype.FuncPC(stubS21_247),
	runtype.FuncPC(stubS21_248),
	runtype.FuncPC(stubS21_249),
	runtype.FuncPC(stubS21_250),
	runtype.FuncPC(stubS21_251),
	runtype.FuncPC(stubS21_252),
	runtype.FuncPC(stubS21_253),
	runtype.FuncPC(stubS21_254),
	runtype.FuncPC(stubS21_255),
}
