// Code generated by gen_pools.go; DO NOT EDIT.
// Shape S34 pool: 256 slots.

package stubs

import (
	"log/slog"
	"unsafe"

	"github.com/mvm-sh/mvm/runtype"
)

const poolSizeS34 = 256

//go:noinline
func stubS34_0(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(0, recv, attrs)
}

//go:noinline
func stubS34_1(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(1, recv, attrs)
}

//go:noinline
func stubS34_2(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(2, recv, attrs)
}

//go:noinline
func stubS34_3(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(3, recv, attrs)
}

//go:noinline
func stubS34_4(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(4, recv, attrs)
}

//go:noinline
func stubS34_5(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(5, recv, attrs)
}

//go:noinline
func stubS34_6(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(6, recv, attrs)
}

//go:noinline
func stubS34_7(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(7, recv, attrs)
}

//go:noinline
func stubS34_8(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(8, recv, attrs)
}

//go:noinline
func stubS34_9(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(9, recv, attrs)
}

//go:noinline
func stubS34_10(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(10, recv, attrs)
}

//go:noinline
func stubS34_11(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(11, recv, attrs)
}

//go:noinline
func stubS34_12(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(12, recv, attrs)
}

//go:noinline
func stubS34_13(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(13, recv, attrs)
}

//go:noinline
func stubS34_14(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(14, recv, attrs)
}

//go:noinline
func stubS34_15(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(15, recv, attrs)
}

//go:noinline
func stubS34_16(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(16, recv, attrs)
}

//go:noinline
func stubS34_17(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(17, recv, attrs)
}

//go:noinline
func stubS34_18(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(18, recv, attrs)
}

//go:noinline
func stubS34_19(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(19, recv, attrs)
}

//go:noinline
func stubS34_20(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(20, recv, attrs)
}

//go:noinline
func stubS34_21(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(21, recv, attrs)
}

//go:noinline
func stubS34_22(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(22, recv, attrs)
}

//go:noinline
func stubS34_23(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(23, recv, attrs)
}

//go:noinline
func stubS34_24(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(24, recv, attrs)
}

//go:noinline
func stubS34_25(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(25, recv, attrs)
}

//go:noinline
func stubS34_26(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(26, recv, attrs)
}

//go:noinline
func stubS34_27(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(27, recv, attrs)
}

//go:noinline
func stubS34_28(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(28, recv, attrs)
}

//go:noinline
func stubS34_29(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(29, recv, attrs)
}

//go:noinline
func stubS34_30(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(30, recv, attrs)
}

//go:noinline
func stubS34_31(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(31, recv, attrs)
}

//go:noinline
func stubS34_32(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(32, recv, attrs)
}

//go:noinline
func stubS34_33(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(33, recv, attrs)
}

//go:noinline
func stubS34_34(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(34, recv, attrs)
}

//go:noinline
func stubS34_35(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(35, recv, attrs)
}

//go:noinline
func stubS34_36(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(36, recv, attrs)
}

//go:noinline
func stubS34_37(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(37, recv, attrs)
}

//go:noinline
func stubS34_38(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(38, recv, attrs)
}

//go:noinline
func stubS34_39(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(39, recv, attrs)
}

//go:noinline
func stubS34_40(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(40, recv, attrs)
}

//go:noinline
func stubS34_41(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(41, recv, attrs)
}

//go:noinline
func stubS34_42(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(42, recv, attrs)
}

//go:noinline
func stubS34_43(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(43, recv, attrs)
}

//go:noinline
func stubS34_44(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(44, recv, attrs)
}

//go:noinline
func stubS34_45(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(45, recv, attrs)
}

//go:noinline
func stubS34_46(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(46, recv, attrs)
}

//go:noinline
func stubS34_47(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(47, recv, attrs)
}

//go:noinline
func stubS34_48(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(48, recv, attrs)
}

//go:noinline
func stubS34_49(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(49, recv, attrs)
}

//go:noinline
func stubS34_50(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(50, recv, attrs)
}

//go:noinline
func stubS34_51(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(51, recv, attrs)
}

//go:noinline
func stubS34_52(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(52, recv, attrs)
}

//go:noinline
func stubS34_53(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(53, recv, attrs)
}

//go:noinline
func stubS34_54(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(54, recv, attrs)
}

//go:noinline
func stubS34_55(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(55, recv, attrs)
}

//go:noinline
func stubS34_56(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(56, recv, attrs)
}

//go:noinline
func stubS34_57(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(57, recv, attrs)
}

//go:noinline
func stubS34_58(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(58, recv, attrs)
}

//go:noinline
func stubS34_59(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(59, recv, attrs)
}

//go:noinline
func stubS34_60(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(60, recv, attrs)
}

//go:noinline
func stubS34_61(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(61, recv, attrs)
}

//go:noinline
func stubS34_62(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(62, recv, attrs)
}

//go:noinline
func stubS34_63(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(63, recv, attrs)
}

//go:noinline
func stubS34_64(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(64, recv, attrs)
}

//go:noinline
func stubS34_65(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(65, recv, attrs)
}

//go:noinline
func stubS34_66(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(66, recv, attrs)
}

//go:noinline
func stubS34_67(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(67, recv, attrs)
}

//go:noinline
func stubS34_68(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(68, recv, attrs)
}

//go:noinline
func stubS34_69(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(69, recv, attrs)
}

//go:noinline
func stubS34_70(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(70, recv, attrs)
}

//go:noinline
func stubS34_71(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(71, recv, attrs)
}

//go:noinline
func stubS34_72(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(72, recv, attrs)
}

//go:noinline
func stubS34_73(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(73, recv, attrs)
}

//go:noinline
func stubS34_74(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(74, recv, attrs)
}

//go:noinline
func stubS34_75(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(75, recv, attrs)
}

//go:noinline
func stubS34_76(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(76, recv, attrs)
}

//go:noinline
func stubS34_77(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(77, recv, attrs)
}

//go:noinline
func stubS34_78(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(78, recv, attrs)
}

//go:noinline
func stubS34_79(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(79, recv, attrs)
}

//go:noinline
func stubS34_80(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(80, recv, attrs)
}

//go:noinline
func stubS34_81(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(81, recv, attrs)
}

//go:noinline
func stubS34_82(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(82, recv, attrs)
}

//go:noinline
func stubS34_83(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(83, recv, attrs)
}

//go:noinline
func stubS34_84(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(84, recv, attrs)
}

//go:noinline
func stubS34_85(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(85, recv, attrs)
}

//go:noinline
func stubS34_86(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(86, recv, attrs)
}

//go:noinline
func stubS34_87(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(87, recv, attrs)
}

//go:noinline
func stubS34_88(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(88, recv, attrs)
}

//go:noinline
func stubS34_89(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(89, recv, attrs)
}

//go:noinline
func stubS34_90(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(90, recv, attrs)
}

//go:noinline
func stubS34_91(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(91, recv, attrs)
}

//go:noinline
func stubS34_92(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(92, recv, attrs)
}

//go:noinline
func stubS34_93(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(93, recv, attrs)
}

//go:noinline
func stubS34_94(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(94, recv, attrs)
}

//go:noinline
func stubS34_95(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(95, recv, attrs)
}

//go:noinline
func stubS34_96(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(96, recv, attrs)
}

//go:noinline
func stubS34_97(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(97, recv, attrs)
}

//go:noinline
func stubS34_98(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(98, recv, attrs)
}

//go:noinline
func stubS34_99(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(99, recv, attrs)
}

//go:noinline
func stubS34_100(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(100, recv, attrs)
}

//go:noinline
func stubS34_101(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(101, recv, attrs)
}

//go:noinline
func stubS34_102(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(102, recv, attrs)
}

//go:noinline
func stubS34_103(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(103, recv, attrs)
}

//go:noinline
func stubS34_104(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(104, recv, attrs)
}

//go:noinline
func stubS34_105(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(105, recv, attrs)
}

//go:noinline
func stubS34_106(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(106, recv, attrs)
}

//go:noinline
func stubS34_107(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(107, recv, attrs)
}

//go:noinline
func stubS34_108(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(108, recv, attrs)
}

//go:noinline
func stubS34_109(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(109, recv, attrs)
}

//go:noinline
func stubS34_110(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(110, recv, attrs)
}

//go:noinline
func stubS34_111(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(111, recv, attrs)
}

//go:noinline
func stubS34_112(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(112, recv, attrs)
}

//go:noinline
func stubS34_113(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(113, recv, attrs)
}

//go:noinline
func stubS34_114(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(114, recv, attrs)
}

//go:noinline
func stubS34_115(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(115, recv, attrs)
}

//go:noinline
func stubS34_116(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(116, recv, attrs)
}

//go:noinline
func stubS34_117(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(117, recv, attrs)
}

//go:noinline
func stubS34_118(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(118, recv, attrs)
}

//go:noinline
func stubS34_119(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(119, recv, attrs)
}

//go:noinline
func stubS34_120(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(120, recv, attrs)
}

//go:noinline
func stubS34_121(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(121, recv, attrs)
}

//go:noinline
func stubS34_122(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(122, recv, attrs)
}

//go:noinline
func stubS34_123(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(123, recv, attrs)
}

//go:noinline
func stubS34_124(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(124, recv, attrs)
}

//go:noinline
func stubS34_125(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(125, recv, attrs)
}

//go:noinline
func stubS34_126(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(126, recv, attrs)
}

//go:noinline
func stubS34_127(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(127, recv, attrs)
}

//go:noinline
func stubS34_128(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(128, recv, attrs)
}

//go:noinline
func stubS34_129(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(129, recv, attrs)
}

//go:noinline
func stubS34_130(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(130, recv, attrs)
}

//go:noinline
func stubS34_131(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(131, recv, attrs)
}

//go:noinline
func stubS34_132(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(132, recv, attrs)
}

//go:noinline
func stubS34_133(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(133, recv, attrs)
}

//go:noinline
func stubS34_134(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(134, recv, attrs)
}

//go:noinline
func stubS34_135(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(135, recv, attrs)
}

//go:noinline
func stubS34_136(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(136, recv, attrs)
}

//go:noinline
func stubS34_137(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(137, recv, attrs)
}

//go:noinline
func stubS34_138(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(138, recv, attrs)
}

//go:noinline
func stubS34_139(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(139, recv, attrs)
}

//go:noinline
func stubS34_140(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(140, recv, attrs)
}

//go:noinline
func stubS34_141(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(141, recv, attrs)
}

//go:noinline
func stubS34_142(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(142, recv, attrs)
}

//go:noinline
func stubS34_143(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(143, recv, attrs)
}

//go:noinline
func stubS34_144(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(144, recv, attrs)
}

//go:noinline
func stubS34_145(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(145, recv, attrs)
}

//go:noinline
func stubS34_146(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(146, recv, attrs)
}

//go:noinline
func stubS34_147(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(147, recv, attrs)
}

//go:noinline
func stubS34_148(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(148, recv, attrs)
}

//go:noinline
func stubS34_149(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(149, recv, attrs)
}

//go:noinline
func stubS34_150(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(150, recv, attrs)
}

//go:noinline
func stubS34_151(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(151, recv, attrs)
}

//go:noinline
func stubS34_152(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(152, recv, attrs)
}

//go:noinline
func stubS34_153(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(153, recv, attrs)
}

//go:noinline
func stubS34_154(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(154, recv, attrs)
}

//go:noinline
func stubS34_155(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(155, recv, attrs)
}

//go:noinline
func stubS34_156(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(156, recv, attrs)
}

//go:noinline
func stubS34_157(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(157, recv, attrs)
}

//go:noinline
func stubS34_158(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(158, recv, attrs)
}

//go:noinline
func stubS34_159(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(159, recv, attrs)
}

//go:noinline
func stubS34_160(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(160, recv, attrs)
}

//go:noinline
func stubS34_161(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(161, recv, attrs)
}

//go:noinline
func stubS34_162(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(162, recv, attrs)
}

//go:noinline
func stubS34_163(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(163, recv, attrs)
}

//go:noinline
func stubS34_164(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(164, recv, attrs)
}

//go:noinline
func stubS34_165(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(165, recv, attrs)
}

//go:noinline
func stubS34_166(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(166, recv, attrs)
}

//go:noinline
func stubS34_167(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(167, recv, attrs)
}

//go:noinline
func stubS34_168(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(168, recv, attrs)
}

//go:noinline
func stubS34_169(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(169, recv, attrs)
}

//go:noinline
func stubS34_170(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(170, recv, attrs)
}

//go:noinline
func stubS34_171(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(171, recv, attrs)
}

//go:noinline
func stubS34_172(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(172, recv, attrs)
}

//go:noinline
func stubS34_173(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(173, recv, attrs)
}

//go:noinline
func stubS34_174(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(174, recv, attrs)
}

//go:noinline
func stubS34_175(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(175, recv, attrs)
}

//go:noinline
func stubS34_176(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(176, recv, attrs)
}

//go:noinline
func stubS34_177(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(177, recv, attrs)
}

//go:noinline
func stubS34_178(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(178, recv, attrs)
}

//go:noinline
func stubS34_179(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(179, recv, attrs)
}

//go:noinline
func stubS34_180(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(180, recv, attrs)
}

//go:noinline
func stubS34_181(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(181, recv, attrs)
}

//go:noinline
func stubS34_182(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(182, recv, attrs)
}

//go:noinline
func stubS34_183(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(183, recv, attrs)
}

//go:noinline
func stubS34_184(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(184, recv, attrs)
}

//go:noinline
func stubS34_185(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(185, recv, attrs)
}

//go:noinline
func stubS34_186(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(186, recv, attrs)
}

//go:noinline
func stubS34_187(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(187, recv, attrs)
}

//go:noinline
func stubS34_188(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(188, recv, attrs)
}

//go:noinline
func stubS34_189(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(189, recv, attrs)
}

//go:noinline
func stubS34_190(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(190, recv, attrs)
}

//go:noinline
func stubS34_191(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(191, recv, attrs)
}

//go:noinline
func stubS34_192(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(192, recv, attrs)
}

//go:noinline
func stubS34_193(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(193, recv, attrs)
}

//go:noinline
func stubS34_194(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(194, recv, attrs)
}

//go:noinline
func stubS34_195(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(195, recv, attrs)
}

//go:noinline
func stubS34_196(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(196, recv, attrs)
}

//go:noinline
func stubS34_197(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(197, recv, attrs)
}

//go:noinline
func stubS34_198(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(198, recv, attrs)
}

//go:noinline
func stubS34_199(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(199, recv, attrs)
}

//go:noinline
func stubS34_200(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(200, recv, attrs)
}

//go:noinline
func stubS34_201(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(201, recv, attrs)
}

//go:noinline
func stubS34_202(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(202, recv, attrs)
}

//go:noinline
func stubS34_203(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(203, recv, attrs)
}

//go:noinline
func stubS34_204(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(204, recv, attrs)
}

//go:noinline
func stubS34_205(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(205, recv, attrs)
}

//go:noinline
func stubS34_206(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(206, recv, attrs)
}

//go:noinline
func stubS34_207(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(207, recv, attrs)
}

//go:noinline
func stubS34_208(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(208, recv, attrs)
}

//go:noinline
func stubS34_209(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(209, recv, attrs)
}

//go:noinline
func stubS34_210(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(210, recv, attrs)
}

//go:noinline
func stubS34_211(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(211, recv, attrs)
}

//go:noinline
func stubS34_212(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(212, recv, attrs)
}

//go:noinline
func stubS34_213(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(213, recv, attrs)
}

//go:noinline
func stubS34_214(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(214, recv, attrs)
}

//go:noinline
func stubS34_215(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(215, recv, attrs)
}

//go:noinline
func stubS34_216(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(216, recv, attrs)
}

//go:noinline
func stubS34_217(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(217, recv, attrs)
}

//go:noinline
func stubS34_218(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(218, recv, attrs)
}

//go:noinline
func stubS34_219(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(219, recv, attrs)
}

//go:noinline
func stubS34_220(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(220, recv, attrs)
}

//go:noinline
func stubS34_221(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(221, recv, attrs)
}

//go:noinline
func stubS34_222(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(222, recv, attrs)
}

//go:noinline
func stubS34_223(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(223, recv, attrs)
}

//go:noinline
func stubS34_224(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(224, recv, attrs)
}

//go:noinline
func stubS34_225(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(225, recv, attrs)
}

//go:noinline
func stubS34_226(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(226, recv, attrs)
}

//go:noinline
func stubS34_227(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(227, recv, attrs)
}

//go:noinline
func stubS34_228(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(228, recv, attrs)
}

//go:noinline
func stubS34_229(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(229, recv, attrs)
}

//go:noinline
func stubS34_230(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(230, recv, attrs)
}

//go:noinline
func stubS34_231(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(231, recv, attrs)
}

//go:noinline
func stubS34_232(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(232, recv, attrs)
}

//go:noinline
func stubS34_233(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(233, recv, attrs)
}

//go:noinline
func stubS34_234(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(234, recv, attrs)
}

//go:noinline
func stubS34_235(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(235, recv, attrs)
}

//go:noinline
func stubS34_236(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(236, recv, attrs)
}

//go:noinline
func stubS34_237(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(237, recv, attrs)
}

//go:noinline
func stubS34_238(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(238, recv, attrs)
}

//go:noinline
func stubS34_239(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(239, recv, attrs)
}

//go:noinline
func stubS34_240(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(240, recv, attrs)
}

//go:noinline
func stubS34_241(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(241, recv, attrs)
}

//go:noinline
func stubS34_242(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(242, recv, attrs)
}

//go:noinline
func stubS34_243(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(243, recv, attrs)
}

//go:noinline
func stubS34_244(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(244, recv, attrs)
}

//go:noinline
func stubS34_245(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(245, recv, attrs)
}

//go:noinline
func stubS34_246(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(246, recv, attrs)
}

//go:noinline
func stubS34_247(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(247, recv, attrs)
}

//go:noinline
func stubS34_248(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(248, recv, attrs)
}

//go:noinline
func stubS34_249(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(249, recv, attrs)
}

//go:noinline
func stubS34_250(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(250, recv, attrs)
}

//go:noinline
func stubS34_251(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(251, recv, attrs)
}

//go:noinline
func stubS34_252(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(252, recv, attrs)
}

//go:noinline
func stubS34_253(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(253, recv, attrs)
}

//go:noinline
func stubS34_254(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(254, recv, attrs)
}

//go:noinline
func stubS34_255(recv unsafe.Pointer, attrs []slog.Attr) slog.Handler {
	return dispatchS34(255, recv, attrs)
}

var stubsS34 = [poolSizeS34]uintptr{
	runtype.FuncPC(stubS34_0),
	runtype.FuncPC(stubS34_1),
	runtype.FuncPC(stubS34_2),
	runtype.FuncPC(stubS34_3),
	runtype.FuncPC(stubS34_4),
	runtype.FuncPC(stubS34_5),
	runtype.FuncPC(stubS34_6),
	runtype.FuncPC(stubS34_7),
	runtype.FuncPC(stubS34_8),
	runtype.FuncPC(stubS34_9),
	runtype.FuncPC(stubS34_10),
	runtype.FuncPC(stubS34_11),
	runtype.FuncPC(stubS34_12),
	runtype.FuncPC(stubS34_13),
	runtype.FuncPC(stubS34_14),
	runtype.FuncPC(stubS34_15),
	runtype.FuncPC(stubS34_16),
	runtype.FuncPC(stubS34_17),
	runtype.FuncPC(stubS34_18),
	runtype.FuncPC(stubS34_19),
	runtype.FuncPC(stubS34_20),
	runtype.FuncPC(stubS34_21),
	runtype.FuncPC(stubS34_22),
	runtype.FuncPC(stubS34_23),
	runtype.FuncPC(stubS34_24),
	runtype.FuncPC(stubS34_25),
	runtype.FuncPC(stubS34_26),
	runtype.FuncPC(stubS34_27),
	runtype.FuncPC(stubS34_28),
	runtype.FuncPC(stubS34_29),
	runtype.FuncPC(stubS34_30),
	runtype.FuncPC(stubS34_31),
	runtype.FuncPC(stubS34_32),
	runtype.FuncPC(stubS34_33),
	runtype.FuncPC(stubS34_34),
	runtype.FuncPC(stubS34_35),
	runtype.FuncPC(stubS34_36),
	runtype.FuncPC(stubS34_37),
	runtype.FuncPC(stubS34_38),
	runtype.FuncPC(stubS34_39),
	runtype.FuncPC(stubS34_40),
	runtype.FuncPC(stubS34_41),
	runtype.FuncPC(stubS34_42),
	runtype.FuncPC(stubS34_43),
	runtype.FuncPC(stubS34_44),
	runtype.FuncPC(stubS34_45),
	runtype.FuncPC(stubS34_46),
	runtype.FuncPC(stubS34_47),
	runtype.FuncPC(stubS34_48),
	runtype.FuncPC(stubS34_49),
	runtype.FuncPC(stubS34_50),
	runtype.FuncPC(stubS34_51),
	runtype.FuncPC(stubS34_52),
	runtype.FuncPC(stubS34_53),
	runtype.FuncPC(stubS34_54),
	runtype.FuncPC(stubS34_55),
	runtype.FuncPC(stubS34_56),
	runtype.FuncPC(stubS34_57),
	runtype.FuncPC(stubS34_58),
	runtype.FuncPC(stubS34_59),
	runtype.FuncPC(stubS34_60),
	runtype.FuncPC(stubS34_61),
	runtype.FuncPC(stubS34_62),
	runtype.FuncPC(stubS34_63),
	runtype.FuncPC(stubS34_64),
	runtype.FuncPC(stubS34_65),
	runtype.FuncPC(stubS34_66),
	runtype.FuncPC(stubS34_67),
	runtype.FuncPC(stubS34_68),
	runtype.FuncPC(stubS34_69),
	runtype.FuncPC(stubS34_70),
	runtype.FuncPC(stubS34_71),
	runtype.FuncPC(stubS34_72),
	runtype.FuncPC(stubS34_73),
	runtype.FuncPC(stubS34_74),
	runtype.FuncPC(stubS34_75),
	runtype.FuncPC(stubS34_76),
	runtype.FuncPC(stubS34_77),
	runtype.FuncPC(stubS34_78),
	runtype.FuncPC(stubS34_79),
	runtype.FuncPC(stubS34_80),
	runtype.FuncPC(stubS34_81),
	runtype.FuncPC(stubS34_82),
	runtype.FuncPC(stubS34_83),
	runtype.FuncPC(stubS34_84),
	runtype.FuncPC(stubS34_85),
	runtype.FuncPC(stubS34_86),
	runtype.FuncPC(stubS34_87),
	runtype.FuncPC(stubS34_88),
	runtype.FuncPC(stubS34_89),
	runtype.FuncPC(stubS34_90),
	runtype.FuncPC(stubS34_91),
	runtype.FuncPC(stubS34_92),
	runtype.FuncPC(stubS34_93),
	runtype.FuncPC(stubS34_94),
	runtype.FuncPC(stubS34_95),
	runtype.FuncPC(stubS34_96),
	runtype.FuncPC(stubS34_97),
	runtype.FuncPC(stubS34_98),
	runtype.FuncPC(stubS34_99),
	runtype.FuncPC(stubS34_100),
	runtype.FuncPC(stubS34_101),
	runtype.FuncPC(stubS34_102),
	runtype.FuncPC(stubS34_103),
	runtype.FuncPC(stubS34_104),
	runtype.FuncPC(stubS34_105),
	runtype.FuncPC(stubS34_106),
	runtype.FuncPC(stubS34_107),
	runtype.FuncPC(stubS34_108),
	runtype.FuncPC(stubS34_109),
	runtype.FuncPC(stubS34_110),
	runtype.FuncPC(stubS34_111),
	runtype.FuncPC(stubS34_112),
	runtype.FuncPC(stubS34_113),
	runtype.FuncPC(stubS34_114),
	runtype.FuncPC(stubS34_115),
	runtype.FuncPC(stubS34_116),
	runtype.FuncPC(stubS34_117),
	runtype.FuncPC(stubS34_118),
	runtype.FuncPC(stubS34_119),
	runtype.FuncPC(stubS34_120),
	runtype.FuncPC(stubS34_121),
	runtype.FuncPC(stubS34_122),
	runtype.FuncPC(stubS34_123),
	runtype.FuncPC(stubS34_124),
	runtype.FuncPC(stubS34_125),
	runtype.FuncPC(stubS34_126),
	runtype.FuncPC(stubS34_127),
	runtype.FuncPC(stubS34_128),
	runtype.FuncPC(stubS34_129),
	runtype.FuncPC(stubS34_130),
	runtype.FuncPC(stubS34_131),
	runtype.FuncPC(stubS34_132),
	runtype.FuncPC(stubS34_133),
	runtype.FuncPC(stubS34_134),
	runtype.FuncPC(stubS34_135),
	runtype.FuncPC(stubS34_136),
	runtype.FuncPC(stubS34_137),
	runtype.FuncPC(stubS34_138),
	runtype.FuncPC(stubS34_139),
	runtype.FuncPC(stubS34_140),
	runtype.FuncPC(stubS34_141),
	runtype.FuncPC(stubS34_142),
	runtype.FuncPC(stubS34_143),
	runtype.FuncPC(stubS34_144),
	runtype.FuncPC(stubS34_145),
	runtype.FuncPC(stubS34_146),
	runtype.FuncPC(stubS34_147),
	runtype.FuncPC(stubS34_148),
	runtype.FuncPC(stubS34_149),
	runtype.FuncPC(stubS34_150),
	runtype.FuncPC(stubS34_151),
	runtype.FuncPC(stubS34_152),
	runtype.FuncPC(stubS34_153),
	runtype.FuncPC(stubS34_154),
	runtype.FuncPC(stubS34_155),
	runtype.FuncPC(stubS34_156),
	runtype.FuncPC(stubS34_157),
	runtype.FuncPC(stubS34_158),
	runtype.FuncPC(stubS34_159),
	runtype.FuncPC(stubS34_160),
	runtype.FuncPC(stubS34_161),
	runtype.FuncPC(stubS34_162),
	runtype.FuncPC(stubS34_163),
	runtype.FuncPC(stubS34_164),
	runtype.FuncPC(stubS34_165),
	runtype.FuncPC(stubS34_166),
	runtype.FuncPC(stubS34_167),
	runtype.FuncPC(stubS34_168),
	runtype.FuncPC(stubS34_169),
	runtype.FuncPC(stubS34_170),
	runtype.FuncPC(stubS34_171),
	runtype.FuncPC(stubS34_172),
	runtype.FuncPC(stubS34_173),
	runtype.FuncPC(stubS34_174),
	runtype.FuncPC(stubS34_175),
	runtype.FuncPC(stubS34_176),
	runtype.FuncPC(stubS34_177),
	runtype.FuncPC(stubS34_178),
	runtype.FuncPC(stubS34_179),
	runtype.FuncPC(stubS34_180),
	runtype.FuncPC(stubS34_181),
	runtype.FuncPC(stubS34_182),
	runtype.FuncPC(stubS34_183),
	runtype.FuncPC(stubS34_184),
	runtype.FuncPC(stubS34_185),
	runtype.FuncPC(stubS34_186),
	runtype.FuncPC(stubS34_187),
	runtype.FuncPC(stubS34_188),
	runtype.FuncPC(stubS34_189),
	runtype.FuncPC(stubS34_190),
	runtype.FuncPC(stubS34_191),
	runtype.FuncPC(stubS34_192),
	runtype.FuncPC(stubS34_193),
	runtype.FuncPC(stubS34_194),
	runtype.FuncPC(stubS34_195),
	runtype.FuncPC(stubS34_196),
	runtype.FuncPC(stubS34_197),
	runtype.FuncPC(stubS34_198),
	runtype.FuncPC(stubS34_199),
	runtype.FuncPC(stubS34_200),
	runtype.FuncPC(stubS34_201),
	runtype.FuncPC(stubS34_202),
	runtype.FuncPC(stubS34_203),
	runtype.FuncPC(stubS34_204),
	runtype.FuncPC(stubS34_205),
	runtype.FuncPC(stubS34_206),
	runtype.FuncPC(stubS34_207),
	runtype.FuncPC(stubS34_208),
	runtype.FuncPC(stubS34_209),
	runtype.FuncPC(stubS34_210),
	runtype.FuncPC(stubS34_211),
	runtype.FuncPC(stubS34_212),
	runtype.FuncPC(stubS34_213),
	runtype.FuncPC(stubS34_214),
	runtype.FuncPC(stubS34_215),
	runtype.FuncPC(stubS34_216),
	runtype.FuncPC(stubS34_217),
	runtype.FuncPC(stubS34_218),
	runtype.FuncPC(stubS34_219),
	runtype.FuncPC(stubS34_220),
	runtype.FuncPC(stubS34_221),
	runtype.FuncPC(stubS34_222),
	runtype.FuncPC(stubS34_223),
	runtype.FuncPC(stubS34_224),
	runtype.FuncPC(stubS34_225),
	runtype.FuncPC(stubS34_226),
	runtype.FuncPC(stubS34_227),
	runtype.FuncPC(stubS34_228),
	runtype.FuncPC(stubS34_229),
	runtype.FuncPC(stubS34_230),
	runtype.FuncPC(stubS34_231),
	runtype.FuncPC(stubS34_232),
	runtype.FuncPC(stubS34_233),
	runtype.FuncPC(stubS34_234),
	runtype.FuncPC(stubS34_235),
	runtype.FuncPC(stubS34_236),
	runtype.FuncPC(stubS34_237),
	runtype.FuncPC(stubS34_238),
	runtype.FuncPC(stubS34_239),
	runtype.FuncPC(stubS34_240),
	runtype.FuncPC(stubS34_241),
	runtype.FuncPC(stubS34_242),
	runtype.FuncPC(stubS34_243),
	runtype.FuncPC(stubS34_244),
	runtype.FuncPC(stubS34_245),
	runtype.FuncPC(stubS34_246),
	runtype.FuncPC(stubS34_247),
	runtype.FuncPC(stubS34_248),
	runtype.FuncPC(stubS34_249),
	runtype.FuncPC(stubS34_250),
	runtype.FuncPC(stubS34_251),
	runtype.FuncPC(stubS34_252),
	runtype.FuncPC(stubS34_253),
	runtype.FuncPC(stubS34_254),
	runtype.FuncPC(stubS34_255),
}
