// Code generated by gen_pools.go; DO NOT EDIT.
// Shape S32 pool: 256 slots.

package stubs

import (
	"context"
	"log/slog"
	"unsafe"

	"github.com/mvm-sh/mvm/runtype"
)

const poolSizeS32 = 256

//go:noinline
func stubS32_0(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(0, recv, ctx, level)
}

//go:noinline
func stubS32_1(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(1, recv, ctx, level)
}

//go:noinline
func stubS32_2(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(2, recv, ctx, level)
}

//go:noinline
func stubS32_3(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(3, recv, ctx, level)
}

//go:noinline
func stubS32_4(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(4, recv, ctx, level)
}

//go:noinline
func stubS32_5(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(5, recv, ctx, level)
}

//go:noinline
func stubS32_6(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(6, recv, ctx, level)
}

//go:noinline
func stubS32_7(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(7, recv, ctx, level)
}

//go:noinline
func stubS32_8(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(8, recv, ctx, level)
}

//go:noinline
func stubS32_9(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(9, recv, ctx, level)
}

//go:noinline
func stubS32_10(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(10, recv, ctx, level)
}

//go:noinline
func stubS32_11(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(11, recv, ctx, level)
}

//go:noinline
func stubS32_12(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(12, recv, ctx, level)
}

//go:noinline
func stubS32_13(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(13, recv, ctx, level)
}

//go:noinline
func stubS32_14(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(14, recv, ctx, level)
}

//go:noinline
func stubS32_15(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(15, recv, ctx, level)
}

//go:noinline
func stubS32_16(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(16, recv, ctx, level)
}

//go:noinline
func stubS32_17(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(17, recv, ctx, level)
}

//go:noinline
func stubS32_18(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(18, recv, ctx, level)
}

//go:noinline
func stubS32_19(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(19, recv, ctx, level)
}

//go:noinline
func stubS32_20(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(20, recv, ctx, level)
}

//go:noinline
func stubS32_21(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(21, recv, ctx, level)
}

//go:noinline
func stubS32_22(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(22, recv, ctx, level)
}

//go:noinline
func stubS32_23(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(23, recv, ctx, level)
}

//go:noinline
func stubS32_24(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(24, recv, ctx, level)
}

//go:noinline
func stubS32_25(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(25, recv, ctx, level)
}

//go:noinline
func stubS32_26(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(26, recv, ctx, level)
}

//go:noinline
func stubS32_27(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(27, recv, ctx, level)
}

//go:noinline
func stubS32_28(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(28, recv, ctx, level)
}

//go:noinline
func stubS32_29(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(29, recv, ctx, level)
}

//go:noinline
func stubS32_30(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(30, recv, ctx, level)
}

//go:noinline
func stubS32_31(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(31, recv, ctx, level)
}

//go:noinline
func stubS32_32(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(32, recv, ctx, level)
}

//go:noinline
func stubS32_33(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(33, recv, ctx, level)
}

//go:noinline
func stubS32_34(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(34, recv, ctx, level)
}

//go:noinline
func stubS32_35(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(35, recv, ctx, level)
}

//go:noinline
func stubS32_36(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(36, recv, ctx, level)
}

//go:noinline
func stubS32_37(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(37, recv, ctx, level)
}

//go:noinline
func stubS32_38(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(38, recv, ctx, level)
}

//go:noinline
func stubS32_39(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(39, recv, ctx, level)
}

//go:noinline
func stubS32_40(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(40, recv, ctx, level)
}

//go:noinline
func stubS32_41(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(41, recv, ctx, level)
}

//go:noinline
func stubS32_42(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(42, recv, ctx, level)
}

//go:noinline
func stubS32_43(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(43, recv, ctx, level)
}

//go:noinline
func stubS32_44(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(44, recv, ctx, level)
}

//go:noinline
func stubS32_45(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(45, recv, ctx, level)
}

//go:noinline
func stubS32_46(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(46, recv, ctx, level)
}

//go:noinline
func stubS32_47(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(47, recv, ctx, level)
}

//go:noinline
func stubS32_48(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(48, recv, ctx, level)
}

//go:noinline
func stubS32_49(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(49, recv, ctx, level)
}

//go:noinline
func stubS32_50(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(50, recv, ctx, level)
}

//go:noinline
func stubS32_51(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(51, recv, ctx, level)
}

//go:noinline
func stubS32_52(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(52, recv, ctx, level)
}

//go:noinline
func stubS32_53(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(53, recv, ctx, level)
}

//go:noinline
func stubS32_54(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(54, recv, ctx, level)
}

//go:noinline
func stubS32_55(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(55, recv, ctx, level)
}

//go:noinline
func stubS32_56(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(56, recv, ctx, level)
}

//go:noinline
func stubS32_57(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(57, recv, ctx, level)
}

//go:noinline
func stubS32_58(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(58, recv, ctx, level)
}

//go:noinline
func stubS32_59(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(59, recv, ctx, level)
}

//go:noinline
func stubS32_60(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(60, recv, ctx, level)
}

//go:noinline
func stubS32_61(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(61, recv, ctx, level)
}

//go:noinline
func stubS32_62(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(62, recv, ctx, level)
}

//go:noinline
func stubS32_63(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(63, recv, ctx, level)
}

//go:noinline
func stubS32_64(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(64, recv, ctx, level)
}

//go:noinline
func stubS32_65(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(65, recv, ctx, level)
}

//go:noinline
func stubS32_66(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(66, recv, ctx, level)
}

//go:noinline
func stubS32_67(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(67, recv, ctx, level)
}

//go:noinline
func stubS32_68(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(68, recv, ctx, level)
}

//go:noinline
func stubS32_69(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(69, recv, ctx, level)
}

//go:noinline
func stubS32_70(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(70, recv, ctx, level)
}

//go:noinline
func stubS32_71(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(71, recv, ctx, level)
}

//go:noinline
func stubS32_72(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(72, recv, ctx, level)
}

//go:noinline
func stubS32_73(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(73, recv, ctx, level)
}

//go:noinline
func stubS32_74(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(74, recv, ctx, level)
}

//go:noinline
func stubS32_75(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(75, recv, ctx, level)
}

//go:noinline
func stubS32_76(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(76, recv, ctx, level)
}

//go:noinline
func stubS32_77(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(77, recv, ctx, level)
}

//go:noinline
func stubS32_78(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(78, recv, ctx, level)
}

//go:noinline
func stubS32_79(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(79, recv, ctx, level)
}

//go:noinline
func stubS32_80(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(80, recv, ctx, level)
}

//go:noinline
func stubS32_81(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(81, recv, ctx, level)
}

//go:noinline
func stubS32_82(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(82, recv, ctx, level)
}

//go:noinline
func stubS32_83(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(83, recv, ctx, level)
}

//go:noinline
func stubS32_84(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(84, recv, ctx, level)
}

//go:noinline
func stubS32_85(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(85, recv, ctx, level)
}

//go:noinline
func stubS32_86(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(86, recv, ctx, level)
}

//go:noinline
func stubS32_87(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(87, recv, ctx, level)
}

//go:noinline
func stubS32_88(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(88, recv, ctx, level)
}

//go:noinline
func stubS32_89(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(89, recv, ctx, level)
}

//go:noinline
func stubS32_90(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(90, recv, ctx, level)
}

//go:noinline
func stubS32_91(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(91, recv, ctx, level)
}

//go:noinline
func stubS32_92(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(92, recv, ctx, level)
}

//go:noinline
func stubS32_93(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(93, recv, ctx, level)
}

//go:noinline
func stubS32_94(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(94, recv, ctx, level)
}

//go:noinline
func stubS32_95(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(95, recv, ctx, level)
}

//go:noinline
func stubS32_96(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(96, recv, ctx, level)
}

//go:noinline
func stubS32_97(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(97, recv, ctx, level)
}

//go:noinline
func stubS32_98(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(98, recv, ctx, level)
}

//go:noinline
func stubS32_99(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(99, recv, ctx, level)
}

//go:noinline
func stubS32_100(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(100, recv, ctx, level)
}

//go:noinline
func stubS32_101(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(101, recv, ctx, level)
}

//go:noinline
func stubS32_102(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(102, recv, ctx, level)
}

//go:noinline
func stubS32_103(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(103, recv, ctx, level)
}

//go:noinline
func stubS32_104(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(104, recv, ctx, level)
}

//go:noinline
func stubS32_105(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(105, recv, ctx, level)
}

//go:noinline
func stubS32_106(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(106, recv, ctx, level)
}

//go:noinline
func stubS32_107(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(107, recv, ctx, level)
}

//go:noinline
func stubS32_108(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(108, recv, ctx, level)
}

//go:noinline
func stubS32_109(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(109, recv, ctx, level)
}

//go:noinline
func stubS32_110(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(110, recv, ctx, level)
}

//go:noinline
func stubS32_111(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(111, recv, ctx, level)
}

//go:noinline
func stubS32_112(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(112, recv, ctx, level)
}

//go:noinline
func stubS32_113(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(113, recv, ctx, level)
}

//go:noinline
func stubS32_114(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(114, recv, ctx, level)
}

//go:noinline
func stubS32_115(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(115, recv, ctx, level)
}

//go:noinline
func stubS32_116(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(116, recv, ctx, level)
}

//go:noinline
func stubS32_117(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(117, recv, ctx, level)
}

//go:noinline
func stubS32_118(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(118, recv, ctx, level)
}

//go:noinline
func stubS32_119(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(119, recv, ctx, level)
}

//go:noinline
func stubS32_120(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(120, recv, ctx, level)
}

//go:noinline
func stubS32_121(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(121, recv, ctx, level)
}

//go:noinline
func stubS32_122(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(122, recv, ctx, level)
}

//go:noinline
func stubS32_123(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(123, recv, ctx, level)
}

//go:noinline
func stubS32_124(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(124, recv, ctx, level)
}

//go:noinline
func stubS32_125(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(125, recv, ctx, level)
}

//go:noinline
func stubS32_126(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(126, recv, ctx, level)
}

//go:noinline
func stubS32_127(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(127, recv, ctx, level)
}

//go:noinline
func stubS32_128(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(128, recv, ctx, level)
}

//go:noinline
func stubS32_129(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(129, recv, ctx, level)
}

//go:noinline
func stubS32_130(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(130, recv, ctx, level)
}

//go:noinline
func stubS32_131(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(131, recv, ctx, level)
}

//go:noinline
func stubS32_132(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(132, recv, ctx, level)
}

//go:noinline
func stubS32_133(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(133, recv, ctx, level)
}

//go:noinline
func stubS32_134(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(134, recv, ctx, level)
}

//go:noinline
func stubS32_135(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(135, recv, ctx, level)
}

//go:noinline
func stubS32_136(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(136, recv, ctx, level)
}

//go:noinline
func stubS32_137(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(137, recv, ctx, level)
}

//go:noinline
func stubS32_138(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(138, recv, ctx, level)
}

//go:noinline
func stubS32_139(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(139, recv, ctx, level)
}

//go:noinline
func stubS32_140(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(140, recv, ctx, level)
}

//go:noinline
func stubS32_141(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(141, recv, ctx, level)
}

//go:noinline
func stubS32_142(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(142, recv, ctx, level)
}

//go:noinline
func stubS32_143(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(143, recv, ctx, level)
}

//go:noinline
func stubS32_144(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(144, recv, ctx, level)
}

//go:noinline
func stubS32_145(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(145, recv, ctx, level)
}

//go:noinline
func stubS32_146(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(146, recv, ctx, level)
}

//go:noinline
func stubS32_147(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(147, recv, ctx, level)
}

//go:noinline
func stubS32_148(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(148, recv, ctx, level)
}

//go:noinline
func stubS32_149(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(149, recv, ctx, level)
}

//go:noinline
func stubS32_150(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(150, recv, ctx, level)
}

//go:noinline
func stubS32_151(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(151, recv, ctx, level)
}

//go:noinline
func stubS32_152(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(152, recv, ctx, level)
}

//go:noinline
func stubS32_153(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(153, recv, ctx, level)
}

//go:noinline
func stubS32_154(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(154, recv, ctx, level)
}

//go:noinline
func stubS32_155(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(155, recv, ctx, level)
}

//go:noinline
func stubS32_156(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(156, recv, ctx, level)
}

//go:noinline
func stubS32_157(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(157, recv, ctx, level)
}

//go:noinline
func stubS32_158(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(158, recv, ctx, level)
}

//go:noinline
func stubS32_159(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(159, recv, ctx, level)
}

//go:noinline
func stubS32_160(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(160, recv, ctx, level)
}

//go:noinline
func stubS32_161(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(161, recv, ctx, level)
}

//go:noinline
func stubS32_162(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(162, recv, ctx, level)
}

//go:noinline
func stubS32_163(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(163, recv, ctx, level)
}

//go:noinline
func stubS32_164(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(164, recv, ctx, level)
}

//go:noinline
func stubS32_165(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(165, recv, ctx, level)
}

//go:noinline
func stubS32_166(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(166, recv, ctx, level)
}

//go:noinline
func stubS32_167(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(167, recv, ctx, level)
}

//go:noinline
func stubS32_168(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(168, recv, ctx, level)
}

//go:noinline
func stubS32_169(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(169, recv, ctx, level)
}

//go:noinline
func stubS32_170(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(170, recv, ctx, level)
}

//go:noinline
func stubS32_171(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(171, recv, ctx, level)
}

//go:noinline
func stubS32_172(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(172, recv, ctx, level)
}

//go:noinline
func stubS32_173(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(173, recv, ctx, level)
}

//go:noinline
func stubS32_174(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(174, recv, ctx, level)
}

//go:noinline
func stubS32_175(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(175, recv, ctx, level)
}

//go:noinline
func stubS32_176(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(176, recv, ctx, level)
}

//go:noinline
func stubS32_177(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(177, recv, ctx, level)
}

//go:noinline
func stubS32_178(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(178, recv, ctx, level)
}

//go:noinline
func stubS32_179(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(179, recv, ctx, level)
}

//go:noinline
func stubS32_180(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(180, recv, ctx, level)
}

//go:noinline
func stubS32_181(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(181, recv, ctx, level)
}

//go:noinline
func stubS32_182(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(182, recv, ctx, level)
}

//go:noinline
func stubS32_183(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(183, recv, ctx, level)
}

//go:noinline
func stubS32_184(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(184, recv, ctx, level)
}

//go:noinline
func stubS32_185(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(185, recv, ctx, level)
}

//go:noinline
func stubS32_186(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(186, recv, ctx, level)
}

//go:noinline
func stubS32_187(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(187, recv, ctx, level)
}

//go:noinline
func stubS32_188(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(188, recv, ctx, level)
}

//go:noinline
func stubS32_189(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(189, recv, ctx, level)
}

//go:noinline
func stubS32_190(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(190, recv, ctx, level)
}

//go:noinline
func stubS32_191(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(191, recv, ctx, level)
}

//go:noinline
func stubS32_192(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(192, recv, ctx, level)
}

//go:noinline
func stubS32_193(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(193, recv, ctx, level)
}

//go:noinline
func stubS32_194(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(194, recv, ctx, level)
}

//go:noinline
func stubS32_195(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(195, recv, ctx, level)
}

//go:noinline
func stubS32_196(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(196, recv, ctx, level)
}

//go:noinline
func stubS32_197(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(197, recv, ctx, level)
}

//go:noinline
func stubS32_198(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(198, recv, ctx, level)
}

//go:noinline
func stubS32_199(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(199, recv, ctx, level)
}

//go:noinline
func stubS32_200(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(200, recv, ctx, level)
}

//go:noinline
func stubS32_201(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(201, recv, ctx, level)
}

//go:noinline
func stubS32_202(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(202, recv, ctx, level)
}

//go:noinline
func stubS32_203(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(203, recv, ctx, level)
}

//go:noinline
func stubS32_204(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(204, recv, ctx, level)
}

//go:noinline
func stubS32_205(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(205, recv, ctx, level)
}

//go:noinline
func stubS32_206(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(206, recv, ctx, level)
}

//go:noinline
func stubS32_207(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(207, recv, ctx, level)
}

//go:noinline
func stubS32_208(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(208, recv, ctx, level)
}

//go:noinline
func stubS32_209(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(209, recv, ctx, level)
}

//go:noinline
func stubS32_210(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(210, recv, ctx, level)
}

//go:noinline
func stubS32_211(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(211, recv, ctx, level)
}

//go:noinline
func stubS32_212(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(212, recv, ctx, level)
}

//go:noinline
func stubS32_213(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(213, recv, ctx, level)
}

//go:noinline
func stubS32_214(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(214, recv, ctx, level)
}

//go:noinline
func stubS32_215(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(215, recv, ctx, level)
}

//go:noinline
func stubS32_216(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(216, recv, ctx, level)
}

//go:noinline
func stubS32_217(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(217, recv, ctx, level)
}

//go:noinline
func stubS32_218(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(218, recv, ctx, level)
}

//go:noinline
func stubS32_219(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(219, recv, ctx, level)
}

//go:noinline
func stubS32_220(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(220, recv, ctx, level)
}

//go:noinline
func stubS32_221(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(221, recv, ctx, level)
}

//go:noinline
func stubS32_222(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(222, recv, ctx, level)
}

//go:noinline
func stubS32_223(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(223, recv, ctx, level)
}

//go:noinline
func stubS32_224(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(224, recv, ctx, level)
}

//go:noinline
func stubS32_225(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(225, recv, ctx, level)
}

//go:noinline
func stubS32_226(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(226, recv, ctx, level)
}

//go:noinline
func stubS32_227(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(227, recv, ctx, level)
}

//go:noinline
func stubS32_228(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(228, recv, ctx, level)
}

//go:noinline
func stubS32_229(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(229, recv, ctx, level)
}

//go:noinline
func stubS32_230(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(230, recv, ctx, level)
}

//go:noinline
func stubS32_231(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(231, recv, ctx, level)
}

//go:noinline
func stubS32_232(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(232, recv, ctx, level)
}

//go:noinline
func stubS32_233(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(233, recv, ctx, level)
}

//go:noinline
func stubS32_234(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(234, recv, ctx, level)
}

//go:noinline
func stubS32_235(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(235, recv, ctx, level)
}

//go:noinline
func stubS32_236(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(236, recv, ctx, level)
}

//go:noinline
func stubS32_237(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(237, recv, ctx, level)
}

//go:noinline
func stubS32_238(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(238, recv, ctx, level)
}

//go:noinline
func stubS32_239(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(239, recv, ctx, level)
}

//go:noinline
func stubS32_240(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(240, recv, ctx, level)
}

//go:noinline
func stubS32_241(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(241, recv, ctx, level)
}

//go:noinline
func stubS32_242(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(242, recv, ctx, level)
}

//go:noinline
func stubS32_243(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(243, recv, ctx, level)
}

//go:noinline
func stubS32_244(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(244, recv, ctx, level)
}

//go:noinline
func stubS32_245(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(245, recv, ctx, level)
}

//go:noinline
func stubS32_246(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(246, recv, ctx, level)
}

//go:noinline
func stubS32_247(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(247, recv, ctx, level)
}

//go:noinline
func stubS32_248(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(248, recv, ctx, level)
}

//go:noinline
func stubS32_249(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(249, recv, ctx, level)
}

//go:noinline
func stubS32_250(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(250, recv, ctx, level)
}

//go:noinline
func stubS32_251(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(251, recv, ctx, level)
}

//go:noinline
func stubS32_252(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(252, recv, ctx, level)
}

//go:noinline
func stubS32_253(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(253, recv, ctx, level)
}

//go:noinline
func stubS32_254(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(254, recv, ctx, level)
}

//go:noinline
func stubS32_255(recv unsafe.Pointer, ctx context.Context, level slog.Level) bool {
	return dispatchS32(255, recv, ctx, level)
}

var stubsS32 = [poolSizeS32]uintptr{
	runtype.FuncPC(stubS32_0),
	runtype.FuncPC(stubS32_1),
	runtype.FuncPC(stubS32_2),
	runtype.FuncPC(stubS32_3),
	runtype.FuncPC(stubS32_4),
	runtype.FuncPC(stubS32_5),
	runtype.FuncPC(stubS32_6),
	runtype.FuncPC(stubS32_7),
	runtype.FuncPC(stubS32_8),
	runtype.FuncPC(stubS32_9),
	runtype.FuncPC(stubS32_10),
	runtype.FuncPC(stubS32_11),
	runtype.FuncPC(stubS32_12),
	runtype.FuncPC(stubS32_13),
	runtype.FuncPC(stubS32_14),
	runtype.FuncPC(stubS32_15),
	runtype.FuncPC(stubS32_16),
	runtype.FuncPC(stubS32_17),
	runtype.FuncPC(stubS32_18),
	runtype.FuncPC(stubS32_19),
	runtype.FuncPC(stubS32_20),
	runtype.FuncPC(stubS32_21),
	runtype.FuncPC(stubS32_22),
	runtype.FuncPC(stubS32_23),
	runtype.FuncPC(stubS32_24),
	runtype.FuncPC(stubS32_25),
	runtype.FuncPC(stubS32_26),
	runtype.FuncPC(stubS32_27),
	runtype.FuncPC(stubS32_28),
	runtype.FuncPC(stubS32_29),
	runtype.FuncPC(stubS32_30),
	runtype.FuncPC(stubS32_31),
	runtype.FuncPC(stubS32_32),
	runtype.FuncPC(stubS32_33),
	runtype.FuncPC(stubS32_34),
	runtype.FuncPC(stubS32_35),
	runtype.FuncPC(stubS32_36),
	runtype.FuncPC(stubS32_37),
	runtype.FuncPC(stubS32_38),
	runtype.FuncPC(stubS32_39),
	runtype.FuncPC(stubS32_40),
	runtype.FuncPC(stubS32_41),
	runtype.FuncPC(stubS32_42),
	runtype.FuncPC(stubS32_43),
	runtype.FuncPC(stubS32_44),
	runtype.FuncPC(stubS32_45),
	runtype.FuncPC(stubS32_46),
	runtype.FuncPC(stubS32_47),
	runtype.FuncPC(stubS32_48),
	runtype.FuncPC(stubS32_49),
	runtype.FuncPC(stubS32_50),
	runtype.FuncPC(stubS32_51),
	runtype.FuncPC(stubS32_52),
	runtype.FuncPC(stubS32_53),
	runtype.FuncPC(stubS32_54),
	runtype.FuncPC(stubS32_55),
	runtype.FuncPC(stubS32_56),
	runtype.FuncPC(stubS32_57),
	runtype.FuncPC(stubS32_58),
	runtype.FuncPC(stubS32_59),
	runtype.FuncPC(stubS32_60),
	runtype.FuncPC(stubS32_61),
	runtype.FuncPC(stubS32_62),
	runtype.FuncPC(stubS32_63),
	runtype.FuncPC(stubS32_64),
	runtype.FuncPC(stubS32_65),
	runtype.FuncPC(stubS32_66),
	runtype.FuncPC(stubS32_67),
	runtype.FuncPC(stubS32_68),
	runtype.FuncPC(stubS32_69),
	runtype.FuncPC(stubS32_70),
	runtype.FuncPC(stubS32_71),
	runtype.FuncPC(stubS32_72),
	runtype.FuncPC(stubS32_73),
	runtype.FuncPC(stubS32_74),
	runtype.FuncPC(stubS32_75),
	runtype.FuncPC(stubS32_76),
	runtype.FuncPC(stubS32_77),
	runtype.FuncPC(stubS32_78),
	runtype.FuncPC(stubS32_79),
	runtype.FuncPC(stubS32_80),
	runtype.FuncPC(stubS32_81),
	runtype.FuncPC(stubS32_82),
	runtype.FuncPC(stubS32_83),
	runtype.FuncPC(stubS32_84),
	runtype.FuncPC(stubS32_85),
	runtype.FuncPC(stubS32_86),
	runtype.FuncPC(stubS32_87),
	runtype.FuncPC(stubS32_88),
	runtype.FuncPC(stubS32_89),
	runtype.FuncPC(stubS32_90),
	runtype.FuncPC(stubS32_91),
	runtype.FuncPC(stubS32_92),
	runtype.FuncPC(stubS32_93),
	runtype.FuncPC(stubS32_94),
	runtype.FuncPC(stubS32_95),
	runtype.FuncPC(stubS32_96),
	runtype.FuncPC(stubS32_97),
	runtype.FuncPC(stubS32_98),
	runtype.FuncPC(stubS32_99),
	runtype.FuncPC(stubS32_100),
	runtype.FuncPC(stubS32_101),
	runtype.FuncPC(stubS32_102),
	runtype.FuncPC(stubS32_103),
	runtype.FuncPC(stubS32_104),
	runtype.FuncPC(stubS32_105),
	runtype.FuncPC(stubS32_106),
	runtype.FuncPC(stubS32_107),
	runtype.FuncPC(stubS32_108),
	runtype.FuncPC(stubS32_109),
	runtype.FuncPC(stubS32_110),
	runtype.FuncPC(stubS32_111),
	runtype.FuncPC(stubS32_112),
	runtype.FuncPC(stubS32_113),
	runtype.FuncPC(stubS32_114),
	runtype.FuncPC(stubS32_115),
	runtype.FuncPC(stubS32_116),
	runtype.FuncPC(stubS32_117),
	runtype.FuncPC(stubS32_118),
	runtype.FuncPC(stubS32_119),
	runtype.FuncPC(stubS32_120),
	runtype.FuncPC(stubS32_121),
	runtype.FuncPC(stubS32_122),
	runtype.FuncPC(stubS32_123),
	runtype.FuncPC(stubS32_124),
	runtype.FuncPC(stubS32_125),
	runtype.FuncPC(stubS32_126),
	runtype.FuncPC(stubS32_127),
	runtype.FuncPC(stubS32_128),
	runtype.FuncPC(stubS32_129),
	runtype.FuncPC(stubS32_130),
	runtype.FuncPC(stubS32_131),
	runtype.FuncPC(stubS32_132),
	runtype.FuncPC(stubS32_133),
	runtype.FuncPC(stubS32_134),
	runtype.FuncPC(stubS32_135),
	runtype.FuncPC(stubS32_136),
	runtype.FuncPC(stubS32_137),
	runtype.FuncPC(stubS32_138),
	runtype.FuncPC(stubS32_139),
	runtype.FuncPC(stubS32_140),
	runtype.FuncPC(stubS32_141),
	runtype.FuncPC(stubS32_142),
	runtype.FuncPC(stubS32_143),
	runtype.FuncPC(stubS32_144),
	runtype.FuncPC(stubS32_145),
	runtype.FuncPC(stubS32_146),
	runtype.FuncPC(stubS32_147),
	runtype.FuncPC(stubS32_148),
	runtype.FuncPC(stubS32_149),
	runtype.FuncPC(stubS32_150),
	runtype.FuncPC(stubS32_151),
	runtype.FuncPC(stubS32_152),
	runtype.FuncPC(stubS32_153),
	runtype.FuncPC(stubS32_154),
	runtype.FuncPC(stubS32_155),
	runtype.FuncPC(stubS32_156),
	runtype.FuncPC(stubS32_157),
	runtype.FuncPC(stubS32_158),
	runtype.FuncPC(stubS32_159),
	runtype.FuncPC(stubS32_160),
	runtype.FuncPC(stubS32_161),
	runtype.FuncPC(stubS32_162),
	runtype.FuncPC(stubS32_163),
	runtype.FuncPC(stubS32_164),
	runtype.FuncPC(stubS32_165),
	runtype.FuncPC(stubS32_166),
	runtype.FuncPC(stubS32_167),
	runtype.FuncPC(stubS32_168),
	runtype.FuncPC(stubS32_169),
	runtype.FuncPC(stubS32_170),
	runtype.FuncPC(stubS32_171),
	runtype.FuncPC(stubS32_172),
	runtype.FuncPC(stubS32_173),
	runtype.FuncPC(stubS32_174),
	runtype.FuncPC(stubS32_175),
	runtype.FuncPC(stubS32_176),
	runtype.FuncPC(stubS32_177),
	runtype.FuncPC(stubS32_178),
	runtype.FuncPC(stubS32_179),
	runtype.FuncPC(stubS32_180),
	runtype.FuncPC(stubS32_181),
	runtype.FuncPC(stubS32_182),
	runtype.FuncPC(stubS32_183),
	runtype.FuncPC(stubS32_184),
	runtype.FuncPC(stubS32_185),
	runtype.FuncPC(stubS32_186),
	runtype.FuncPC(stubS32_187),
	runtype.FuncPC(stubS32_188),
	runtype.FuncPC(stubS32_189),
	runtype.FuncPC(stubS32_190),
	runtype.FuncPC(stubS32_191),
	runtype.FuncPC(stubS32_192),
	runtype.FuncPC(stubS32_193),
	runtype.FuncPC(stubS32_194),
	runtype.FuncPC(stubS32_195),
	runtype.FuncPC(stubS32_196),
	runtype.FuncPC(stubS32_197),
	runtype.FuncPC(stubS32_198),
	runtype.FuncPC(stubS32_199),
	runtype.FuncPC(stubS32_200),
	runtype.FuncPC(stubS32_201),
	runtype.FuncPC(stubS32_202),
	runtype.FuncPC(stubS32_203),
	runtype.FuncPC(stubS32_204),
	runtype.FuncPC(stubS32_205),
	runtype.FuncPC(stubS32_206),
	runtype.FuncPC(stubS32_207),
	runtype.FuncPC(stubS32_208),
	runtype.FuncPC(stubS32_209),
	runtype.FuncPC(stubS32_210),
	runtype.FuncPC(stubS32_211),
	runtype.FuncPC(stubS32_212),
	runtype.FuncPC(stubS32_213),
	runtype.FuncPC(stubS32_214),
	runtype.FuncPC(stubS32_215),
	runtype.FuncPC(stubS32_216),
	runtype.FuncPC(stubS32_217),
	runtype.FuncPC(stubS32_218),
	runtype.FuncPC(stubS32_219),
	runtype.FuncPC(stubS32_220),
	runtype.FuncPC(stubS32_221),
	runtype.FuncPC(stubS32_222),
	runtype.FuncPC(stubS32_223),
	runtype.FuncPC(stubS32_224),
	runtype.FuncPC(stubS32_225),
	runtype.FuncPC(stubS32_226),
	runtype.FuncPC(stubS32_227),
	runtype.FuncPC(stubS32_228),
	runtype.FuncPC(stubS32_229),
	runtype.FuncPC(stubS32_230),
	runtype.FuncPC(stubS32_231),
	runtype.FuncPC(stubS32_232),
	runtype.FuncPC(stubS32_233),
	runtype.FuncPC(stubS32_234),
	runtype.FuncPC(stubS32_235),
	runtype.FuncPC(stubS32_236),
	runtype.FuncPC(stubS32_237),
	runtype.FuncPC(stubS32_238),
	runtype.FuncPC(stubS32_239),
	runtype.FuncPC(stubS32_240),
	runtype.FuncPC(stubS32_241),
	runtype.FuncPC(stubS32_242),
	runtype.FuncPC(stubS32_243),
	runtype.FuncPC(stubS32_244),
	runtype.FuncPC(stubS32_245),
	runtype.FuncPC(stubS32_246),
	runtype.FuncPC(stubS32_247),
	runtype.FuncPC(stubS32_248),
	runtype.FuncPC(stubS32_249),
	runtype.FuncPC(stubS32_250),
	runtype.FuncPC(stubS32_251),
	runtype.FuncPC(stubS32_252),
	runtype.FuncPC(stubS32_253),
	runtype.FuncPC(stubS32_254),
	runtype.FuncPC(stubS32_255),
}
