// Code generated by gen_pools.go; DO NOT EDIT.
// Shape S20 pool: 256 slots.

package stubs

import (
	"unsafe"

	"github.com/mvm-sh/mvm/runtype"
)

const poolSizeS20 = 256

//go:noinline
func stubS20_0(recv unsafe.Pointer, value string) error { return dispatchS20(0, recv, value) }

//go:noinline
func stubS20_1(recv unsafe.Pointer, value string) error { return dispatchS20(1, recv, value) }

//go:noinline
func stubS20_2(recv unsafe.Pointer, value string) error { return dispatchS20(2, recv, value) }

//go:noinline
func stubS20_3(recv unsafe.Pointer, value string) error { return dispatchS20(3, recv, value) }

//go:noinline
func stubS20_4(recv unsafe.Pointer, value string) error { return dispatchS20(4, recv, value) }

//go:noinline
func stubS20_5(recv unsafe.Pointer, value string) error { return dispatchS20(5, recv, value) }

//go:noinline
func stubS20_6(recv unsafe.Pointer, value string) error { return dispatchS20(6, recv, value) }

//go:noinline
func stubS20_7(recv unsafe.Pointer, value string) error { return dispatchS20(7, recv, value) }

//go:noinline
func stubS20_8(recv unsafe.Pointer, value string) error { return dispatchS20(8, recv, value) }

//go:noinline
func stubS20_9(recv unsafe.Pointer, value string) error { return dispatchS20(9, recv, value) }

//go:noinline
func stubS20_10(recv unsafe.Pointer, value string) error { return dispatchS20(10, recv, value) }

//go:noinline
func stubS20_11(recv unsafe.Pointer, value string) error { return dispatchS20(11, recv, value) }

//go:noinline
func stubS20_12(recv unsafe.Pointer, value string) error { return dispatchS20(12, recv, value) }

//go:noinline
func stubS20_13(recv unsafe.Pointer, value string) error { return dispatchS20(13, recv, value) }

//go:noinline
func stubS20_14(recv unsafe.Pointer, value string) error { return dispatchS20(14, recv, value) }

//go:noinline
func stubS20_15(recv unsafe.Pointer, value string) error { return dispatchS20(15, recv, value) }

//go:noinline
func stubS20_16(recv unsafe.Pointer, value string) error { return dispatchS20(16, recv, value) }

//go:noinline
func stubS20_17(recv unsafe.Pointer, value string) error { return dispatchS20(17, recv, value) }

//go:noinline
func stubS20_18(recv unsafe.Pointer, value string) error { return dispatchS20(18, recv, value) }

//go:noinline
func stubS20_19(recv unsafe.Pointer, value string) error { return dispatchS20(19, recv, value) }

//go:noinline
func stubS20_20(recv unsafe.Pointer, value string) error { return dispatchS20(20, recv, value) }

//go:noinline
func stubS20_21(recv unsafe.Pointer, value string) error { return dispatchS20(21, recv, value) }

//go:noinline
func stubS20_22(recv unsafe.Pointer, value string) error { return dispatchS20(22, recv, value) }

//go:noinline
func stubS20_23(recv unsafe.Pointer, value string) error { return dispatchS20(23, recv, value) }

//go:noinline
func stubS20_24(recv unsafe.Pointer, value string) error { return dispatchS20(24, recv, value) }

//go:noinline
func stubS20_25(recv unsafe.Pointer, value string) error { return dispatchS20(25, recv, value) }

//go:noinline
func stubS20_26(recv unsafe.Pointer, value string) error { return dispatchS20(26, recv, value) }

//go:noinline
func stubS20_27(recv unsafe.Pointer, value string) error { return dispatchS20(27, recv, value) }

//go:noinline
func stubS20_28(recv unsafe.Pointer, value string) error { return dispatchS20(28, recv, value) }

//go:noinline
func stubS20_29(recv unsafe.Pointer, value string) error { return dispatchS20(29, recv, value) }

//go:noinline
func stubS20_30(recv unsafe.Pointer, value string) error { return dispatchS20(30, recv, value) }

//go:noinline
func stubS20_31(recv unsafe.Pointer, value string) error { return dispatchS20(31, recv, value) }

//go:noinline
func stubS20_32(recv unsafe.Pointer, value string) error { return dispatchS20(32, recv, value) }

//go:noinline
func stubS20_33(recv unsafe.Pointer, value string) error { return dispatchS20(33, recv, value) }

//go:noinline
func stubS20_34(recv unsafe.Pointer, value string) error { return dispatchS20(34, recv, value) }

//go:noinline
func stubS20_35(recv unsafe.Pointer, value string) error { return dispatchS20(35, recv, value) }

//go:noinline
func stubS20_36(recv unsafe.Pointer, value string) error { return dispatchS20(36, recv, value) }

//go:noinline
func stubS20_37(recv unsafe.Pointer, value string) error { return dispatchS20(37, recv, value) }

//go:noinline
func stubS20_38(recv unsafe.Pointer, value string) error { return dispatchS20(38, recv, value) }

//go:noinline
func stubS20_39(recv unsafe.Pointer, value string) error { return dispatchS20(39, recv, value) }

//go:noinline
func stubS20_40(recv unsafe.Pointer, value string) error { return dispatchS20(40, recv, value) }

//go:noinline
func stubS20_41(recv unsafe.Pointer, value string) error { return dispatchS20(41, recv, value) }

//go:noinline
func stubS20_42(recv unsafe.Pointer, value string) error { return dispatchS20(42, recv, value) }

//go:noinline
func stubS20_43(recv unsafe.Pointer, value string) error { return dispatchS20(43, recv, value) }

//go:noinline
func stubS20_44(recv unsafe.Pointer, value string) error { return dispatchS20(44, recv, value) }

//go:noinline
func stubS20_45(recv unsafe.Pointer, value string) error { return dispatchS20(45, recv, value) }

//go:noinline
func stubS20_46(recv unsafe.Pointer, value string) error { return dispatchS20(46, recv, value) }

//go:noinline
func stubS20_47(recv unsafe.Pointer, value string) error { return dispatchS20(47, recv, value) }

//go:noinline
func stubS20_48(recv unsafe.Pointer, value string) error { return dispatchS20(48, recv, value) }

//go:noinline
func stubS20_49(recv unsafe.Pointer, value string) error { return dispatchS20(49, recv, value) }

//go:noinline
func stubS20_50(recv unsafe.Pointer, value string) error { return dispatchS20(50, recv, value) }

//go:noinline
func stubS20_51(recv unsafe.Pointer, value string) error { return dispatchS20(51, recv, value) }

//go:noinline
func stubS20_52(recv unsafe.Pointer, value string) error { return dispatchS20(52, recv, value) }

//go:noinline
func stubS20_53(recv unsafe.Pointer, value string) error { return dispatchS20(53, recv, value) }

//go:noinline
func stubS20_54(recv unsafe.Pointer, value string) error { return dispatchS20(54, recv, value) }

//go:noinline
func stubS20_55(recv unsafe.Pointer, value string) error { return dispatchS20(55, recv, value) }

//go:noinline
func stubS20_56(recv unsafe.Pointer, value string) error { return dispatchS20(56, recv, value) }

//go:noinline
func stubS20_57(recv unsafe.Pointer, value string) error { return dispatchS20(57, recv, value) }

//go:noinline
func stubS20_58(recv unsafe.Pointer, value string) error { return dispatchS20(58, recv, value) }

//go:noinline
func stubS20_59(recv unsafe.Pointer, value string) error { return dispatchS20(59, recv, value) }

//go:noinline
func stubS20_60(recv unsafe.Pointer, value string) error { return dispatchS20(60, recv, value) }

//go:noinline
func stubS20_61(recv unsafe.Pointer, value string) error { return dispatchS20(61, recv, value) }

//go:noinline
func stubS20_62(recv unsafe.Pointer, value string) error { return dispatchS20(62, recv, value) }

//go:noinline
func stubS20_63(recv unsafe.Pointer, value string) error { return dispatchS20(63, recv, value) }

//go:noinline
func stubS20_64(recv unsafe.Pointer, value string) error { return dispatchS20(64, recv, value) }

//go:noinline
func stubS20_65(recv unsafe.Pointer, value string) error { return dispatchS20(65, recv, value) }

//go:noinline
func stubS20_66(recv unsafe.Pointer, value string) error { return dispatchS20(66, recv, value) }

//go:noinline
func stubS20_67(recv unsafe.Pointer, value string) error { return dispatchS20(67, recv, value) }

//go:noinline
func stubS20_68(recv unsafe.Pointer, value string) error { return dispatchS20(68, recv, value) }

//go:noinline
func stubS20_69(recv unsafe.Pointer, value string) error { return dispatchS20(69, recv, value) }

//go:noinline
func stubS20_70(recv unsafe.Pointer, value string) error { return dispatchS20(70, recv, value) }

//go:noinline
func stubS20_71(recv unsafe.Pointer, value string) error { return dispatchS20(71, recv, value) }

//go:noinline
func stubS20_72(recv unsafe.Pointer, value string) error { return dispatchS20(72, recv, value) }

//go:noinline
func stubS20_73(recv unsafe.Pointer, value string) error { return dispatchS20(73, recv, value) }

//go:noinline
func stubS20_74(recv unsafe.Pointer, value string) error { return dispatchS20(74, recv, value) }

//go:noinline
func stubS20_75(recv unsafe.Pointer, value string) error { return dispatchS20(75, recv, value) }

//go:noinline
func stubS20_76(recv unsafe.Pointer, value string) error { return dispatchS20(76, recv, value) }

//go:noinline
func stubS20_77(recv unsafe.Pointer, value string) error { return dispatchS20(77, recv, value) }

//go:noinline
func stubS20_78(recv unsafe.Pointer, value string) error { return dispatchS20(78, recv, value) }

//go:noinline
func stubS20_79(recv unsafe.Pointer, value string) error { return dispatchS20(79, recv, value) }

//go:noinline
func stubS20_80(recv unsafe.Pointer, value string) error { return dispatchS20(80, recv, value) }

//go:noinline
func stubS20_81(recv unsafe.Pointer, value string) error { return dispatchS20(81, recv, value) }

//go:noinline
func stubS20_82(recv unsafe.Pointer, value string) error { return dispatchS20(82, recv, value) }

//go:noinline
func stubS20_83(recv unsafe.Pointer, value string) error { return dispatchS20(83, recv, value) }

//go:noinline
func stubS20_84(recv unsafe.Pointer, value string) error { return dispatchS20(84, recv, value) }

//go:noinline
func stubS20_85(recv unsafe.Pointer, value string) error { return dispatchS20(85, recv, value) }

//go:noinline
func stubS20_86(recv unsafe.Pointer, value string) error { return dispatchS20(86, recv, value) }

//go:noinline
func stubS20_87(recv unsafe.Pointer, value string) error { return dispatchS20(87, recv, value) }

//go:noinline
func stubS20_88(recv unsafe.Pointer, value string) error { return dispatchS20(88, recv, value) }

//go:noinline
func stubS20_89(recv unsafe.Pointer, value string) error { return dispatchS20(89, recv, value) }

//go:noinline
func stubS20_90(recv unsafe.Pointer, value string) error { return dispatchS20(90, recv, value) }

//go:noinline
func stubS20_91(recv unsafe.Pointer, value string) error { return dispatchS20(91, recv, value) }

//go:noinline
func stubS20_92(recv unsafe.Pointer, value string) error { return dispatchS20(92, recv, value) }

//go:noinline
func stubS20_93(recv unsafe.Pointer, value string) error { return dispatchS20(93, recv, value) }

//go:noinline
func stubS20_94(recv unsafe.Pointer, value string) error { return dispatchS20(94, recv, value) }

//go:noinline
func stubS20_95(recv unsafe.Pointer, value string) error { return dispatchS20(95, recv, value) }

//go:noinline
func stubS20_96(recv unsafe.Pointer, value string) error { return dispatchS20(96, recv, value) }

//go:noinline
func stubS20_97(recv unsafe.Pointer, value string) error { return dispatchS20(97, recv, value) }

//go:noinline
func stubS20_98(recv unsafe.Pointer, value string) error { return dispatchS20(98, recv, value) }

//go:noinline
func stubS20_99(recv unsafe.Pointer, value string) error { return dispatchS20(99, recv, value) }

//go:noinline
func stubS20_100(recv unsafe.Pointer, value string) error { return dispatchS20(100, recv, value) }

//go:noinline
func stubS20_101(recv unsafe.Pointer, value string) error { return dispatchS20(101, recv, value) }

//go:noinline
func stubS20_102(recv unsafe.Pointer, value string) error { return dispatchS20(102, recv, value) }

//go:noinline
func stubS20_103(recv unsafe.Pointer, value string) error { return dispatchS20(103, recv, value) }

//go:noinline
func stubS20_104(recv unsafe.Pointer, value string) error { return dispatchS20(104, recv, value) }

//go:noinline
func stubS20_105(recv unsafe.Pointer, value string) error { return dispatchS20(105, recv, value) }

//go:noinline
func stubS20_106(recv unsafe.Pointer, value string) error { return dispatchS20(106, recv, value) }

//go:noinline
func stubS20_107(recv unsafe.Pointer, value string) error { return dispatchS20(107, recv, value) }

//go:noinline
func stubS20_108(recv unsafe.Pointer, value string) error { return dispatchS20(108, recv, value) }

//go:noinline
func stubS20_109(recv unsafe.Pointer, value string) error { return dispatchS20(109, recv, value) }

//go:noinline
func stubS20_110(recv unsafe.Pointer, value string) error { return dispatchS20(110, recv, value) }

//go:noinline
func stubS20_111(recv unsafe.Pointer, value string) error { return dispatchS20(111, recv, value) }

//go:noinline
func stubS20_112(recv unsafe.Pointer, value string) error { return dispatchS20(112, recv, value) }

//go:noinline
func stubS20_113(recv unsafe.Pointer, value string) error { return dispatchS20(113, recv, value) }

//go:noinline
func stubS20_114(recv unsafe.Pointer, value string) error { return dispatchS20(114, recv, value) }

//go:noinline
func stubS20_115(recv unsafe.Pointer, value string) error { return dispatchS20(115, recv, value) }

//go:noinline
func stubS20_116(recv unsafe.Pointer, value string) error { return dispatchS20(116, recv, value) }

//go:noinline
func stubS20_117(recv unsafe.Pointer, value string) error { return dispatchS20(117, recv, value) }

//go:noinline
func stubS20_118(recv unsafe.Pointer, value string) error { return dispatchS20(118, recv, value) }

//go:noinline
func stubS20_119(recv unsafe.Pointer, value string) error { return dispatchS20(119, recv, value) }

//go:noinline
func stubS20_120(recv unsafe.Pointer, value string) error { return dispatchS20(120, recv, value) }

//go:noinline
func stubS20_121(recv unsafe.Pointer, value string) error { return dispatchS20(121, recv, value) }

//go:noinline
func stubS20_122(recv unsafe.Pointer, value string) error { return dispatchS20(122, recv, value) }

//go:noinline
func stubS20_123(recv unsafe.Pointer, value string) error { return dispatchS20(123, recv, value) }

//go:noinline
func stubS20_124(recv unsafe.Pointer, value string) error { return dispatchS20(124, recv, value) }

//go:noinline
func stubS20_125(recv unsafe.Pointer, value string) error { return dispatchS20(125, recv, value) }

//go:noinline
func stubS20_126(recv unsafe.Pointer, value string) error { return dispatchS20(126, recv, value) }

//go:noinline
func stubS20_127(recv unsafe.Pointer, value string) error { return dispatchS20(127, recv, value) }

//go:noinline
func stubS20_128(recv unsafe.Pointer, value string) error { return dispatchS20(128, recv, value) }

//go:noinline
func stubS20_129(recv unsafe.Pointer, value string) error { return dispatchS20(129, recv, value) }

//go:noinline
func stubS20_130(recv unsafe.Pointer, value string) error { return dispatchS20(130, recv, value) }

//go:noinline
func stubS20_131(recv unsafe.Pointer, value string) error { return dispatchS20(131, recv, value) }

//go:noinline
func stubS20_132(recv unsafe.Pointer, value string) error { return dispatchS20(132, recv, value) }

//go:noinline
func stubS20_133(recv unsafe.Pointer, value string) error { return dispatchS20(133, recv, value) }

//go:noinline
func stubS20_134(recv unsafe.Pointer, value string) error { return dispatchS20(134, recv, value) }

//go:noinline
func stubS20_135(recv unsafe.Pointer, value string) error { return dispatchS20(135, recv, value) }

//go:noinline
func stubS20_136(recv unsafe.Pointer, value string) error { return dispatchS20(136, recv, value) }

//go:noinline
func stubS20_137(recv unsafe.Pointer, value string) error { return dispatchS20(137, recv, value) }

//go:noinline
func stubS20_138(recv unsafe.Pointer, value string) error { return dispatchS20(138, recv, value) }

//go:noinline
func stubS20_139(recv unsafe.Pointer, value string) error { return dispatchS20(139, recv, value) }

//go:noinline
func stubS20_140(recv unsafe.Pointer, value string) error { return dispatchS20(140, recv, value) }

//go:noinline
func stubS20_141(recv unsafe.Pointer, value string) error { return dispatchS20(141, recv, value) }

//go:noinline
func stubS20_142(recv unsafe.Pointer, value string) error { return dispatchS20(142, recv, value) }

//go:noinline
func stubS20_143(recv unsafe.Pointer, value string) error { return dispatchS20(143, recv, value) }

//go:noinline
func stubS20_144(recv unsafe.Pointer, value string) error { return dispatchS20(144, recv, value) }

//go:noinline
func stubS20_145(recv unsafe.Pointer, value string) error { return dispatchS20(145, recv, value) }

//go:noinline
func stubS20_146(recv unsafe.Pointer, value string) error { return dispatchS20(146, recv, value) }

//go:noinline
func stubS20_147(recv unsafe.Pointer, value string) error { return dispatchS20(147, recv, value) }

//go:noinline
func stubS20_148(recv unsafe.Pointer, value string) error { return dispatchS20(148, recv, value) }

//go:noinline
func stubS20_149(recv unsafe.Pointer, value string) error { return dispatchS20(149, recv, value) }

//go:noinline
func stubS20_150(recv unsafe.Pointer, value string) error { return dispatchS20(150, recv, value) }

//go:noinline
func stubS20_151(recv unsafe.Pointer, value string) error { return dispatchS20(151, recv, value) }

//go:noinline
func stubS20_152(recv unsafe.Pointer, value string) error { return dispatchS20(152, recv, value) }

//go:noinline
func stubS20_153(recv unsafe.Pointer, value string) error { return dispatchS20(153, recv, value) }

//go:noinline
func stubS20_154(recv unsafe.Pointer, value string) error { return dispatchS20(154, recv, value) }

//go:noinline
func stubS20_155(recv unsafe.Pointer, value string) error { return dispatchS20(155, recv, value) }

//go:noinline
func stubS20_156(recv unsafe.Pointer, value string) error { return dispatchS20(156, recv, value) }

//go:noinline
func stubS20_157(recv unsafe.Pointer, value string) error { return dispatchS20(157, recv, value) }

//go:noinline
func stubS20_158(recv unsafe.Pointer, value string) error { return dispatchS20(158, recv, value) }

//go:noinline
func stubS20_159(recv unsafe.Pointer, value string) error { return dispatchS20(159, recv, value) }

//go:noinline
func stubS20_160(recv unsafe.Pointer, value string) error { return dispatchS20(160, recv, value) }

//go:noinline
func stubS20_161(recv unsafe.Pointer, value string) error { return dispatchS20(161, recv, value) }

//go:noinline
func stubS20_162(recv unsafe.Pointer, value string) error { return dispatchS20(162, recv, value) }

//go:noinline
func stubS20_163(recv unsafe.Pointer, value string) error { return dispatchS20(163, recv, value) }

//go:noinline
func stubS20_164(recv unsafe.Pointer, value string) error { return dispatchS20(164, recv, value) }

//go:noinline
func stubS20_165(recv unsafe.Pointer, value string) error { return dispatchS20(165, recv, value) }

//go:noinline
func stubS20_166(recv unsafe.Pointer, value string) error { return dispatchS20(166, recv, value) }

//go:noinline
func stubS20_167(recv unsafe.Pointer, value string) error { return dispatchS20(167, recv, value) }

//go:noinline
func stubS20_168(recv unsafe.Pointer, value string) error { return dispatchS20(168, recv, value) }

//go:noinline
func stubS20_169(recv unsafe.Pointer, value string) error { return dispatchS20(169, recv, value) }

//go:noinline
func stubS20_170(recv unsafe.Pointer, value string) error { return dispatchS20(170, recv, value) }

//go:noinline
func stubS20_171(recv unsafe.Pointer, value string) error { return dispatchS20(171, recv, value) }

//go:noinline
func stubS20_172(recv unsafe.Pointer, value string) error { return dispatchS20(172, recv, value) }

//go:noinline
func stubS20_173(recv unsafe.Pointer, value string) error { return dispatchS20(173, recv, value) }

//go:noinline
func stubS20_174(recv unsafe.Pointer, value string) error { return dispatchS20(174, recv, value) }

//go:noinline
func stubS20_175(recv unsafe.Pointer, value string) error { return dispatchS20(175, recv, value) }

//go:noinline
func stubS20_176(recv unsafe.Pointer, value string) error { return dispatchS20(176, recv, value) }

//go:noinline
func stubS20_177(recv unsafe.Pointer, value string) error { return dispatchS20(177, recv, value) }

//go:noinline
func stubS20_178(recv unsafe.Pointer, value string) error { return dispatchS20(178, recv, value) }

//go:noinline
func stubS20_179(recv unsafe.Pointer, value string) error { return dispatchS20(179, recv, value) }

//go:noinline
func stubS20_180(recv unsafe.Pointer, value string) error { return dispatchS20(180, recv, value) }

//go:noinline
func stubS20_181(recv unsafe.Pointer, value string) error { return dispatchS20(181, recv, value) }

//go:noinline
func stubS20_182(recv unsafe.Pointer, value string) error { return dispatchS20(182, recv, value) }

//go:noinline
func stubS20_183(recv unsafe.Pointer, value string) error { return dispatchS20(183, recv, value) }

//go:noinline
func stubS20_184(recv unsafe.Pointer, value string) error { return dispatchS20(184, recv, value) }

//go:noinline
func stubS20_185(recv unsafe.Pointer, value string) error { return dispatchS20(185, recv, value) }

//go:noinline
func stubS20_186(recv unsafe.Pointer, value string) error { return dispatchS20(186, recv, value) }

//go:noinline
func stubS20_187(recv unsafe.Pointer, value string) error { return dispatchS20(187, recv, value) }

//go:noinline
func stubS20_188(recv unsafe.Pointer, value string) error { return dispatchS20(188, recv, value) }

//go:noinline
func stubS20_189(recv unsafe.Pointer, value string) error { return dispatchS20(189, recv, value) }

//go:noinline
func stubS20_190(recv unsafe.Pointer, value string) error { return dispatchS20(190, recv, value) }

//go:noinline
func stubS20_191(recv unsafe.Pointer, value string) error { return dispatchS20(191, recv, value) }

//go:noinline
func stubS20_192(recv unsafe.Pointer, value string) error { return dispatchS20(192, recv, value) }

//go:noinline
func stubS20_193(recv unsafe.Pointer, value string) error { return dispatchS20(193, recv, value) }

//go:noinline
func stubS20_194(recv unsafe.Pointer, value string) error { return dispatchS20(194, recv, value) }

//go:noinline
func stubS20_195(recv unsafe.Pointer, value string) error { return dispatchS20(195, recv, value) }

//go:noinline
func stubS20_196(recv unsafe.Pointer, value string) error { return dispatchS20(196, recv, value) }

//go:noinline
func stubS20_197(recv unsafe.Pointer, value string) error { return dispatchS20(197, recv, value) }

//go:noinline
func stubS20_198(recv unsafe.Pointer, value string) error { return dispatchS20(198, recv, value) }

//go:noinline
func stubS20_199(recv unsafe.Pointer, value string) error { return dispatchS20(199, recv, value) }

//go:noinline
func stubS20_200(recv unsafe.Pointer, value string) error { return dispatchS20(200, recv, value) }

//go:noinline
func stubS20_201(recv unsafe.Pointer, value string) error { return dispatchS20(201, recv, value) }

//go:noinline
func stubS20_202(recv unsafe.Pointer, value string) error { return dispatchS20(202, recv, value) }

//go:noinline
func stubS20_203(recv unsafe.Pointer, value string) error { return dispatchS20(203, recv, value) }

//go:noinline
func stubS20_204(recv unsafe.Pointer, value string) error { return dispatchS20(204, recv, value) }

//go:noinline
func stubS20_205(recv unsafe.Pointer, value string) error { return dispatchS20(205, recv, value) }

//go:noinline
func stubS20_206(recv unsafe.Pointer, value string) error { return dispatchS20(206, recv, value) }

//go:noinline
func stubS20_207(recv unsafe.Pointer, value string) error { return dispatchS20(207, recv, value) }

//go:noinline
func stubS20_208(recv unsafe.Pointer, value string) error { return dispatchS20(208, recv, value) }

//go:noinline
func stubS20_209(recv unsafe.Pointer, value string) error { return dispatchS20(209, recv, value) }

//go:noinline
func stubS20_210(recv unsafe.Pointer, value string) error { return dispatchS20(210, recv, value) }

//go:noinline
func stubS20_211(recv unsafe.Pointer, value string) error { return dispatchS20(211, recv, value) }

//go:noinline
func stubS20_212(recv unsafe.Pointer, value string) error { return dispatchS20(212, recv, value) }

//go:noinline
func stubS20_213(recv unsafe.Pointer, value string) error { return dispatchS20(213, recv, value) }

//go:noinline
func stubS20_214(recv unsafe.Pointer, value string) error { return dispatchS20(214, recv, value) }

//go:noinline
func stubS20_215(recv unsafe.Pointer, value string) error { return dispatchS20(215, recv, value) }

//go:noinline
func stubS20_216(recv unsafe.Pointer, value string) error { return dispatchS20(216, recv, value) }

//go:noinline
func stubS20_217(recv unsafe.Pointer, value string) error { return dispatchS20(217, recv, value) }

//go:noinline
func stubS20_218(recv unsafe.Pointer, value string) error { return dispatchS20(218, recv, value) }

//go:noinline
func stubS20_219(recv unsafe.Pointer, value string) error { return dispatchS20(219, recv, value) }

//go:noinline
func stubS20_220(recv unsafe.Pointer, value string) error { return dispatchS20(220, recv, value) }

//go:noinline
func stubS20_221(recv unsafe.Pointer, value string) error { return dispatchS20(221, recv, value) }

//go:noinline
func stubS20_222(recv unsafe.Pointer, value string) error { return dispatchS20(222, recv, value) }

//go:noinline
func stubS20_223(recv unsafe.Pointer, value string) error { return dispatchS20(223, recv, value) }

//go:noinline
func stubS20_224(recv unsafe.Pointer, value string) error { return dispatchS20(224, recv, value) }

//go:noinline
func stubS20_225(recv unsafe.Pointer, value string) error { return dispatchS20(225, recv, value) }

//go:noinline
func stubS20_226(recv unsafe.Pointer, value string) error { return dispatchS20(226, recv, value) }

//go:noinline
func stubS20_227(recv unsafe.Pointer, value string) error { return dispatchS20(227, recv, value) }

//go:noinline
func stubS20_228(recv unsafe.Pointer, value string) error { return dispatchS20(228, recv, value) }

//go:noinline
func stubS20_229(recv unsafe.Pointer, value string) error { return dispatchS20(229, recv, value) }

//go:noinline
func stubS20_230(recv unsafe.Pointer, value string) error { return dispatchS20(230, recv, value) }

//go:noinline
func stubS20_231(recv unsafe.Pointer, value string) error { return dispatchS20(231, recv, value) }

//go:noinline
func stubS20_232(recv unsafe.Pointer, value string) error { return dispatchS20(232, recv, value) }

//go:noinline
func stubS20_233(recv unsafe.Pointer, value string) error { return dispatchS20(233, recv, value) }

//go:noinline
func stubS20_234(recv unsafe.Pointer, value string) error { return dispatchS20(234, recv, value) }

//go:noinline
func stubS20_235(recv unsafe.Pointer, value string) error { return dispatchS20(235, recv, value) }

//go:noinline
func stubS20_236(recv unsafe.Pointer, value string) error { return dispatchS20(236, recv, value) }

//go:noinline
func stubS20_237(recv unsafe.Pointer, value string) error { return dispatchS20(237, recv, value) }

//go:noinline
func stubS20_238(recv unsafe.Pointer, value string) error { return dispatchS20(238, recv, value) }

//go:noinline
func stubS20_239(recv unsafe.Pointer, value string) error { return dispatchS20(239, recv, value) }

//go:noinline
func stubS20_240(recv unsafe.Pointer, value string) error { return dispatchS20(240, recv, value) }

//go:noinline
func stubS20_241(recv unsafe.Pointer, value string) error { return dispatchS20(241, recv, value) }

//go:noinline
func stubS20_242(recv unsafe.Pointer, value string) error { return dispatchS20(242, recv, value) }

//go:noinline
func stubS20_243(recv unsafe.Pointer, value string) error { return dispatchS20(243, recv, value) }

//go:noinline
func stubS20_244(recv unsafe.Pointer, value string) error { return dispatchS20(244, recv, value) }

//go:noinline
func stubS20_245(recv unsafe.Pointer, value string) error { return dispatchS20(245, recv, value) }

//go:noinline
func stubS20_246(recv unsafe.Pointer, value string) error { return dispatchS20(246, recv, value) }

//go:noinline
func stubS20_247(recv unsafe.Pointer, value string) error { return dispatchS20(247, recv, value) }

//go:noinline
func stubS20_248(recv unsafe.Pointer, value string) error { return dispatchS20(248, recv, value) }

//go:noinline
func stubS20_249(recv unsafe.Pointer, value string) error { return dispatchS20(249, recv, value) }

//go:noinline
func stubS20_250(recv unsafe.Pointer, value string) error { return dispatchS20(250, recv, value) }

//go:noinline
func stubS20_251(recv unsafe.Pointer, value string) error { return dispatchS20(251, recv, value) }

//go:noinline
func stubS20_252(recv unsafe.Pointer, value string) error { return dispatchS20(252, recv, value) }

//go:noinline
func stubS20_253(recv unsafe.Pointer, value string) error { return dispatchS20(253, recv, value) }

//go:noinline
func stubS20_254(recv unsafe.Pointer, value string) error { return dispatchS20(254, recv, value) }

//go:noinline
func stubS20_255(recv unsafe.Pointer, value string) error { return dispatchS20(255, recv, value) }

var stubsS20 = [poolSizeS20]uintptr{
	runtype.FuncPC(stubS20_0),
	runtype.FuncPC(stubS20_1),
	runtype.FuncPC(stubS20_2),
	runtype.FuncPC(stubS20_3),
	runtype.FuncPC(stubS20_4),
	runtype.FuncPC(stubS20_5),
	runtype.FuncPC(stubS20_6),
	runtype.FuncPC(stubS20_7),
	runtype.FuncPC(stubS20_8),
	runtype.FuncPC(stubS20_9),
	runtype.FuncPC(stubS20_10),
	runtype.FuncPC(stubS20_11),
	runtype.FuncPC(stubS20_12),
	runtype.FuncPC(stubS20_13),
	runtype.FuncPC(stubS20_14),
	runtype.FuncPC(stubS20_15),
	runtype.FuncPC(stubS20_16),
	runtype.FuncPC(stubS20_17),
	runtype.FuncPC(stubS20_18),
	runtype.FuncPC(stubS20_19),
	runtype.FuncPC(stubS20_20),
	runtype.FuncPC(stubS20_21),
	runtype.FuncPC(stubS20_22),
	runtype.FuncPC(stubS20_23),
	runtype.FuncPC(stubS20_24),
	runtype.FuncPC(stubS20_25),
	runtype.FuncPC(stubS20_26),
	runtype.FuncPC(stubS20_27),
	runtype.FuncPC(stubS20_28),
	runtype.FuncPC(stubS20_29),
	runtype.FuncPC(stubS20_30),
	runtype.FuncPC(stubS20_31),
	runtype.FuncPC(stubS20_32),
	runtype.FuncPC(stubS20_33),
	runtype.FuncPC(stubS20_34),
	runtype.FuncPC(stubS20_35),
	runtype.FuncPC(stubS20_36),
	runtype.FuncPC(stubS20_37),
	runtype.FuncPC(stubS20_38),
	runtype.FuncPC(stubS20_39),
	runtype.FuncPC(stubS20_40),
	runtype.FuncPC(stubS20_41),
	runtype.FuncPC(stubS20_42),
	runtype.FuncPC(stubS20_43),
	runtype.FuncPC(stubS20_44),
	runtype.FuncPC(stubS20_45),
	runtype.FuncPC(stubS20_46),
	runtype.FuncPC(stubS20_47),
	runtype.FuncPC(stubS20_48),
	runtype.FuncPC(stubS20_49),
	runtype.FuncPC(stubS20_50),
	runtype.FuncPC(stubS20_51),
	runtype.FuncPC(stubS20_52),
	runtype.FuncPC(stubS20_53),
	runtype.FuncPC(stubS20_54),
	runtype.FuncPC(stubS20_55),
	runtype.FuncPC(stubS20_56),
	runtype.FuncPC(stubS20_57),
	runtype.FuncPC(stubS20_58),
	runtype.FuncPC(stubS20_59),
	runtype.FuncPC(stubS20_60),
	runtype.FuncPC(stubS20_61),
	runtype.FuncPC(stubS20_62),
	runtype.FuncPC(stubS20_63),
	runtype.FuncPC(stubS20_64),
	runtype.FuncPC(stubS20_65),
	runtype.FuncPC(stubS20_66),
	runtype.FuncPC(stubS20_67),
	runtype.FuncPC(stubS20_68),
	runtype.FuncPC(stubS20_69),
	runtype.FuncPC(stubS20_70),
	runtype.FuncPC(stubS20_71),
	runtype.FuncPC(stubS20_72),
	runtype.FuncPC(stubS20_73),
	runtype.FuncPC(stubS20_74),
	runtype.FuncPC(stubS20_75),
	runtype.FuncPC(stubS20_76),
	runtype.FuncPC(stubS20_77),
	runtype.FuncPC(stubS20_78),
	runtype.FuncPC(stubS20_79),
	runtype.FuncPC(stubS20_80),
	runtype.FuncPC(stubS20_81),
	runtype.FuncPC(stubS20_82),
	runtype.FuncPC(stubS20_83),
	runtype.FuncPC(stubS20_84),
	runtype.FuncPC(stubS20_85),
	runtype.FuncPC(stubS20_86),
	runtype.FuncPC(stubS20_87),
	runtype.FuncPC(stubS20_88),
	runtype.FuncPC(stubS20_89),
	runtype.FuncPC(stubS20_90),
	runtype.FuncPC(stubS20_91),
	runtype.FuncPC(stubS20_92),
	runtype.FuncPC(stubS20_93),
	runtype.FuncPC(stubS20_94),
	runtype.FuncPC(stubS20_95),
	runtype.FuncPC(stubS20_96),
	runtype.FuncPC(stubS20_97),
	runtype.FuncPC(stubS20_98),
	runtype.FuncPC(stubS20_99),
	runtype.FuncPC(stubS20_100),
	runtype.FuncPC(stubS20_101),
	runtype.FuncPC(stubS20_102),
	runtype.FuncPC(stubS20_103),
	runtype.FuncPC(stubS20_104),
	runtype.FuncPC(stubS20_105),
	runtype.FuncPC(stubS20_106),
	runtype.FuncPC(stubS20_107),
	runtype.FuncPC(stubS20_108),
	runtype.FuncPC(stubS20_109),
	runtype.FuncPC(stubS20_110),
	runtype.FuncPC(stubS20_111),
	runtype.FuncPC(stubS20_112),
	runtype.FuncPC(stubS20_113),
	runtype.FuncPC(stubS20_114),
	runtype.FuncPC(stubS20_115),
	runtype.FuncPC(stubS20_116),
	runtype.FuncPC(stubS20_117),
	runtype.FuncPC(stubS20_118),
	runtype.FuncPC(stubS20_119),
	runtype.FuncPC(stubS20_120),
	runtype.FuncPC(stubS20_121),
	runtype.FuncPC(stubS20_122),
	runtype.FuncPC(stubS20_123),
	runtype.FuncPC(stubS20_124),
	runtype.FuncPC(stubS20_125),
	runtype.FuncPC(stubS20_126),
	runtype.FuncPC(stubS20_127),
	runtype.FuncPC(stubS20_128),
	runtype.FuncPC(stubS20_129),
	runtype.FuncPC(stubS20_130),
	runtype.FuncPC(stubS20_131),
	runtype.FuncPC(stubS20_132),
	runtype.FuncPC(stubS20_133),
	runtype.FuncPC(stubS20_134),
	runtype.FuncPC(stubS20_135),
	runtype.FuncPC(stubS20_136),
	runtype.FuncPC(stubS20_137),
	runtype.FuncPC(stubS20_138),
	runtype.FuncPC(stubS20_139),
	runtype.FuncPC(stubS20_140),
	runtype.FuncPC(stubS20_141),
	runtype.FuncPC(stubS20_142),
	runtype.FuncPC(stubS20_143),
	runtype.FuncPC(stubS20_144),
	runtype.FuncPC(stubS20_145),
	runtype.FuncPC(stubS20_146),
	runtype.FuncPC(stubS20_147),
	runtype.FuncPC(stubS20_148),
	runtype.FuncPC(stubS20_149),
	runtype.FuncPC(stubS20_150),
	runtype.FuncPC(stubS20_151),
	runtype.FuncPC(stubS20_152),
	runtype.FuncPC(stubS20_153),
	runtype.FuncPC(stubS20_154),
	runtype.FuncPC(stubS20_155),
	runtype.FuncPC(stubS20_156),
	runtype.FuncPC(stubS20_157),
	runtype.FuncPC(stubS20_158),
	runtype.FuncPC(stubS20_159),
	runtype.FuncPC(stubS20_160),
	runtype.FuncPC(stubS20_161),
	runtype.FuncPC(stubS20_162),
	runtype.FuncPC(stubS20_163),
	runtype.FuncPC(stubS20_164),
	runtype.FuncPC(stubS20_165),
	runtype.FuncPC(stubS20_166),
	runtype.FuncPC(stubS20_167),
	runtype.FuncPC(stubS20_168),
	runtype.FuncPC(stubS20_169),
	runtype.FuncPC(stubS20_170),
	runtype.FuncPC(stubS20_171),
	runtype.FuncPC(stubS20_172),
	runtype.FuncPC(stubS20_173),
	runtype.FuncPC(stubS20_174),
	runtype.FuncPC(stubS20_175),
	runtype.FuncPC(stubS20_176),
	runtype.FuncPC(stubS20_177),
	runtype.FuncPC(stubS20_178),
	runtype.FuncPC(stubS20_179),
	runtype.FuncPC(stubS20_180),
	runtype.FuncPC(stubS20_181),
	runtype.FuncPC(stubS20_182),
	runtype.FuncPC(stubS20_183),
	runtype.FuncPC(stubS20_184),
	runtype.FuncPC(stubS20_185),
	runtype.FuncPC(stubS20_186),
	runtype.FuncPC(stubS20_187),
	runtype.FuncPC(stubS20_188),
	runtype.FuncPC(stubS20_189),
	runtype.FuncPC(stubS20_190),
	runtype.FuncPC(stubS20_191),
	runtype.FuncPC(stubS20_192),
	runtype.FuncPC(stubS20_193),
	runtype.FuncPC(stubS20_194),
	runtype.FuncPC(stubS20_195),
	runtype.FuncPC(stubS20_196),
	runtype.FuncPC(stubS20_197),
	runtype.FuncPC(stubS20_198),
	runtype.FuncPC(stubS20_199),
	runtype.FuncPC(stubS20_200),
	runtype.FuncPC(stubS20_201),
	runtype.FuncPC(stubS20_202),
	runtype.FuncPC(stubS20_203),
	runtype.FuncPC(stubS20_204),
	runtype.FuncPC(stubS20_205),
	runtype.FuncPC(stubS20_206),
	runtype.FuncPC(stubS20_207),
	runtype.FuncPC(stubS20_208),
	runtype.FuncPC(stubS20_209),
	runtype.FuncPC(stubS20_210),
	runtype.FuncPC(stubS20_211),
	runtype.FuncPC(stubS20_212),
	runtype.FuncPC(stubS20_213),
	runtype.FuncPC(stubS20_214),
	runtype.FuncPC(stubS20_215),
	runtype.FuncPC(stubS20_216),
	runtype.FuncPC(stubS20_217),
	runtype.FuncPC(stubS20_218),
	runtype.FuncPC(stubS20_219),
	runtype.FuncPC(stubS20_220),
	runtype.FuncPC(stubS20_221),
	runtype.FuncPC(stubS20_222),
	runtype.FuncPC(stubS20_223),
	runtype.FuncPC(stubS20_224),
	runtype.FuncPC(stubS20_225),
	runtype.FuncPC(stubS20_226),
	runtype.FuncPC(stubS20_227),
	runtype.FuncPC(stubS20_228),
	runtype.FuncPC(stubS20_229),
	runtype.FuncPC(stubS20_230),
	runtype.FuncPC(stubS20_231),
	runtype.FuncPC(stubS20_232),
	runtype.FuncPC(stubS20_233),
	runtype.FuncPC(stubS20_234),
	runtype.FuncPC(stubS20_235),
	runtype.FuncPC(stubS20_236),
	runtype.FuncPC(stubS20_237),
	runtype.FuncPC(stubS20_238),
	runtype.FuncPC(stubS20_239),
	runtype.FuncPC(stubS20_240),
	runtype.FuncPC(stubS20_241),
	runtype.FuncPC(stubS20_242),
	runtype.FuncPC(stubS20_243),
	runtype.FuncPC(stubS20_244),
	runtype.FuncPC(stubS20_245),
	runtype.FuncPC(stubS20_246),
	runtype.FuncPC(stubS20_247),
	runtype.FuncPC(stubS20_248),
	runtype.FuncPC(stubS20_249),
	runtype.FuncPC(stubS20_250),
	runtype.FuncPC(stubS20_251),
	runtype.FuncPC(stubS20_252),
	runtype.FuncPC(stubS20_253),
	runtype.FuncPC(stubS20_254),
	runtype.FuncPC(stubS20_255),
}
