// Code generated by gen_pools.go; DO NOT EDIT.
// Shape S17 pool: 256 slots.

package stubs

import (
	"unsafe"

	"github.com/mvm-sh/mvm/runtype"
)

const poolSizeS17 = 256

//go:noinline
func stubS17_0(recv unsafe.Pointer) (int, bool) { return dispatchS17(0, recv) }

//go:noinline
func stubS17_1(recv unsafe.Pointer) (int, bool) { return dispatchS17(1, recv) }

//go:noinline
func stubS17_2(recv unsafe.Pointer) (int, bool) { return dispatchS17(2, recv) }

//go:noinline
func stubS17_3(recv unsafe.Pointer) (int, bool) { return dispatchS17(3, recv) }

//go:noinline
func stubS17_4(recv unsafe.Pointer) (int, bool) { return dispatchS17(4, recv) }

//go:noinline
func stubS17_5(recv unsafe.Pointer) (int, bool) { return dispatchS17(5, recv) }

//go:noinline
func stubS17_6(recv unsafe.Pointer) (int, bool) { return dispatchS17(6, recv) }

//go:noinline
func stubS17_7(recv unsafe.Pointer) (int, bool) { return dispatchS17(7, recv) }

//go:noinline
func stubS17_8(recv unsafe.Pointer) (int, bool) { return dispatchS17(8, recv) }

//go:noinline
func stubS17_9(recv unsafe.Pointer) (int, bool) { return dispatchS17(9, recv) }

//go:noinline
func stubS17_10(recv unsafe.Pointer) (int, bool) { return dispatchS17(10, recv) }

//go:noinline
func stubS17_11(recv unsafe.Pointer) (int, bool) { return dispatchS17(11, recv) }

//go:noinline
func stubS17_12(recv unsafe.Pointer) (int, bool) { return dispatchS17(12, recv) }

//go:noinline
func stubS17_13(recv unsafe.Pointer) (int, bool) { return dispatchS17(13, recv) }

//go:noinline
func stubS17_14(recv unsafe.Pointer) (int, bool) { return dispatchS17(14, recv) }

//go:noinline
func stubS17_15(recv unsafe.Pointer) (int, bool) { return dispatchS17(15, recv) }

//go:noinline
func stubS17_16(recv unsafe.Pointer) (int, bool) { return dispatchS17(16, recv) }

//go:noinline
func stubS17_17(recv unsafe.Pointer) (int, bool) { return dispatchS17(17, recv) }

//go:noinline
func stubS17_18(recv unsafe.Pointer) (int, bool) { return dispatchS17(18, recv) }

//go:noinline
func stubS17_19(recv unsafe.Pointer) (int, bool) { return dispatchS17(19, recv) }

//go:noinline
func stubS17_20(recv unsafe.Pointer) (int, bool) { return dispatchS17(20, recv) }

//go:noinline
func stubS17_21(recv unsafe.Pointer) (int, bool) { return dispatchS17(21, recv) }

//go:noinline
func stubS17_22(recv unsafe.Pointer) (int, bool) { return dispatchS17(22, recv) }

//go:noinline
func stubS17_23(recv unsafe.Pointer) (int, bool) { return dispatchS17(23, recv) }

//go:noinline
func stubS17_24(recv unsafe.Pointer) (int, bool) { return dispatchS17(24, recv) }

//go:noinline
func stubS17_25(recv unsafe.Pointer) (int, bool) { return dispatchS17(25, recv) }

//go:noinline
func stubS17_26(recv unsafe.Pointer) (int, bool) { return dispatchS17(26, recv) }

//go:noinline
func stubS17_27(recv unsafe.Pointer) (int, bool) { return dispatchS17(27, recv) }

//go:noinline
func stubS17_28(recv unsafe.Pointer) (int, bool) { return dispatchS17(28, recv) }

//go:noinline
func stubS17_29(recv unsafe.Pointer) (int, bool) { return dispatchS17(29, recv) }

//go:noinline
func stubS17_30(recv unsafe.Pointer) (int, bool) { return dispatchS17(30, recv) }

//go:noinline
func stubS17_31(recv unsafe.Pointer) (int, bool) { return dispatchS17(31, recv) }

//go:noinline
func stubS17_32(recv unsafe.Pointer) (int, bool) { return dispatchS17(32, recv) }

//go:noinline
func stubS17_33(recv unsafe.Pointer) (int, bool) { return dispatchS17(33, recv) }

//go:noinline
func stubS17_34(recv unsafe.Pointer) (int, bool) { return dispatchS17(34, recv) }

//go:noinline
func stubS17_35(recv unsafe.Pointer) (int, bool) { return dispatchS17(35, recv) }

//go:noinline
func stubS17_36(recv unsafe.Pointer) (int, bool) { return dispatchS17(36, recv) }

//go:noinline
func stubS17_37(recv unsafe.Pointer) (int, bool) { return dispatchS17(37, recv) }

//go:noinline
func stubS17_38(recv unsafe.Pointer) (int, bool) { return dispatchS17(38, recv) }

//go:noinline
func stubS17_39(recv unsafe.Pointer) (int, bool) { return dispatchS17(39, recv) }

//go:noinline
func stubS17_40(recv unsafe.Pointer) (int, bool) { return dispatchS17(40, recv) }

//go:noinline
func stubS17_41(recv unsafe.Pointer) (int, bool) { return dispatchS17(41, recv) }

//go:noinline
func stubS17_42(recv unsafe.Pointer) (int, bool) { return dispatchS17(42, recv) }

//go:noinline
func stubS17_43(recv unsafe.Pointer) (int, bool) { return dispatchS17(43, recv) }

//go:noinline
func stubS17_44(recv unsafe.Pointer) (int, bool) { return dispatchS17(44, recv) }

//go:noinline
func stubS17_45(recv unsafe.Pointer) (int, bool) { return dispatchS17(45, recv) }

//go:noinline
func stubS17_46(recv unsafe.Pointer) (int, bool) { return dispatchS17(46, recv) }

//go:noinline
func stubS17_47(recv unsafe.Pointer) (int, bool) { return dispatchS17(47, recv) }

//go:noinline
func stubS17_48(recv unsafe.Pointer) (int, bool) { return dispatchS17(48, recv) }

//go:noinline
func stubS17_49(recv unsafe.Pointer) (int, bool) { return dispatchS17(49, recv) }

//go:noinline
func stubS17_50(recv unsafe.Pointer) (int, bool) { return dispatchS17(50, recv) }

//go:noinline
func stubS17_51(recv unsafe.Pointer) (int, bool) { return dispatchS17(51, recv) }

//go:noinline
func stubS17_52(recv unsafe.Pointer) (int, bool) { return dispatchS17(52, recv) }

//go:noinline
func stubS17_53(recv unsafe.Pointer) (int, bool) { return dispatchS17(53, recv) }

//go:noinline
func stubS17_54(recv unsafe.Pointer) (int, bool) { return dispatchS17(54, recv) }

//go:noinline
func stubS17_55(recv unsafe.Pointer) (int, bool) { return dispatchS17(55, recv) }

//go:noinline
func stubS17_56(recv unsafe.Pointer) (int, bool) { return dispatchS17(56, recv) }

//go:noinline
func stubS17_57(recv unsafe.Pointer) (int, bool) { return dispatchS17(57, recv) }

//go:noinline
func stubS17_58(recv unsafe.Pointer) (int, bool) { return dispatchS17(58, recv) }

//go:noinline
func stubS17_59(recv unsafe.Pointer) (int, bool) { return dispatchS17(59, recv) }

//go:noinline
func stubS17_60(recv unsafe.Pointer) (int, bool) { return dispatchS17(60, recv) }

//go:noinline
func stubS17_61(recv unsafe.Pointer) (int, bool) { return dispatchS17(61, recv) }

//go:noinline
func stubS17_62(recv unsafe.Pointer) (int, bool) { return dispatchS17(62, recv) }

//go:noinline
func stubS17_63(recv unsafe.Pointer) (int, bool) { return dispatchS17(63, recv) }

//go:noinline
func stubS17_64(recv unsafe.Pointer) (int, bool) { return dispatchS17(64, recv) }

//go:noinline
func stubS17_65(recv unsafe.Pointer) (int, bool) { return dispatchS17(65, recv) }

//go:noinline
func stubS17_66(recv unsafe.Pointer) (int, bool) { return dispatchS17(66, recv) }

//go:noinline
func stubS17_67(recv unsafe.Pointer) (int, bool) { return dispatchS17(67, recv) }

//go:noinline
func stubS17_68(recv unsafe.Pointer) (int, bool) { return dispatchS17(68, recv) }

//go:noinline
func stubS17_69(recv unsafe.Pointer) (int, bool) { return dispatchS17(69, recv) }

//go:noinline
func stubS17_70(recv unsafe.Pointer) (int, bool) { return dispatchS17(70, recv) }

//go:noinline
func stubS17_71(recv unsafe.Pointer) (int, bool) { return dispatchS17(71, recv) }

//go:noinline
func stubS17_72(recv unsafe.Pointer) (int, bool) { return dispatchS17(72, recv) }

//go:noinline
func stubS17_73(recv unsafe.Pointer) (int, bool) { return dispatchS17(73, recv) }

//go:noinline
func stubS17_74(recv unsafe.Pointer) (int, bool) { return dispatchS17(74, recv) }

//go:noinline
func stubS17_75(recv unsafe.Pointer) (int, bool) { return dispatchS17(75, recv) }

//go:noinline
func stubS17_76(recv unsafe.Pointer) (int, bool) { return dispatchS17(76, recv) }

//go:noinline
func stubS17_77(recv unsafe.Pointer) (int, bool) { return dispatchS17(77, recv) }

//go:noinline
func stubS17_78(recv unsafe.Pointer) (int, bool) { return dispatchS17(78, recv) }

//go:noinline
func stubS17_79(recv unsafe.Pointer) (int, bool) { return dispatchS17(79, recv) }

//go:noinline
func stubS17_80(recv unsafe.Pointer) (int, bool) { return dispatchS17(80, recv) }

//go:noinline
func stubS17_81(recv unsafe.Pointer) (int, bool) { return dispatchS17(81, recv) }

//go:noinline
func stubS17_82(recv unsafe.Pointer) (int, bool) { return dispatchS17(82, recv) }

//go:noinline
func stubS17_83(recv unsafe.Pointer) (int, bool) { return dispatchS17(83, recv) }

//go:noinline
func stubS17_84(recv unsafe.Pointer) (int, bool) { return dispatchS17(84, recv) }

//go:noinline
func stubS17_85(recv unsafe.Pointer) (int, bool) { return dispatchS17(85, recv) }

//go:noinline
func stubS17_86(recv unsafe.Pointer) (int, bool) { return dispatchS17(86, recv) }

//go:noinline
func stubS17_87(recv unsafe.Pointer) (int, bool) { return dispatchS17(87, recv) }

//go:noinline
func stubS17_88(recv unsafe.Pointer) (int, bool) { return dispatchS17(88, recv) }

//go:noinline
func stubS17_89(recv unsafe.Pointer) (int, bool) { return dispatchS17(89, recv) }

//go:noinline
func stubS17_90(recv unsafe.Pointer) (int, bool) { return dispatchS17(90, recv) }

//go:noinline
func stubS17_91(recv unsafe.Pointer) (int, bool) { return dispatchS17(91, recv) }

//go:noinline
func stubS17_92(recv unsafe.Pointer) (int, bool) { return dispatchS17(92, recv) }

//go:noinline
func stubS17_93(recv unsafe.Pointer) (int, bool) { return dispatchS17(93, recv) }

//go:noinline
func stubS17_94(recv unsafe.Pointer) (int, bool) { return dispatchS17(94, recv) }

//go:noinline
func stubS17_95(recv unsafe.Pointer) (int, bool) { return dispatchS17(95, recv) }

//go:noinline
func stubS17_96(recv unsafe.Pointer) (int, bool) { return dispatchS17(96, recv) }

//go:noinline
func stubS17_97(recv unsafe.Pointer) (int, bool) { return dispatchS17(97, recv) }

//go:noinline
func stubS17_98(recv unsafe.Pointer) (int, bool) { return dispatchS17(98, recv) }

//go:noinline
func stubS17_99(recv unsafe.Pointer) (int, bool) { return dispatchS17(99, recv) }

//go:noinline
func stubS17_100(recv unsafe.Pointer) (int, bool) { return dispatchS17(100, recv) }

//go:noinline
func stubS17_101(recv unsafe.Pointer) (int, bool) { return dispatchS17(101, recv) }

//go:noinline
func stubS17_102(recv unsafe.Pointer) (int, bool) { return dispatchS17(102, recv) }

//go:noinline
func stubS17_103(recv unsafe.Pointer) (int, bool) { return dispatchS17(103, recv) }

//go:noinline
func stubS17_104(recv unsafe.Pointer) (int, bool) { return dispatchS17(104, recv) }

//go:noinline
func stubS17_105(recv unsafe.Pointer) (int, bool) { return dispatchS17(105, recv) }

//go:noinline
func stubS17_106(recv unsafe.Pointer) (int, bool) { return dispatchS17(106, recv) }

//go:noinline
func stubS17_107(recv unsafe.Pointer) (int, bool) { return dispatchS17(107, recv) }

//go:noinline
func stubS17_108(recv unsafe.Pointer) (int, bool) { return dispatchS17(108, recv) }

//go:noinline
func stubS17_109(recv unsafe.Pointer) (int, bool) { return dispatchS17(109, recv) }

//go:noinline
func stubS17_110(recv unsafe.Pointer) (int, bool) { return dispatchS17(110, recv) }

//go:noinline
func stubS17_111(recv unsafe.Pointer) (int, bool) { return dispatchS17(111, recv) }

//go:noinline
func stubS17_112(recv unsafe.Pointer) (int, bool) { return dispatchS17(112, recv) }

//go:noinline
func stubS17_113(recv unsafe.Pointer) (int, bool) { return dispatchS17(113, recv) }

//go:noinline
func stubS17_114(recv unsafe.Pointer) (int, bool) { return dispatchS17(114, recv) }

//go:noinline
func stubS17_115(recv unsafe.Pointer) (int, bool) { return dispatchS17(115, recv) }

//go:noinline
func stubS17_116(recv unsafe.Pointer) (int, bool) { return dispatchS17(116, recv) }

//go:noinline
func stubS17_117(recv unsafe.Pointer) (int, bool) { return dispatchS17(117, recv) }

//go:noinline
func stubS17_118(recv unsafe.Pointer) (int, bool) { return dispatchS17(118, recv) }

//go:noinline
func stubS17_119(recv unsafe.Pointer) (int, bool) { return dispatchS17(119, recv) }

//go:noinline
func stubS17_120(recv unsafe.Pointer) (int, bool) { return dispatchS17(120, recv) }

//go:noinline
func stubS17_121(recv unsafe.Pointer) (int, bool) { return dispatchS17(121, recv) }

//go:noinline
func stubS17_122(recv unsafe.Pointer) (int, bool) { return dispatchS17(122, recv) }

//go:noinline
func stubS17_123(recv unsafe.Pointer) (int, bool) { return dispatchS17(123, recv) }

//go:noinline
func stubS17_124(recv unsafe.Pointer) (int, bool) { return dispatchS17(124, recv) }

//go:noinline
func stubS17_125(recv unsafe.Pointer) (int, bool) { return dispatchS17(125, recv) }

//go:noinline
func stubS17_126(recv unsafe.Pointer) (int, bool) { return dispatchS17(126, recv) }

//go:noinline
func stubS17_127(recv unsafe.Pointer) (int, bool) { return dispatchS17(127, recv) }

//go:noinline
func stubS17_128(recv unsafe.Pointer) (int, bool) { return dispatchS17(128, recv) }

//go:noinline
func stubS17_129(recv unsafe.Pointer) (int, bool) { return dispatchS17(129, recv) }

//go:noinline
func stubS17_130(recv unsafe.Pointer) (int, bool) { return dispatchS17(130, recv) }

//go:noinline
func stubS17_131(recv unsafe.Pointer) (int, bool) { return dispatchS17(131, recv) }

//go:noinline
func stubS17_132(recv unsafe.Pointer) (int, bool) { return dispatchS17(132, recv) }

//go:noinline
func stubS17_133(recv unsafe.Pointer) (int, bool) { return dispatchS17(133, recv) }

//go:noinline
func stubS17_134(recv unsafe.Pointer) (int, bool) { return dispatchS17(134, recv) }

//go:noinline
func stubS17_135(recv unsafe.Pointer) (int, bool) { return dispatchS17(135, recv) }

//go:noinline
func stubS17_136(recv unsafe.Pointer) (int, bool) { return dispatchS17(136, recv) }

//go:noinline
func stubS17_137(recv unsafe.Pointer) (int, bool) { return dispatchS17(137, recv) }

//go:noinline
func stubS17_138(recv unsafe.Pointer) (int, bool) { return dispatchS17(138, recv) }

//go:noinline
func stubS17_139(recv unsafe.Pointer) (int, bool) { return dispatchS17(139, recv) }

//go:noinline
func stubS17_140(recv unsafe.Pointer) (int, bool) { return dispatchS17(140, recv) }

//go:noinline
func stubS17_141(recv unsafe.Pointer) (int, bool) { return dispatchS17(141, recv) }

//go:noinline
func stubS17_142(recv unsafe.Pointer) (int, bool) { return dispatchS17(142, recv) }

//go:noinline
func stubS17_143(recv unsafe.Pointer) (int, bool) { return dispatchS17(143, recv) }

//go:noinline
func stubS17_144(recv unsafe.Pointer) (int, bool) { return dispatchS17(144, recv) }

//go:noinline
func stubS17_145(recv unsafe.Pointer) (int, bool) { return dispatchS17(145, recv) }

//go:noinline
func stubS17_146(recv unsafe.Pointer) (int, bool) { return dispatchS17(146, recv) }

//go:noinline
func stubS17_147(recv unsafe.Pointer) (int, bool) { return dispatchS17(147, recv) }

//go:noinline
func stubS17_148(recv unsafe.Pointer) (int, bool) { return dispatchS17(148, recv) }

//go:noinline
func stubS17_149(recv unsafe.Pointer) (int, bool) { return dispatchS17(149, recv) }

//go:noinline
func stubS17_150(recv unsafe.Pointer) (int, bool) { return dispatchS17(150, recv) }

//go:noinline
func stubS17_151(recv unsafe.Pointer) (int, bool) { return dispatchS17(151, recv) }

//go:noinline
func stubS17_152(recv unsafe.Pointer) (int, bool) { return dispatchS17(152, recv) }

//go:noinline
func stubS17_153(recv unsafe.Pointer) (int, bool) { return dispatchS17(153, recv) }

//go:noinline
func stubS17_154(recv unsafe.Pointer) (int, bool) { return dispatchS17(154, recv) }

//go:noinline
func stubS17_155(recv unsafe.Pointer) (int, bool) { return dispatchS17(155, recv) }

//go:noinline
func stubS17_156(recv unsafe.Pointer) (int, bool) { return dispatchS17(156, recv) }

//go:noinline
func stubS17_157(recv unsafe.Pointer) (int, bool) { return dispatchS17(157, recv) }

//go:noinline
func stubS17_158(recv unsafe.Pointer) (int, bool) { return dispatchS17(158, recv) }

//go:noinline
func stubS17_159(recv unsafe.Pointer) (int, bool) { return dispatchS17(159, recv) }

//go:noinline
func stubS17_160(recv unsafe.Pointer) (int, bool) { return dispatchS17(160, recv) }

//go:noinline
func stubS17_161(recv unsafe.Pointer) (int, bool) { return dispatchS17(161, recv) }

//go:noinline
func stubS17_162(recv unsafe.Pointer) (int, bool) { return dispatchS17(162, recv) }

//go:noinline
func stubS17_163(recv unsafe.Pointer) (int, bool) { return dispatchS17(163, recv) }

//go:noinline
func stubS17_164(recv unsafe.Pointer) (int, bool) { return dispatchS17(164, recv) }

//go:noinline
func stubS17_165(recv unsafe.Pointer) (int, bool) { return dispatchS17(165, recv) }

//go:noinline
func stubS17_166(recv unsafe.Pointer) (int, bool) { return dispatchS17(166, recv) }

//go:noinline
func stubS17_167(recv unsafe.Pointer) (int, bool) { return dispatchS17(167, recv) }

//go:noinline
func stubS17_168(recv unsafe.Pointer) (int, bool) { return dispatchS17(168, recv) }

//go:noinline
func stubS17_169(recv unsafe.Pointer) (int, bool) { return dispatchS17(169, recv) }

//go:noinline
func stubS17_170(recv unsafe.Pointer) (int, bool) { return dispatchS17(170, recv) }

//go:noinline
func stubS17_171(recv unsafe.Pointer) (int, bool) { return dispatchS17(171, recv) }

//go:noinline
func stubS17_172(recv unsafe.Pointer) (int, bool) { return dispatchS17(172, recv) }

//go:noinline
func stubS17_173(recv unsafe.Pointer) (int, bool) { return dispatchS17(173, recv) }

//go:noinline
func stubS17_174(recv unsafe.Pointer) (int, bool) { return dispatchS17(174, recv) }

//go:noinline
func stubS17_175(recv unsafe.Pointer) (int, bool) { return dispatchS17(175, recv) }

//go:noinline
func stubS17_176(recv unsafe.Pointer) (int, bool) { return dispatchS17(176, recv) }

//go:noinline
func stubS17_177(recv unsafe.Pointer) (int, bool) { return dispatchS17(177, recv) }

//go:noinline
func stubS17_178(recv unsafe.Pointer) (int, bool) { return dispatchS17(178, recv) }

//go:noinline
func stubS17_179(recv unsafe.Pointer) (int, bool) { return dispatchS17(179, recv) }

//go:noinline
func stubS17_180(recv unsafe.Pointer) (int, bool) { return dispatchS17(180, recv) }

//go:noinline
func stubS17_181(recv unsafe.Pointer) (int, bool) { return dispatchS17(181, recv) }

//go:noinline
func stubS17_182(recv unsafe.Pointer) (int, bool) { return dispatchS17(182, recv) }

//go:noinline
func stubS17_183(recv unsafe.Pointer) (int, bool) { return dispatchS17(183, recv) }

//go:noinline
func stubS17_184(recv unsafe.Pointer) (int, bool) { return dispatchS17(184, recv) }

//go:noinline
func stubS17_185(recv unsafe.Pointer) (int, bool) { return dispatchS17(185, recv) }

//go:noinline
func stubS17_186(recv unsafe.Pointer) (int, bool) { return dispatchS17(186, recv) }

//go:noinline
func stubS17_187(recv unsafe.Pointer) (int, bool) { return dispatchS17(187, recv) }

//go:noinline
func stubS17_188(recv unsafe.Pointer) (int, bool) { return dispatchS17(188, recv) }

//go:noinline
func stubS17_189(recv unsafe.Pointer) (int, bool) { return dispatchS17(189, recv) }

//go:noinline
func stubS17_190(recv unsafe.Pointer) (int, bool) { return dispatchS17(190, recv) }

//go:noinline
func stubS17_191(recv unsafe.Pointer) (int, bool) { return dispatchS17(191, recv) }

//go:noinline
func stubS17_192(recv unsafe.Pointer) (int, bool) { return dispatchS17(192, recv) }

//go:noinline
func stubS17_193(recv unsafe.Pointer) (int, bool) { return dispatchS17(193, recv) }

//go:noinline
func stubS17_194(recv unsafe.Pointer) (int, bool) { return dispatchS17(194, recv) }

//go:noinline
func stubS17_195(recv unsafe.Pointer) (int, bool) { return dispatchS17(195, recv) }

//go:noinline
func stubS17_196(recv unsafe.Pointer) (int, bool) { return dispatchS17(196, recv) }

//go:noinline
func stubS17_197(recv unsafe.Pointer) (int, bool) { return dispatchS17(197, recv) }

//go:noinline
func stubS17_198(recv unsafe.Pointer) (int, bool) { return dispatchS17(198, recv) }

//go:noinline
func stubS17_199(recv unsafe.Pointer) (int, bool) { return dispatchS17(199, recv) }

//go:noinline
func stubS17_200(recv unsafe.Pointer) (int, bool) { return dispatchS17(200, recv) }

//go:noinline
func stubS17_201(recv unsafe.Pointer) (int, bool) { return dispatchS17(201, recv) }

//go:noinline
func stubS17_202(recv unsafe.Pointer) (int, bool) { return dispatchS17(202, recv) }

//go:noinline
func stubS17_203(recv unsafe.Pointer) (int, bool) { return dispatchS17(203, recv) }

//go:noinline
func stubS17_204(recv unsafe.Pointer) (int, bool) { return dispatchS17(204, recv) }

//go:noinline
func stubS17_205(recv unsafe.Pointer) (int, bool) { return dispatchS17(205, recv) }

//go:noinline
func stubS17_206(recv unsafe.Pointer) (int, bool) { return dispatchS17(206, recv) }

//go:noinline
func stubS17_207(recv unsafe.Pointer) (int, bool) { return dispatchS17(207, recv) }

//go:noinline
func stubS17_208(recv unsafe.Pointer) (int, bool) { return dispatchS17(208, recv) }

//go:noinline
func stubS17_209(recv unsafe.Pointer) (int, bool) { return dispatchS17(209, recv) }

//go:noinline
func stubS17_210(recv unsafe.Pointer) (int, bool) { return dispatchS17(210, recv) }

//go:noinline
func stubS17_211(recv unsafe.Pointer) (int, bool) { return dispatchS17(211, recv) }

//go:noinline
func stubS17_212(recv unsafe.Pointer) (int, bool) { return dispatchS17(212, recv) }

//go:noinline
func stubS17_213(recv unsafe.Pointer) (int, bool) { return dispatchS17(213, recv) }

//go:noinline
func stubS17_214(recv unsafe.Pointer) (int, bool) { return dispatchS17(214, recv) }

//go:noinline
func stubS17_215(recv unsafe.Pointer) (int, bool) { return dispatchS17(215, recv) }

//go:noinline
func stubS17_216(recv unsafe.Pointer) (int, bool) { return dispatchS17(216, recv) }

//go:noinline
func stubS17_217(recv unsafe.Pointer) (int, bool) { return dispatchS17(217, recv) }

//go:noinline
func stubS17_218(recv unsafe.Pointer) (int, bool) { return dispatchS17(218, recv) }

//go:noinline
func stubS17_219(recv unsafe.Pointer) (int, bool) { return dispatchS17(219, recv) }

//go:noinline
func stubS17_220(recv unsafe.Pointer) (int, bool) { return dispatchS17(220, recv) }

//go:noinline
func stubS17_221(recv unsafe.Pointer) (int, bool) { return dispatchS17(221, recv) }

//go:noinline
func stubS17_222(recv unsafe.Pointer) (int, bool) { return dispatchS17(222, recv) }

//go:noinline
func stubS17_223(recv unsafe.Pointer) (int, bool) { return dispatchS17(223, recv) }

//go:noinline
func stubS17_224(recv unsafe.Pointer) (int, bool) { return dispatchS17(224, recv) }

//go:noinline
func stubS17_225(recv unsafe.Pointer) (int, bool) { return dispatchS17(225, recv) }

//go:noinline
func stubS17_226(recv unsafe.Pointer) (int, bool) { return dispatchS17(226, recv) }

//go:noinline
func stubS17_227(recv unsafe.Pointer) (int, bool) { return dispatchS17(227, recv) }

//go:noinline
func stubS17_228(recv unsafe.Pointer) (int, bool) { return dispatchS17(228, recv) }

//go:noinline
func stubS17_229(recv unsafe.Pointer) (int, bool) { return dispatchS17(229, recv) }

//go:noinline
func stubS17_230(recv unsafe.Pointer) (int, bool) { return dispatchS17(230, recv) }

//go:noinline
func stubS17_231(recv unsafe.Pointer) (int, bool) { return dispatchS17(231, recv) }

//go:noinline
func stubS17_232(recv unsafe.Pointer) (int, bool) { return dispatchS17(232, recv) }

//go:noinline
func stubS17_233(recv unsafe.Pointer) (int, bool) { return dispatchS17(233, recv) }

//go:noinline
func stubS17_234(recv unsafe.Pointer) (int, bool) { return dispatchS17(234, recv) }

//go:noinline
func stubS17_235(recv unsafe.Pointer) (int, bool) { return dispatchS17(235, recv) }

//go:noinline
func stubS17_236(recv unsafe.Pointer) (int, bool) { return dispatchS17(236, recv) }

//go:noinline
func stubS17_237(recv unsafe.Pointer) (int, bool) { return dispatchS17(237, recv) }

//go:noinline
func stubS17_238(recv unsafe.Pointer) (int, bool) { return dispatchS17(238, recv) }

//go:noinline
func stubS17_239(recv unsafe.Pointer) (int, bool) { return dispatchS17(239, recv) }

//go:noinline
func stubS17_240(recv unsafe.Pointer) (int, bool) { return dispatchS17(240, recv) }

//go:noinline
func stubS17_241(recv unsafe.Pointer) (int, bool) { return dispatchS17(241, recv) }

//go:noinline
func stubS17_242(recv unsafe.Pointer) (int, bool) { return dispatchS17(242, recv) }

//go:noinline
func stubS17_243(recv unsafe.Pointer) (int, bool) { return dispatchS17(243, recv) }

//go:noinline
func stubS17_244(recv unsafe.Pointer) (int, bool) { return dispatchS17(244, recv) }

//go:noinline
func stubS17_245(recv unsafe.Pointer) (int, bool) { return dispatchS17(245, recv) }

//go:noinline
func stubS17_246(recv unsafe.Pointer) (int, bool) { return dispatchS17(246, recv) }

//go:noinline
func stubS17_247(recv unsafe.Pointer) (int, bool) { return dispatchS17(247, recv) }

//go:noinline
func stubS17_248(recv unsafe.Pointer) (int, bool) { return dispatchS17(248, recv) }

//go:noinline
func stubS17_249(recv unsafe.Pointer) (int, bool) { return dispatchS17(249, recv) }

//go:noinline
func stubS17_250(recv unsafe.Pointer) (int, bool) { return dispatchS17(250, recv) }

//go:noinline
func stubS17_251(recv unsafe.Pointer) (int, bool) { return dispatchS17(251, recv) }

//go:noinline
func stubS17_252(recv unsafe.Pointer) (int, bool) { return dispatchS17(252, recv) }

//go:noinline
func stubS17_253(recv unsafe.Pointer) (int, bool) { return dispatchS17(253, recv) }

//go:noinline
func stubS17_254(recv unsafe.Pointer) (int, bool) { return dispatchS17(254, recv) }

//go:noinline
func stubS17_255(recv unsafe.Pointer) (int, bool) { return dispatchS17(255, recv) }

var stubsS17 = [poolSizeS17]uintptr{
	runtype.FuncPC(stubS17_0),
	runtype.FuncPC(stubS17_1),
	runtype.FuncPC(stubS17_2),
	runtype.FuncPC(stubS17_3),
	runtype.FuncPC(stubS17_4),
	runtype.FuncPC(stubS17_5),
	runtype.FuncPC(stubS17_6),
	runtype.FuncPC(stubS17_7),
	runtype.FuncPC(stubS17_8),
	runtype.FuncPC(stubS17_9),
	runtype.FuncPC(stubS17_10),
	runtype.FuncPC(stubS17_11),
	runtype.FuncPC(stubS17_12),
	runtype.FuncPC(stubS17_13),
	runtype.FuncPC(stubS17_14),
	runtype.FuncPC(stubS17_15),
	runtype.FuncPC(stubS17_16),
	runtype.FuncPC(stubS17_17),
	runtype.FuncPC(stubS17_18),
	runtype.FuncPC(stubS17_19),
	runtype.FuncPC(stubS17_20),
	runtype.FuncPC(stubS17_21),
	runtype.FuncPC(stubS17_22),
	runtype.FuncPC(stubS17_23),
	runtype.FuncPC(stubS17_24),
	runtype.FuncPC(stubS17_25),
	runtype.FuncPC(stubS17_26),
	runtype.FuncPC(stubS17_27),
	runtype.FuncPC(stubS17_28),
	runtype.FuncPC(stubS17_29),
	runtype.FuncPC(stubS17_30),
	runtype.FuncPC(stubS17_31),
	runtype.FuncPC(stubS17_32),
	runtype.FuncPC(stubS17_33),
	runtype.FuncPC(stubS17_34),
	runtype.FuncPC(stubS17_35),
	runtype.FuncPC(stubS17_36),
	runtype.FuncPC(stubS17_37),
	runtype.FuncPC(stubS17_38),
	runtype.FuncPC(stubS17_39),
	runtype.FuncPC(stubS17_40),
	runtype.FuncPC(stubS17_41),
	runtype.FuncPC(stubS17_42),
	runtype.FuncPC(stubS17_43),
	runtype.FuncPC(stubS17_44),
	runtype.FuncPC(stubS17_45),
	runtype.FuncPC(stubS17_46),
	runtype.FuncPC(stubS17_47),
	runtype.FuncPC(stubS17_48),
	runtype.FuncPC(stubS17_49),
	runtype.FuncPC(stubS17_50),
	runtype.FuncPC(stubS17_51),
	runtype.FuncPC(stubS17_52),
	runtype.FuncPC(stubS17_53),
	runtype.FuncPC(stubS17_54),
	runtype.FuncPC(stubS17_55),
	runtype.FuncPC(stubS17_56),
	runtype.FuncPC(stubS17_57),
	runtype.FuncPC(stubS17_58),
	runtype.FuncPC(stubS17_59),
	runtype.FuncPC(stubS17_60),
	runtype.FuncPC(stubS17_61),
	runtype.FuncPC(stubS17_62),
	runtype.FuncPC(stubS17_63),
	runtype.FuncPC(stubS17_64),
	runtype.FuncPC(stubS17_65),
	runtype.FuncPC(stubS17_66),
	runtype.FuncPC(stubS17_67),
	runtype.FuncPC(stubS17_68),
	runtype.FuncPC(stubS17_69),
	runtype.FuncPC(stubS17_70),
	runtype.FuncPC(stubS17_71),
	runtype.FuncPC(stubS17_72),
	runtype.FuncPC(stubS17_73),
	runtype.FuncPC(stubS17_74),
	runtype.FuncPC(stubS17_75),
	runtype.FuncPC(stubS17_76),
	runtype.FuncPC(stubS17_77),
	runtype.FuncPC(stubS17_78),
	runtype.FuncPC(stubS17_79),
	runtype.FuncPC(stubS17_80),
	runtype.FuncPC(stubS17_81),
	runtype.FuncPC(stubS17_82),
	runtype.FuncPC(stubS17_83),
	runtype.FuncPC(stubS17_84),
	runtype.FuncPC(stubS17_85),
	runtype.FuncPC(stubS17_86),
	runtype.FuncPC(stubS17_87),
	runtype.FuncPC(stubS17_88),
	runtype.FuncPC(stubS17_89),
	runtype.FuncPC(stubS17_90),
	runtype.FuncPC(stubS17_91),
	runtype.FuncPC(stubS17_92),
	runtype.FuncPC(stubS17_93),
	runtype.FuncPC(stubS17_94),
	runtype.FuncPC(stubS17_95),
	runtype.FuncPC(stubS17_96),
	runtype.FuncPC(stubS17_97),
	runtype.FuncPC(stubS17_98),
	runtype.FuncPC(stubS17_99),
	runtype.FuncPC(stubS17_100),
	runtype.FuncPC(stubS17_101),
	runtype.FuncPC(stubS17_102),
	runtype.FuncPC(stubS17_103),
	runtype.FuncPC(stubS17_104),
	runtype.FuncPC(stubS17_105),
	runtype.FuncPC(stubS17_106),
	runtype.FuncPC(stubS17_107),
	runtype.FuncPC(stubS17_108),
	runtype.FuncPC(stubS17_109),
	runtype.FuncPC(stubS17_110),
	runtype.FuncPC(stubS17_111),
	runtype.FuncPC(stubS17_112),
	runtype.FuncPC(stubS17_113),
	runtype.FuncPC(stubS17_114),
	runtype.FuncPC(stubS17_115),
	runtype.FuncPC(stubS17_116),
	runtype.FuncPC(stubS17_117),
	runtype.FuncPC(stubS17_118),
	runtype.FuncPC(stubS17_119),
	runtype.FuncPC(stubS17_120),
	runtype.FuncPC(stubS17_121),
	runtype.FuncPC(stubS17_122),
	runtype.FuncPC(stubS17_123),
	runtype.FuncPC(stubS17_124),
	runtype.FuncPC(stubS17_125),
	runtype.FuncPC(stubS17_126),
	runtype.FuncPC(stubS17_127),
	runtype.FuncPC(stubS17_128),
	runtype.FuncPC(stubS17_129),
	runtype.FuncPC(stubS17_130),
	runtype.FuncPC(stubS17_131),
	runtype.FuncPC(stubS17_132),
	runtype.FuncPC(stubS17_133),
	runtype.FuncPC(stubS17_134),
	runtype.FuncPC(stubS17_135),
	runtype.FuncPC(stubS17_136),
	runtype.FuncPC(stubS17_137),
	runtype.FuncPC(stubS17_138),
	runtype.FuncPC(stubS17_139),
	runtype.FuncPC(stubS17_140),
	runtype.FuncPC(stubS17_141),
	runtype.FuncPC(stubS17_142),
	runtype.FuncPC(stubS17_143),
	runtype.FuncPC(stubS17_144),
	runtype.FuncPC(stubS17_145),
	runtype.FuncPC(stubS17_146),
	runtype.FuncPC(stubS17_147),
	runtype.FuncPC(stubS17_148),
	runtype.FuncPC(stubS17_149),
	runtype.FuncPC(stubS17_150),
	runtype.FuncPC(stubS17_151),
	runtype.FuncPC(stubS17_152),
	runtype.FuncPC(stubS17_153),
	runtype.FuncPC(stubS17_154),
	runtype.FuncPC(stubS17_155),
	runtype.FuncPC(stubS17_156),
	runtype.FuncPC(stubS17_157),
	runtype.FuncPC(stubS17_158),
	runtype.FuncPC(stubS17_159),
	runtype.FuncPC(stubS17_160),
	runtype.FuncPC(stubS17_161),
	runtype.FuncPC(stubS17_162),
	runtype.FuncPC(stubS17_163),
	runtype.FuncPC(stubS17_164),
	runtype.FuncPC(stubS17_165),
	runtype.FuncPC(stubS17_166),
	runtype.FuncPC(stubS17_167),
	runtype.FuncPC(stubS17_168),
	runtype.FuncPC(stubS17_169),
	runtype.FuncPC(stubS17_170),
	runtype.FuncPC(stubS17_171),
	runtype.FuncPC(stubS17_172),
	runtype.FuncPC(stubS17_173),
	runtype.FuncPC(stubS17_174),
	runtype.FuncPC(stubS17_175),
	runtype.FuncPC(stubS17_176),
	runtype.FuncPC(stubS17_177),
	runtype.FuncPC(stubS17_178),
	runtype.FuncPC(stubS17_179),
	runtype.FuncPC(stubS17_180),
	runtype.FuncPC(stubS17_181),
	runtype.FuncPC(stubS17_182),
	runtype.FuncPC(stubS17_183),
	runtype.FuncPC(stubS17_184),
	runtype.FuncPC(stubS17_185),
	runtype.FuncPC(stubS17_186),
	runtype.FuncPC(stubS17_187),
	runtype.FuncPC(stubS17_188),
	runtype.FuncPC(stubS17_189),
	runtype.FuncPC(stubS17_190),
	runtype.FuncPC(stubS17_191),
	runtype.FuncPC(stubS17_192),
	runtype.FuncPC(stubS17_193),
	runtype.FuncPC(stubS17_194),
	runtype.FuncPC(stubS17_195),
	runtype.FuncPC(stubS17_196),
	runtype.FuncPC(stubS17_197),
	runtype.FuncPC(stubS17_198),
	runtype.FuncPC(stubS17_199),
	runtype.FuncPC(stubS17_200),
	runtype.FuncPC(stubS17_201),
	runtype.FuncPC(stubS17_202),
	runtype.FuncPC(stubS17_203),
	runtype.FuncPC(stubS17_204),
	runtype.FuncPC(stubS17_205),
	runtype.FuncPC(stubS17_206),
	runtype.FuncPC(stubS17_207),
	runtype.FuncPC(stubS17_208),
	runtype.FuncPC(stubS17_209),
	runtype.FuncPC(stubS17_210),
	runtype.FuncPC(stubS17_211),
	runtype.FuncPC(stubS17_212),
	runtype.FuncPC(stubS17_213),
	runtype.FuncPC(stubS17_214),
	runtype.FuncPC(stubS17_215),
	runtype.FuncPC(stubS17_216),
	runtype.FuncPC(stubS17_217),
	runtype.FuncPC(stubS17_218),
	runtype.FuncPC(stubS17_219),
	runtype.FuncPC(stubS17_220),
	runtype.FuncPC(stubS17_221),
	runtype.FuncPC(stubS17_222),
	runtype.FuncPC(stubS17_223),
	runtype.FuncPC(stubS17_224),
	runtype.FuncPC(stubS17_225),
	runtype.FuncPC(stubS17_226),
	runtype.FuncPC(stubS17_227),
	runtype.FuncPC(stubS17_228),
	runtype.FuncPC(stubS17_229),
	runtype.FuncPC(stubS17_230),
	runtype.FuncPC(stubS17_231),
	runtype.FuncPC(stubS17_232),
	runtype.FuncPC(stubS17_233),
	runtype.FuncPC(stubS17_234),
	runtype.FuncPC(stubS17_235),
	runtype.FuncPC(stubS17_236),
	runtype.FuncPC(stubS17_237),
	runtype.FuncPC(stubS17_238),
	runtype.FuncPC(stubS17_239),
	runtype.FuncPC(stubS17_240),
	runtype.FuncPC(stubS17_241),
	runtype.FuncPC(stubS17_242),
	runtype.FuncPC(stubS17_243),
	runtype.FuncPC(stubS17_244),
	runtype.FuncPC(stubS17_245),
	runtype.FuncPC(stubS17_246),
	runtype.FuncPC(stubS17_247),
	runtype.FuncPC(stubS17_248),
	runtype.FuncPC(stubS17_249),
	runtype.FuncPC(stubS17_250),
	runtype.FuncPC(stubS17_251),
	runtype.FuncPC(stubS17_252),
	runtype.FuncPC(stubS17_253),
	runtype.FuncPC(stubS17_254),
	runtype.FuncPC(stubS17_255),
}
