// Code generated by gen_pools.go; DO NOT EDIT.
// Shape S33 pool: 256 slots.

package stubs

import (
	"context"
	"log/slog"
	"unsafe"

	"github.com/mvm-sh/mvm/runtype"
)

const poolSizeS33 = 256

//go:noinline
func stubS33_0(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(0, recv, ctx, record)
}

//go:noinline
func stubS33_1(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(1, recv, ctx, record)
}

//go:noinline
func stubS33_2(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(2, recv, ctx, record)
}

//go:noinline
func stubS33_3(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(3, recv, ctx, record)
}

//go:noinline
func stubS33_4(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(4, recv, ctx, record)
}

//go:noinline
func stubS33_5(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(5, recv, ctx, record)
}

//go:noinline
func stubS33_6(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(6, recv, ctx, record)
}

//go:noinline
func stubS33_7(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(7, recv, ctx, record)
}

//go:noinline
func stubS33_8(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(8, recv, ctx, record)
}

//go:noinline
func stubS33_9(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(9, recv, ctx, record)
}

//go:noinline
func stubS33_10(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(10, recv, ctx, record)
}

//go:noinline
func stubS33_11(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(11, recv, ctx, record)
}

//go:noinline
func stubS33_12(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(12, recv, ctx, record)
}

//go:noinline
func stubS33_13(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(13, recv, ctx, record)
}

//go:noinline
func stubS33_14(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(14, recv, ctx, record)
}

//go:noinline
func stubS33_15(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(15, recv, ctx, record)
}

//go:noinline
func stubS33_16(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(16, recv, ctx, record)
}

//go:noinline
func stubS33_17(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(17, recv, ctx, record)
}

//go:noinline
func stubS33_18(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(18, recv, ctx, record)
}

//go:noinline
func stubS33_19(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(19, recv, ctx, record)
}

//go:noinline
func stubS33_20(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(20, recv, ctx, record)
}

//go:noinline
func stubS33_21(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(21, recv, ctx, record)
}

//go:noinline
func stubS33_22(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(22, recv, ctx, record)
}

//go:noinline
func stubS33_23(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(23, recv, ctx, record)
}

//go:noinline
func stubS33_24(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(24, recv, ctx, record)
}

//go:noinline
func stubS33_25(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(25, recv, ctx, record)
}

//go:noinline
func stubS33_26(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(26, recv, ctx, record)
}

//go:noinline
func stubS33_27(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(27, recv, ctx, record)
}

//go:noinline
func stubS33_28(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(28, recv, ctx, record)
}

//go:noinline
func stubS33_29(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(29, recv, ctx, record)
}

//go:noinline
func stubS33_30(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(30, recv, ctx, record)
}

//go:noinline
func stubS33_31(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(31, recv, ctx, record)
}

//go:noinline
func stubS33_32(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(32, recv, ctx, record)
}

//go:noinline
func stubS33_33(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(33, recv, ctx, record)
}

//go:noinline
func stubS33_34(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(34, recv, ctx, record)
}

//go:noinline
func stubS33_35(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(35, recv, ctx, record)
}

//go:noinline
func stubS33_36(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(36, recv, ctx, record)
}

//go:noinline
func stubS33_37(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(37, recv, ctx, record)
}

//go:noinline
func stubS33_38(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(38, recv, ctx, record)
}

//go:noinline
func stubS33_39(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(39, recv, ctx, record)
}

//go:noinline
func stubS33_40(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(40, recv, ctx, record)
}

//go:noinline
func stubS33_41(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(41, recv, ctx, record)
}

//go:noinline
func stubS33_42(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(42, recv, ctx, record)
}

//go:noinline
func stubS33_43(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(43, recv, ctx, record)
}

//go:noinline
func stubS33_44(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(44, recv, ctx, record)
}

//go:noinline
func stubS33_45(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(45, recv, ctx, record)
}

//go:noinline
func stubS33_46(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(46, recv, ctx, record)
}

//go:noinline
func stubS33_47(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(47, recv, ctx, record)
}

//go:noinline
func stubS33_48(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(48, recv, ctx, record)
}

//go:noinline
func stubS33_49(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(49, recv, ctx, record)
}

//go:noinline
func stubS33_50(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(50, recv, ctx, record)
}

//go:noinline
func stubS33_51(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(51, recv, ctx, record)
}

//go:noinline
func stubS33_52(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(52, recv, ctx, record)
}

//go:noinline
func stubS33_53(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(53, recv, ctx, record)
}

//go:noinline
func stubS33_54(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(54, recv, ctx, record)
}

//go:noinline
func stubS33_55(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(55, recv, ctx, record)
}

//go:noinline
func stubS33_56(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(56, recv, ctx, record)
}

//go:noinline
func stubS33_57(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(57, recv, ctx, record)
}

//go:noinline
func stubS33_58(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(58, recv, ctx, record)
}

//go:noinline
func stubS33_59(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(59, recv, ctx, record)
}

//go:noinline
func stubS33_60(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(60, recv, ctx, record)
}

//go:noinline
func stubS33_61(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(61, recv, ctx, record)
}

//go:noinline
func stubS33_62(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(62, recv, ctx, record)
}

//go:noinline
func stubS33_63(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(63, recv, ctx, record)
}

//go:noinline
func stubS33_64(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(64, recv, ctx, record)
}

//go:noinline
func stubS33_65(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(65, recv, ctx, record)
}

//go:noinline
func stubS33_66(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(66, recv, ctx, record)
}

//go:noinline
func stubS33_67(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(67, recv, ctx, record)
}

//go:noinline
func stubS33_68(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(68, recv, ctx, record)
}

//go:noinline
func stubS33_69(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(69, recv, ctx, record)
}

//go:noinline
func stubS33_70(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(70, recv, ctx, record)
}

//go:noinline
func stubS33_71(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(71, recv, ctx, record)
}

//go:noinline
func stubS33_72(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(72, recv, ctx, record)
}

//go:noinline
func stubS33_73(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(73, recv, ctx, record)
}

//go:noinline
func stubS33_74(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(74, recv, ctx, record)
}

//go:noinline
func stubS33_75(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(75, recv, ctx, record)
}

//go:noinline
func stubS33_76(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(76, recv, ctx, record)
}

//go:noinline
func stubS33_77(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(77, recv, ctx, record)
}

//go:noinline
func stubS33_78(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(78, recv, ctx, record)
}

//go:noinline
func stubS33_79(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(79, recv, ctx, record)
}

//go:noinline
func stubS33_80(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(80, recv, ctx, record)
}

//go:noinline
func stubS33_81(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(81, recv, ctx, record)
}

//go:noinline
func stubS33_82(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(82, recv, ctx, record)
}

//go:noinline
func stubS33_83(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(83, recv, ctx, record)
}

//go:noinline
func stubS33_84(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(84, recv, ctx, record)
}

//go:noinline
func stubS33_85(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(85, recv, ctx, record)
}

//go:noinline
func stubS33_86(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(86, recv, ctx, record)
}

//go:noinline
func stubS33_87(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(87, recv, ctx, record)
}

//go:noinline
func stubS33_88(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(88, recv, ctx, record)
}

//go:noinline
func stubS33_89(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(89, recv, ctx, record)
}

//go:noinline
func stubS33_90(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(90, recv, ctx, record)
}

//go:noinline
func stubS33_91(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(91, recv, ctx, record)
}

//go:noinline
func stubS33_92(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(92, recv, ctx, record)
}

//go:noinline
func stubS33_93(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(93, recv, ctx, record)
}

//go:noinline
func stubS33_94(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(94, recv, ctx, record)
}

//go:noinline
func stubS33_95(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(95, recv, ctx, record)
}

//go:noinline
func stubS33_96(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(96, recv, ctx, record)
}

//go:noinline
func stubS33_97(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(97, recv, ctx, record)
}

//go:noinline
func stubS33_98(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(98, recv, ctx, record)
}

//go:noinline
func stubS33_99(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(99, recv, ctx, record)
}

//go:noinline
func stubS33_100(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(100, recv, ctx, record)
}

//go:noinline
func stubS33_101(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(101, recv, ctx, record)
}

//go:noinline
func stubS33_102(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(102, recv, ctx, record)
}

//go:noinline
func stubS33_103(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(103, recv, ctx, record)
}

//go:noinline
func stubS33_104(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(104, recv, ctx, record)
}

//go:noinline
func stubS33_105(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(105, recv, ctx, record)
}

//go:noinline
func stubS33_106(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(106, recv, ctx, record)
}

//go:noinline
func stubS33_107(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(107, recv, ctx, record)
}

//go:noinline
func stubS33_108(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(108, recv, ctx, record)
}

//go:noinline
func stubS33_109(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(109, recv, ctx, record)
}

//go:noinline
func stubS33_110(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(110, recv, ctx, record)
}

//go:noinline
func stubS33_111(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(111, recv, ctx, record)
}

//go:noinline
func stubS33_112(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(112, recv, ctx, record)
}

//go:noinline
func stubS33_113(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(113, recv, ctx, record)
}

//go:noinline
func stubS33_114(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(114, recv, ctx, record)
}

//go:noinline
func stubS33_115(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(115, recv, ctx, record)
}

//go:noinline
func stubS33_116(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(116, recv, ctx, record)
}

//go:noinline
func stubS33_117(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(117, recv, ctx, record)
}

//go:noinline
func stubS33_118(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(118, recv, ctx, record)
}

//go:noinline
func stubS33_119(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(119, recv, ctx, record)
}

//go:noinline
func stubS33_120(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(120, recv, ctx, record)
}

//go:noinline
func stubS33_121(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(121, recv, ctx, record)
}

//go:noinline
func stubS33_122(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(122, recv, ctx, record)
}

//go:noinline
func stubS33_123(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(123, recv, ctx, record)
}

//go:noinline
func stubS33_124(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(124, recv, ctx, record)
}

//go:noinline
func stubS33_125(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(125, recv, ctx, record)
}

//go:noinline
func stubS33_126(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(126, recv, ctx, record)
}

//go:noinline
func stubS33_127(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(127, recv, ctx, record)
}

//go:noinline
func stubS33_128(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(128, recv, ctx, record)
}

//go:noinline
func stubS33_129(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(129, recv, ctx, record)
}

//go:noinline
func stubS33_130(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(130, recv, ctx, record)
}

//go:noinline
func stubS33_131(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(131, recv, ctx, record)
}

//go:noinline
func stubS33_132(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(132, recv, ctx, record)
}

//go:noinline
func stubS33_133(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(133, recv, ctx, record)
}

//go:noinline
func stubS33_134(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(134, recv, ctx, record)
}

//go:noinline
func stubS33_135(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(135, recv, ctx, record)
}

//go:noinline
func stubS33_136(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(136, recv, ctx, record)
}

//go:noinline
func stubS33_137(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(137, recv, ctx, record)
}

//go:noinline
func stubS33_138(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(138, recv, ctx, record)
}

//go:noinline
func stubS33_139(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(139, recv, ctx, record)
}

//go:noinline
func stubS33_140(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(140, recv, ctx, record)
}

//go:noinline
func stubS33_141(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(141, recv, ctx, record)
}

//go:noinline
func stubS33_142(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(142, recv, ctx, record)
}

//go:noinline
func stubS33_143(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(143, recv, ctx, record)
}

//go:noinline
func stubS33_144(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(144, recv, ctx, record)
}

//go:noinline
func stubS33_145(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(145, recv, ctx, record)
}

//go:noinline
func stubS33_146(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(146, recv, ctx, record)
}

//go:noinline
func stubS33_147(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(147, recv, ctx, record)
}

//go:noinline
func stubS33_148(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(148, recv, ctx, record)
}

//go:noinline
func stubS33_149(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(149, recv, ctx, record)
}

//go:noinline
func stubS33_150(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(150, recv, ctx, record)
}

//go:noinline
func stubS33_151(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(151, recv, ctx, record)
}

//go:noinline
func stubS33_152(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(152, recv, ctx, record)
}

//go:noinline
func stubS33_153(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(153, recv, ctx, record)
}

//go:noinline
func stubS33_154(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(154, recv, ctx, record)
}

//go:noinline
func stubS33_155(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(155, recv, ctx, record)
}

//go:noinline
func stubS33_156(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(156, recv, ctx, record)
}

//go:noinline
func stubS33_157(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(157, recv, ctx, record)
}

//go:noinline
func stubS33_158(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(158, recv, ctx, record)
}

//go:noinline
func stubS33_159(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(159, recv, ctx, record)
}

//go:noinline
func stubS33_160(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(160, recv, ctx, record)
}

//go:noinline
func stubS33_161(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(161, recv, ctx, record)
}

//go:noinline
func stubS33_162(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(162, recv, ctx, record)
}

//go:noinline
func stubS33_163(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(163, recv, ctx, record)
}

//go:noinline
func stubS33_164(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(164, recv, ctx, record)
}

//go:noinline
func stubS33_165(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(165, recv, ctx, record)
}

//go:noinline
func stubS33_166(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(166, recv, ctx, record)
}

//go:noinline
func stubS33_167(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(167, recv, ctx, record)
}

//go:noinline
func stubS33_168(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(168, recv, ctx, record)
}

//go:noinline
func stubS33_169(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(169, recv, ctx, record)
}

//go:noinline
func stubS33_170(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(170, recv, ctx, record)
}

//go:noinline
func stubS33_171(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(171, recv, ctx, record)
}

//go:noinline
func stubS33_172(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(172, recv, ctx, record)
}

//go:noinline
func stubS33_173(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(173, recv, ctx, record)
}

//go:noinline
func stubS33_174(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(174, recv, ctx, record)
}

//go:noinline
func stubS33_175(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(175, recv, ctx, record)
}

//go:noinline
func stubS33_176(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(176, recv, ctx, record)
}

//go:noinline
func stubS33_177(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(177, recv, ctx, record)
}

//go:noinline
func stubS33_178(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(178, recv, ctx, record)
}

//go:noinline
func stubS33_179(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(179, recv, ctx, record)
}

//go:noinline
func stubS33_180(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(180, recv, ctx, record)
}

//go:noinline
func stubS33_181(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(181, recv, ctx, record)
}

//go:noinline
func stubS33_182(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(182, recv, ctx, record)
}

//go:noinline
func stubS33_183(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(183, recv, ctx, record)
}

//go:noinline
func stubS33_184(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(184, recv, ctx, record)
}

//go:noinline
func stubS33_185(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(185, recv, ctx, record)
}

//go:noinline
func stubS33_186(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(186, recv, ctx, record)
}

//go:noinline
func stubS33_187(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(187, recv, ctx, record)
}

//go:noinline
func stubS33_188(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(188, recv, ctx, record)
}

//go:noinline
func stubS33_189(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(189, recv, ctx, record)
}

//go:noinline
func stubS33_190(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(190, recv, ctx, record)
}

//go:noinline
func stubS33_191(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(191, recv, ctx, record)
}

//go:noinline
func stubS33_192(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(192, recv, ctx, record)
}

//go:noinline
func stubS33_193(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(193, recv, ctx, record)
}

//go:noinline
func stubS33_194(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(194, recv, ctx, record)
}

//go:noinline
func stubS33_195(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(195, recv, ctx, record)
}

//go:noinline
func stubS33_196(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(196, recv, ctx, record)
}

//go:noinline
func stubS33_197(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(197, recv, ctx, record)
}

//go:noinline
func stubS33_198(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(198, recv, ctx, record)
}

//go:noinline
func stubS33_199(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(199, recv, ctx, record)
}

//go:noinline
func stubS33_200(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(200, recv, ctx, record)
}

//go:noinline
func stubS33_201(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(201, recv, ctx, record)
}

//go:noinline
func stubS33_202(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(202, recv, ctx, record)
}

//go:noinline
func stubS33_203(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(203, recv, ctx, record)
}

//go:noinline
func stubS33_204(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(204, recv, ctx, record)
}

//go:noinline
func stubS33_205(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(205, recv, ctx, record)
}

//go:noinline
func stubS33_206(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(206, recv, ctx, record)
}

//go:noinline
func stubS33_207(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(207, recv, ctx, record)
}

//go:noinline
func stubS33_208(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(208, recv, ctx, record)
}

//go:noinline
func stubS33_209(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(209, recv, ctx, record)
}

//go:noinline
func stubS33_210(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(210, recv, ctx, record)
}

//go:noinline
func stubS33_211(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(211, recv, ctx, record)
}

//go:noinline
func stubS33_212(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(212, recv, ctx, record)
}

//go:noinline
func stubS33_213(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(213, recv, ctx, record)
}

//go:noinline
func stubS33_214(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(214, recv, ctx, record)
}

//go:noinline
func stubS33_215(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(215, recv, ctx, record)
}

//go:noinline
func stubS33_216(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(216, recv, ctx, record)
}

//go:noinline
func stubS33_217(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(217, recv, ctx, record)
}

//go:noinline
func stubS33_218(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(218, recv, ctx, record)
}

//go:noinline
func stubS33_219(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(219, recv, ctx, record)
}

//go:noinline
func stubS33_220(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(220, recv, ctx, record)
}

//go:noinline
func stubS33_221(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(221, recv, ctx, record)
}

//go:noinline
func stubS33_222(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(222, recv, ctx, record)
}

//go:noinline
func stubS33_223(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(223, recv, ctx, record)
}

//go:noinline
func stubS33_224(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(224, recv, ctx, record)
}

//go:noinline
func stubS33_225(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(225, recv, ctx, record)
}

//go:noinline
func stubS33_226(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(226, recv, ctx, record)
}

//go:noinline
func stubS33_227(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(227, recv, ctx, record)
}

//go:noinline
func stubS33_228(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(228, recv, ctx, record)
}

//go:noinline
func stubS33_229(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(229, recv, ctx, record)
}

//go:noinline
func stubS33_230(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(230, recv, ctx, record)
}

//go:noinline
func stubS33_231(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(231, recv, ctx, record)
}

//go:noinline
func stubS33_232(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(232, recv, ctx, record)
}

//go:noinline
func stubS33_233(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(233, recv, ctx, record)
}

//go:noinline
func stubS33_234(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(234, recv, ctx, record)
}

//go:noinline
func stubS33_235(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(235, recv, ctx, record)
}

//go:noinline
func stubS33_236(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(236, recv, ctx, record)
}

//go:noinline
func stubS33_237(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(237, recv, ctx, record)
}

//go:noinline
func stubS33_238(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(238, recv, ctx, record)
}

//go:noinline
func stubS33_239(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(239, recv, ctx, record)
}

//go:noinline
func stubS33_240(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(240, recv, ctx, record)
}

//go:noinline
func stubS33_241(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(241, recv, ctx, record)
}

//go:noinline
func stubS33_242(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(242, recv, ctx, record)
}

//go:noinline
func stubS33_243(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(243, recv, ctx, record)
}

//go:noinline
func stubS33_244(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(244, recv, ctx, record)
}

//go:noinline
func stubS33_245(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(245, recv, ctx, record)
}

//go:noinline
func stubS33_246(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(246, recv, ctx, record)
}

//go:noinline
func stubS33_247(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(247, recv, ctx, record)
}

//go:noinline
func stubS33_248(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(248, recv, ctx, record)
}

//go:noinline
func stubS33_249(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(249, recv, ctx, record)
}

//go:noinline
func stubS33_250(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(250, recv, ctx, record)
}

//go:noinline
func stubS33_251(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(251, recv, ctx, record)
}

//go:noinline
func stubS33_252(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(252, recv, ctx, record)
}

//go:noinline
func stubS33_253(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(253, recv, ctx, record)
}

//go:noinline
func stubS33_254(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(254, recv, ctx, record)
}

//go:noinline
func stubS33_255(recv unsafe.Pointer, ctx context.Context, record slog.Record) error {
	return dispatchS33(255, recv, ctx, record)
}

var stubsS33 = [poolSizeS33]uintptr{
	runtype.FuncPC(stubS33_0),
	runtype.FuncPC(stubS33_1),
	runtype.FuncPC(stubS33_2),
	runtype.FuncPC(stubS33_3),
	runtype.FuncPC(stubS33_4),
	runtype.FuncPC(stubS33_5),
	runtype.FuncPC(stubS33_6),
	runtype.FuncPC(stubS33_7),
	runtype.FuncPC(stubS33_8),
	runtype.FuncPC(stubS33_9),
	runtype.FuncPC(stubS33_10),
	runtype.FuncPC(stubS33_11),
	runtype.FuncPC(stubS33_12),
	runtype.FuncPC(stubS33_13),
	runtype.FuncPC(stubS33_14),
	runtype.FuncPC(stubS33_15),
	runtype.FuncPC(stubS33_16),
	runtype.FuncPC(stubS33_17),
	runtype.FuncPC(stubS33_18),
	runtype.FuncPC(stubS33_19),
	runtype.FuncPC(stubS33_20),
	runtype.FuncPC(stubS33_21),
	runtype.FuncPC(stubS33_22),
	runtype.FuncPC(stubS33_23),
	runtype.FuncPC(stubS33_24),
	runtype.FuncPC(stubS33_25),
	runtype.FuncPC(stubS33_26),
	runtype.FuncPC(stubS33_27),
	runtype.FuncPC(stubS33_28),
	runtype.FuncPC(stubS33_29),
	runtype.FuncPC(stubS33_30),
	runtype.FuncPC(stubS33_31),
	runtype.FuncPC(stubS33_32),
	runtype.FuncPC(stubS33_33),
	runtype.FuncPC(stubS33_34),
	runtype.FuncPC(stubS33_35),
	runtype.FuncPC(stubS33_36),
	runtype.FuncPC(stubS33_37),
	runtype.FuncPC(stubS33_38),
	runtype.FuncPC(stubS33_39),
	runtype.FuncPC(stubS33_40),
	runtype.FuncPC(stubS33_41),
	runtype.FuncPC(stubS33_42),
	runtype.FuncPC(stubS33_43),
	runtype.FuncPC(stubS33_44),
	runtype.FuncPC(stubS33_45),
	runtype.FuncPC(stubS33_46),
	runtype.FuncPC(stubS33_47),
	runtype.FuncPC(stubS33_48),
	runtype.FuncPC(stubS33_49),
	runtype.FuncPC(stubS33_50),
	runtype.FuncPC(stubS33_51),
	runtype.FuncPC(stubS33_52),
	runtype.FuncPC(stubS33_53),
	runtype.FuncPC(stubS33_54),
	runtype.FuncPC(stubS33_55),
	runtype.FuncPC(stubS33_56),
	runtype.FuncPC(stubS33_57),
	runtype.FuncPC(stubS33_58),
	runtype.FuncPC(stubS33_59),
	runtype.FuncPC(stubS33_60),
	runtype.FuncPC(stubS33_61),
	runtype.FuncPC(stubS33_62),
	runtype.FuncPC(stubS33_63),
	runtype.FuncPC(stubS33_64),
	runtype.FuncPC(stubS33_65),
	runtype.FuncPC(stubS33_66),
	runtype.FuncPC(stubS33_67),
	runtype.FuncPC(stubS33_68),
	runtype.FuncPC(stubS33_69),
	runtype.FuncPC(stubS33_70),
	runtype.FuncPC(stubS33_71),
	runtype.FuncPC(stubS33_72),
	runtype.FuncPC(stubS33_73),
	runtype.FuncPC(stubS33_74),
	runtype.FuncPC(stubS33_75),
	runtype.FuncPC(stubS33_76),
	runtype.FuncPC(stubS33_77),
	runtype.FuncPC(stubS33_78),
	runtype.FuncPC(stubS33_79),
	runtype.FuncPC(stubS33_80),
	runtype.FuncPC(stubS33_81),
	runtype.FuncPC(stubS33_82),
	runtype.FuncPC(stubS33_83),
	runtype.FuncPC(stubS33_84),
	runtype.FuncPC(stubS33_85),
	runtype.FuncPC(stubS33_86),
	runtype.FuncPC(stubS33_87),
	runtype.FuncPC(stubS33_88),
	runtype.FuncPC(stubS33_89),
	runtype.FuncPC(stubS33_90),
	runtype.FuncPC(stubS33_91),
	runtype.FuncPC(stubS33_92),
	runtype.FuncPC(stubS33_93),
	runtype.FuncPC(stubS33_94),
	runtype.FuncPC(stubS33_95),
	runtype.FuncPC(stubS33_96),
	runtype.FuncPC(stubS33_97),
	runtype.FuncPC(stubS33_98),
	runtype.FuncPC(stubS33_99),
	runtype.FuncPC(stubS33_100),
	runtype.FuncPC(stubS33_101),
	runtype.FuncPC(stubS33_102),
	runtype.FuncPC(stubS33_103),
	runtype.FuncPC(stubS33_104),
	runtype.FuncPC(stubS33_105),
	runtype.FuncPC(stubS33_106),
	runtype.FuncPC(stubS33_107),
	runtype.FuncPC(stubS33_108),
	runtype.FuncPC(stubS33_109),
	runtype.FuncPC(stubS33_110),
	runtype.FuncPC(stubS33_111),
	runtype.FuncPC(stubS33_112),
	runtype.FuncPC(stubS33_113),
	runtype.FuncPC(stubS33_114),
	runtype.FuncPC(stubS33_115),
	runtype.FuncPC(stubS33_116),
	runtype.FuncPC(stubS33_117),
	runtype.FuncPC(stubS33_118),
	runtype.FuncPC(stubS33_119),
	runtype.FuncPC(stubS33_120),
	runtype.FuncPC(stubS33_121),
	runtype.FuncPC(stubS33_122),
	runtype.FuncPC(stubS33_123),
	runtype.FuncPC(stubS33_124),
	runtype.FuncPC(stubS33_125),
	runtype.FuncPC(stubS33_126),
	runtype.FuncPC(stubS33_127),
	runtype.FuncPC(stubS33_128),
	runtype.FuncPC(stubS33_129),
	runtype.FuncPC(stubS33_130),
	runtype.FuncPC(stubS33_131),
	runtype.FuncPC(stubS33_132),
	runtype.FuncPC(stubS33_133),
	runtype.FuncPC(stubS33_134),
	runtype.FuncPC(stubS33_135),
	runtype.FuncPC(stubS33_136),
	runtype.FuncPC(stubS33_137),
	runtype.FuncPC(stubS33_138),
	runtype.FuncPC(stubS33_139),
	runtype.FuncPC(stubS33_140),
	runtype.FuncPC(stubS33_141),
	runtype.FuncPC(stubS33_142),
	runtype.FuncPC(stubS33_143),
	runtype.FuncPC(stubS33_144),
	runtype.FuncPC(stubS33_145),
	runtype.FuncPC(stubS33_146),
	runtype.FuncPC(stubS33_147),
	runtype.FuncPC(stubS33_148),
	runtype.FuncPC(stubS33_149),
	runtype.FuncPC(stubS33_150),
	runtype.FuncPC(stubS33_151),
	runtype.FuncPC(stubS33_152),
	runtype.FuncPC(stubS33_153),
	runtype.FuncPC(stubS33_154),
	runtype.FuncPC(stubS33_155),
	runtype.FuncPC(stubS33_156),
	runtype.FuncPC(stubS33_157),
	runtype.FuncPC(stubS33_158),
	runtype.FuncPC(stubS33_159),
	runtype.FuncPC(stubS33_160),
	runtype.FuncPC(stubS33_161),
	runtype.FuncPC(stubS33_162),
	runtype.FuncPC(stubS33_163),
	runtype.FuncPC(stubS33_164),
	runtype.FuncPC(stubS33_165),
	runtype.FuncPC(stubS33_166),
	runtype.FuncPC(stubS33_167),
	runtype.FuncPC(stubS33_168),
	runtype.FuncPC(stubS33_169),
	runtype.FuncPC(stubS33_170),
	runtype.FuncPC(stubS33_171),
	runtype.FuncPC(stubS33_172),
	runtype.FuncPC(stubS33_173),
	runtype.FuncPC(stubS33_174),
	runtype.FuncPC(stubS33_175),
	runtype.FuncPC(stubS33_176),
	runtype.FuncPC(stubS33_177),
	runtype.FuncPC(stubS33_178),
	runtype.FuncPC(stubS33_179),
	runtype.FuncPC(stubS33_180),
	runtype.FuncPC(stubS33_181),
	runtype.FuncPC(stubS33_182),
	runtype.FuncPC(stubS33_183),
	runtype.FuncPC(stubS33_184),
	runtype.FuncPC(stubS33_185),
	runtype.FuncPC(stubS33_186),
	runtype.FuncPC(stubS33_187),
	runtype.FuncPC(stubS33_188),
	runtype.FuncPC(stubS33_189),
	runtype.FuncPC(stubS33_190),
	runtype.FuncPC(stubS33_191),
	runtype.FuncPC(stubS33_192),
	runtype.FuncPC(stubS33_193),
	runtype.FuncPC(stubS33_194),
	runtype.FuncPC(stubS33_195),
	runtype.FuncPC(stubS33_196),
	runtype.FuncPC(stubS33_197),
	runtype.FuncPC(stubS33_198),
	runtype.FuncPC(stubS33_199),
	runtype.FuncPC(stubS33_200),
	runtype.FuncPC(stubS33_201),
	runtype.FuncPC(stubS33_202),
	runtype.FuncPC(stubS33_203),
	runtype.FuncPC(stubS33_204),
	runtype.FuncPC(stubS33_205),
	runtype.FuncPC(stubS33_206),
	runtype.FuncPC(stubS33_207),
	runtype.FuncPC(stubS33_208),
	runtype.FuncPC(stubS33_209),
	runtype.FuncPC(stubS33_210),
	runtype.FuncPC(stubS33_211),
	runtype.FuncPC(stubS33_212),
	runtype.FuncPC(stubS33_213),
	runtype.FuncPC(stubS33_214),
	runtype.FuncPC(stubS33_215),
	runtype.FuncPC(stubS33_216),
	runtype.FuncPC(stubS33_217),
	runtype.FuncPC(stubS33_218),
	runtype.FuncPC(stubS33_219),
	runtype.FuncPC(stubS33_220),
	runtype.FuncPC(stubS33_221),
	runtype.FuncPC(stubS33_222),
	runtype.FuncPC(stubS33_223),
	runtype.FuncPC(stubS33_224),
	runtype.FuncPC(stubS33_225),
	runtype.FuncPC(stubS33_226),
	runtype.FuncPC(stubS33_227),
	runtype.FuncPC(stubS33_228),
	runtype.FuncPC(stubS33_229),
	runtype.FuncPC(stubS33_230),
	runtype.FuncPC(stubS33_231),
	runtype.FuncPC(stubS33_232),
	runtype.FuncPC(stubS33_233),
	runtype.FuncPC(stubS33_234),
	runtype.FuncPC(stubS33_235),
	runtype.FuncPC(stubS33_236),
	runtype.FuncPC(stubS33_237),
	runtype.FuncPC(stubS33_238),
	runtype.FuncPC(stubS33_239),
	runtype.FuncPC(stubS33_240),
	runtype.FuncPC(stubS33_241),
	runtype.FuncPC(stubS33_242),
	runtype.FuncPC(stubS33_243),
	runtype.FuncPC(stubS33_244),
	runtype.FuncPC(stubS33_245),
	runtype.FuncPC(stubS33_246),
	runtype.FuncPC(stubS33_247),
	runtype.FuncPC(stubS33_248),
	runtype.FuncPC(stubS33_249),
	runtype.FuncPC(stubS33_250),
	runtype.FuncPC(stubS33_251),
	runtype.FuncPC(stubS33_252),
	runtype.FuncPC(stubS33_253),
	runtype.FuncPC(stubS33_254),
	runtype.FuncPC(stubS33_255),
}
